const linkResources = {
    "Accessibility Standards Canada": "https://yiopjq.ph.files.1drv.com/y4mxMCw4xhJrG78wWXFizgbGEnpn-4SnbNZi_xDsyrXEQsNwmrvodedePRnEfkzxM7nYE99E7Y1u7R28-i-1NnIYmPmFvRMrUaobEdLNE04YH_zl9AU1F-sLukmID0YEzhU8f0KVqgMPzG7idL_l--mNw7NI6551Gv84VZTpglRBr-qExBl15UpVlDiIS0S7ETQ0O7wMGdeg5nUo-G7jHpdWg", 
    "Administrative Tribunals Support Service of Canada": "https://yiopjq.ph.files.1drv.com/y4m6UH0qffIgSAn59WEItrftrDA1QEseJtgXaDqOjot2PKZEG6C1lO2Jmocp322ibd82ItKJOKPAV2XC64ZZ66pJYyeiBYYKMPmUAQ7H34xeQwvl15Ewd-3MDSVA87pDUKgdylgq3Umx7E3-QzI1eI8JkpA-OR9-t4fKChsKD8WNs96pVZaAUeQIzbl3tK4ZDRP8HSe0mxdsEsdAJG429v97A", 
    "Agriculture and Agri-Food Canada": "https://yiopjq.ph.files.1drv.com/y4mgOLGqGSUNmlW8yqWLECeDnvfBWfbLnrFP8GlE72mpv_BNSEXCnaZFIPqHeQfHkTXsA0fQXOXD7ms-sVQI5gfLw2PMgW_ckAaThjM7ioqK2HmoG367EHD4a09Ngn-n-BoW9Bh-0TNhwtaSCDQskihS_2R--rB9OZjfhXTxXBNDVrITS-_lKK3kppx6-T1UjO6OxpbLvD62wWoZFHy1L7VAA", 
    "Association of Professional Executives of the Public Service of Canada": "https://yiopjq.ph.files.1drv.com/y4mw6-kKtsGiywhUYrP7zbb9I1tXNVY9ZULi187MupaerDZdGMzixwUQZxN1b7tVdVxhSCkYAMt838qBZeOom3WRra7SLWdgQcrpmYj9W4LZKn_6k_BUPXWiTF86NZ2HLia0yGEGZ6p6ugDT8LwhEr-VWs8E7ZUjriZ9s1TpoOTZzXXIF3PPv9zsF533_aM1DepPkD5SAREj013r01h9c_L_A", 
    "Atlantic Canada Opportunities Agency": "https://yiopjq.ph.files.1drv.com/y4m3UEH4Zewm640jeQqEr9lgtYcl6nEwcgs2JRptdTKad6XNi4p4n27xyj_aT3mmtBUXZiQlukwhvGR69GqdqRyt1-biBpWCeNskp4Ext4i7gmpx5V1kxH9dX7yPilhR7zmgCDgbKxeRuWXw5UZ4WUYbTEzSzIt8FxptNM7v_OLnVYFE5GM1qUfxspp-gUfpVz07r1cImPOkgu7ftw2Ouv1XQ", 
    "Atlantic Pilotage Authority": "https://yiopjq.ph.files.1drv.com/y4mXHD0D5qpjQZFLG97t5w9eq2tedKWmQ6BxtLcWaQZng3IhJyu5WtQOo2O3_7w37ztldNFJ0iy0CCOvtaLwOBq_TNQDZlonQWBYZShCbGJ5qvNHOmIsmDel5uSVJGgoYuJRcNtrMsLViJd_SpgAZoW5VOj8EVbPHpY9wtwswoIsXe_2haawocQd5VZj8TB3YNAvXfl_EDRakKqbQZ0Z7GcFQ", 
    "Atomic Energy of Canada Limited": "https://yiopjq.ph.files.1drv.com/y4mxbkLm0f99L-HnWjtEi147LSHdpC7sAewlAcLEACOwh9VAINfRRHL5qHxX4dcZp43V5HLyrkxYCtIUG-cig-zrL4Il5QopxjUp6-tN1DMUZG5HtHk5U5b8pF7oM171N5ZmN3_IQ8A86EhcyS5Sce63pJLTuk55wPHaaXCylW2--2ptzsFjWx34oB5J1puuf2mQhXAX3aWMrC1LWbxTX8Yjw", 
    "Canada Agricultural Review Tribunal": "https://yiopjq.ph.files.1drv.com/y4mkuRnQlezeHOJMxjGU4tEN7wzJx6XqqMJwukaVfgjsrBVbvBL_vrXPHAUdrGzBWh7l5NM99lRqaIzqbI-YH2hyb5qVtFi7-FfKdOFnK_vxVzd5jySwaeVqC9KZXqBLzM1MHDZkoTGM8-4wuby6YeEJ3ccVvjpgLAEdHZ6Be7ha-0x8LG4KKRDXgivc0Ae51mfesBbXUSI6q21zrRG0s0jqg", 
    "Canada Border Services Agency": "https://yiopjq.ph.files.1drv.com/y4mK9IZZSSAloGL3zNZaPpe58m2Nn37QbUSTW6c2iiHd1InGKZPJppJ9UdbopK26npBIH0omYoAbmUvg942HxJcltbLLKn8zFREa2FRtjbJQalxu3rBXQ0MF0ia8zTaNesEoiwXMbYXb7jEpYOuBZVn-EqOQ30COAdXbSvNCZpDM6rtIXxEqJ3XBUDynpBQ3saE3MYXEek8dNsbQeJsy_npmw", 
    "Canada Council for the Arts": "https://yiopjq.ph.files.1drv.com/y4mqyZz5Mzkwu4XAijbVllvw0yZC5uP0tdwGLNntyCtgy6TT9B4imjiYl2YrsbpIvKWb2yDAs0x2HiqHfmxMZNgDkLsUdzLp4ALDsOlnUy9ouoD37egfc9VSKcVK2hBrdzZQhei5fyYC0EoiyTWKHUR-vKkHPX-AZJdMgHXNvy9SbU6gmIIXiijIXWMEJv23SaZHDSdIQfvDAAawdyL8TR7qg", 
    "Canada Economic Development for Quebec Regions": "https://yiopjq.ph.files.1drv.com/y4m6oEnZu4V93C4BZx-XrckUR22UUE0TmzULJMuJcVy3d4no57jueHFtXuqlEZue3nwmFmfCZGGrrwlW-PENlMwM-b3DCW8DjydR7FDbSQQgWqj0FPtIyDZwxoLiX5HqB1VQaQbiEYfgk9pn6KGyox7SvgRDzcyFzpBs6Wzn5zKzisOHMdCRVtlU1iK6g-EWmjLjv6cgV_dzlGA8B1ELbYgrA", 
    "Canada Energy Regulator": "https://yiopjq.ph.files.1drv.com/y4mLqTGJyo4_E_J840fc09Vsn5xFdyCUVnDZ2a4vuhVI0L2PZidYfA-rAeBUr4FsIEb_GhfNzTw6rfehxM6yiNN1TBiAYCmyq5cdTvGcgXdj1pRKuyPgfFLzki3cE0zRsDOLjcZQ6cxqUWa6dGEfKhorFO1eFrxLg57pm6bdVSpuZ2N_uiGtujvDNxDPBaSVQ04Tt3h3jAKEOQHpbilBERXFw", 
    "Canada Industrial Relations Board": "https://yiopjq.ph.files.1drv.com/y4mOXmIWxvTxzagO_3l52wVIf0NFgPqCiOL9JU1INJh3htKXZ0ExSbvC_DUe9h7wcWxchjZuNxMbKYHob6TWfm0o7o3ZCDfFck3p38LngrYhvYATUF3WYdJLoKHcQyBEI_NzvmF6NMKz2utTKo_WBru67v-H0TgCYqrpL157ZJoDyMGt64fD5mpfp4HKpkiahUv-XbJfBIWtfK3TDPZTM1AnQ", 
    "Canada Mortgage and Housing Corporation": "https://yiopjq.ph.files.1drv.com/y4mlmimVsGzNtSxa_-YBDN5HpR1hi21AQ1McT-yo0XEFap9wFd3a7MPE3JcLkPg0M4C9Npdds79zEn8nT6NfykJglh3XlHwCZ148RscVCKyg7IQdGaq1pjjnE7HrqsWzkkHSbrfYQRl49H8U6aG2PBeFBkSr-8g_T3va-Aek7oH5a87oRiSz3yNgsrfsrU-SemfiCBPkwCTms4qumJc4I86MQ", 
    "Canada Revenue Agency": "https://yiopjq.ph.files.1drv.com/y4mMF6rhBgF5Ug-oUBh7z1cdxndijGyFt8tYZzd2iDdFV59R-pkbXL9eZQNGZu89bGmG5QOK-t6laQj368ZGhzmXx2r_IgWF30DX1xmxklyjvaq1NmAHyk8crYyuF6EBHxb8mIQzR27BywkOqfVdUATwmCeDl-EUGmlR-__Ido-60UPiqlc6eGP20hwhDNNvc0GSE8050qahckc_A15lNIDhg", 
    "Canada School of Public Service": "https://yiopjq.ph.files.1drv.com/y4m6LU2J6BCk1xWanfIUn15AMDgvdmJ1Q7G7Du16J0qjviE0bg3o5CwFo9FRrntzEOoFUWfqPMCZLWa-UpOktXlqUxZmIOxOiYxoLiA4dUIvdLUrRYnmHqrAOpCn3-DK9XxSe_tVWBP_Vv488OW9IEhWGSCWIEfXoGGNYCcvyEEBrQkUfukrm5vA4Vhhm6LlIaQ1evwCzEIa9f8PUzosrkn6g", 
    "Canadian Air Transport Security Authority": "https://yiopjq.ph.files.1drv.com/y4maWLwOOSTbCfhKKlzknHy5iO5sTDJzP9bH7J66WfbBKGSlAEM5CuB6ZNZCJEq_7N5lJ4Mkpv7p25C2PChK4xp95Ay_UnBsR1sRw5_989iRBJSr_f2EDTU0uLuQNI-qmjaHi4sRJDjyiYvqLFAThEl8Dgg_KQWB-oNh7K89HGSwJ9ksaV9-7LbsVPfN7xmbcDHF1H1amAIh6sgbzcgpiF3Mg", 
    "Canadian Centre for Occupational Health and Safety": "https://yiopjq.ph.files.1drv.com/y4m0PNciSxn8OnBQTaso7ylsU6dqby4KKQ29Ac5EbTOhvVW0mpp6dvjeYKkV13gQUFU8h7RPueM5aARNt3y1OCnM1vQdJXmh8rYi833JIC1izmxNXoOhTB1uJ886u__K-G0-6qWRrtVXAqdCBgMNlgHU4XtlM8ciFEWXsGoZmrw0cCbK4RyK0P7TwygB3UtiVhTfFZyW7lYGl7JCzpErjJjFQ", 
    "Canadian Centre on Substance Abuse": "https://yiopjq.ph.files.1drv.com/y4m1-M4Mi90aiBasCV9LeaAn0cQt_p0-riFmwhMfhxBGVsTznrGf7dREVBcv_xeoIDxxBcZWiHREUoO4eZDZSHo7EFrGbe0Sa4HtmAp1fC7SA-ZllPceuyzZ8lTal6hKKOdZy1YGWZnxF7_Ly8nnihh9Eddpu3qNvyBGlZmbmocv0-nlHJhhuiS2Mka59jSwKvKAi2LBfVeUMVtTUFq-sXM0g", 
    "Canadian Commercial Corporation": "https://yiopjq.ph.files.1drv.com/y4mqyROJ2y4lcnzrUSa4LEIroXmyHeC8DMVjCgBJEM508c7O_ptoj6TC8RHIAurngaTnM2gTSTXMxTUod-ZbeHzvX-d59R4VOB6JMb19Iv8UhUUgHq5iCSXSSXrtoasECEd6oCKceFyQSnXAD4RiMxGZlBJSSKq1BHfeXe7EUs_mec51XYgojNsg824sE7IdN939WaYowUQpL2ODNJc3qNTxQ", 
    "Canadian Dairy Commission": "https://yiopjq.ph.files.1drv.com/y4muJdpvfUCSbIqbrW4QZyGeuMnbYKyupNSe7cGyididZ5gJ3cQWAVQWzwHnaATJLi3ZynpLhSnmqX_-OD-NGJhET2eCjj9Tgwppy2oiKxPawPwczOVcwamgyjUs9b3uYrBliHHEXGMU3cz1W_g2ra9ieNt9uyJQLfbSyiKkjdJzxWYLSG5KydeYVTcNsQDToZHXuRi30AxuJrVQJOcJ_jJRw", 
    "Canadian Food Inspection Agency": "https://yiopjq.ph.files.1drv.com/y4m-enNTz9EDJCKdbPzX9UDcit6eDvhX1BU_jo2V0OIalRW7T1DwijPzhh3opXxE3_vi6zjawJJbTF0pQ4VCOG2C8Zi5LfqCREVJLE9ziRWMAH_Si7sUAv0MTkwX4DxVfxFoN5T7dawAojJPn1RVp3MrAB2OgRuIUA3SBF62y9EEtH4tkEDiYVmmK_u7JD9Qyj98mOrBZUVB7MPW6yyR_SiCA", 
    "Canadian Grain Commission": "https://yiopjq.ph.files.1drv.com/y4mNuB1UyGAsj1iX16kMFOqpGxmkQMuNmPG1B7SHojLCEcBhweVnXzW0oALlGbNdz2YRIWBTn2ELCzHc3fruFZc0tPbtkvwNuA11152CXOqn-7MG68E1AyXXVzCVO3cV1WdYzVMvLiO4Clq21sExqasUvPkLknsSN-jMF5yUphGWYByx3gyogFI7TYqQbm6wLdktJGq1qhd3f-LyLGsASV6MQ", 
    "Canadian Heritage": "https://yiopjq.ph.files.1drv.com/y4m7MR7-5jxZGQnZ3THapIx1BOQ3Uy3LbJY3cmcWTu2cY7mC-kF2_UewtfUhn-U8BHILqX8M3hqjXZAWLghKQekX5LYq0ZCFJTGEggelh29UIpGoPyFafyaWk9NncZfGeYkAIPkUU_iJl01771orTnkCLlJsfu-ff68D3iPbBvAFUrFt1xigVGOw2oxy0cyE4-IqlpxOibSgyOOloWIyMOszA", 
    "Canadian Human Rights Commission": "https://yiopjq.ph.files.1drv.com/y4muz7rlOamB8DiZeBwlz_Hky9E277kNMpeAeYN8oi6pSgwrvnpCVHB9nhBvbCwVnKz2Ka9uinmbh9nK9oVbJB6ii_KzxzlmVL6rCkmP6Aqn34n4bS4cwwucTBcaRcsxfikiEhXJodPoVDZQHTD_59W6-A1FL-yjy-tzaDv4ggT74ECVUjGLVY-vv70wlgGnE8JMI8V4SgOUUmVaD5cb7EjgA", 
    "Canadian Human Rights Tribunal": "https://yiopjq.ph.files.1drv.com/y4m7ZDxKRnYM3WozqAhX2BWr1fW6o3FozSy6iZlM-mUc2_mVPKsvfllfaSxKwJ-Rt1rqEZnXP9twBm18odR3xCg7LaYemY3KaoOyPejmBbaJu-I0wIkIGoTQjdTbQLeL74NJGVAQM6ERyvFwLqEip_bNsQrTTy_-8qwI16StGBVME95QqhZid4yigvo8hdd95Af82qoyRQkrwGa6i9PSV5MXg", 
    "Canadian Institutes of Health Research": "https://yiopjq.ph.files.1drv.com/y4mALCwu6KuaJj3qLrX5MT0HeJhyB9ARk7_O5agjWa0POCjbrBdqG_8YSG9aLP7az1sy7jt_T8_41zpaOCXPSIZ-0oOzTVvaaJTLZZm1brH47FeuQPDRbIfirAFniCqb1RLcC7dKhmXMsUmmf5sAzCPujYVEJvWfttJMst9XuxcnusThWMK29uw7pY27OT8F0ivzeN6J9nYMC5ZNu9USt1pfA", 
    "Canadian Intergovernmental Conference Secretariat": "https://yiopjq.ph.files.1drv.com/y4mZvEOJreOtAAJY5nSrzxHwUs2QDZpuVmI8y98jstwnzVKX0_O9BTGyeL4mE1f9aRWOu2h3XW9EzDNOywEztLQFE0RuVuJbewnSks4ZMqDTqoG6pFslHKRJIq8_3TUVYM9gbDZ5WIadlnyedYE3YVbcunpb60-JL2iM44__11hQkF3BFCri5lQ0qIoGMf5U-RDsH0qpD8--9Iu7R69x0YhIg", 
    "Canadian International Trade Tribunal": "https://yiopjq.ph.files.1drv.com/y4mdDi6xyGzcEsSgy0g3LAziUTHrqDeRMuH62i8dkd3yl1-Rydi_c6q0V8oaNwT37M4EtBL7WH1AjrpC4ilxdn1tdKNXSRA3mmlakyhWczeGx_kDMHxQf87Afpgl9wbLitsQ6B30utJex7LNY9RzgqZ3Yg7nnWtDIpQyrrhSwAhGW6Q6Ul43j6Epx_YdC7M1_OvrOkE6Tj0-ruvOmL0XxMfrg", 
    "Canadian Judicial Council": "https://yiopjq.ph.files.1drv.com/y4mOhfANvAw5c6XE4__ELwtB2cHU9E97f41SGSwCPSB-_tlArcVppH23aWvL5kbINCNuZcrtmb9v8SxODvVfOjNMC-o1Y9NPgyrzfoGQRcelKcjlUBYhGUDQwmAmvpiOccH-pAE4eKgAri2WGNihysqW6D9yVW3pzR6Mbs5tislrrZR-PRp_-VW3jEPfC2i0SKasU-3yIyK3EpNv-eNDtedPA", 
    "Canadian Museum for Human Rights": "https://yiopjq.ph.files.1drv.com/y4mFDi0xAtvfWKymA2BgXVbJNnDvxjMBUGmwQiqonNUnOy-BYG03adcaDvAsG0UJ1yN59LJ-xqzB0O6uWl72jOwOaLzguJfHAAy9wfNHV1xKluM6oN0QqujvdM3jeXp4B4LA9x7siD88F6kHBMneyp_VC8wUrQZwJgyJN7mx63vKjYeRUZ5udyi8msA2UqiZeOjDfB6uXOfV6bj_QvEbJBo2A", 
    "Canadian Museum of History": "https://yiopjq.ph.files.1drv.com/y4mMMxjY4Pib1Xjbd2A1PhMn8ofx2lkx-ZAXvZLDI_OnyTdtqTHchH09ggESPOKmjn5bykSCRz_8M7YcRVNxpvvYHgHhiPI6Y4VUuSdHsnt15LZYjN5ldMiDuyyEGgZXpwri7GkkIOKLzxjJc8_MYIYg7KSBk0qNEfoSJT745F8xa-prl0Ljhi43jN2YF0AQ5J646i22lEy-PY9_sgumdJQgg", 
    "Canadian Museum of Nature": "https://yiopjq.ph.files.1drv.com/y4mMLobhJCWywhQBHr5vXyBQc5JZAcMeVG6XLTotEXv-gTkcEHYrIv1nPxM_2o49KoICQ1MNGuY0qgxYJiuxBmYxsZAuhWOBabzOtAMFA9bhNWWmH1XrBn_GIwEatweK59CI6rCYehLnXbj0KdxZxYhETKZFjkbRLC9S8UNq_3X8xVsIjCNzjZFbAr1pjutROF60b9bqRsY1ilkyvAkfD7vmg", 
    "Canadian Northern Economic Development Agency": "https://yiopjq.ph.files.1drv.com/y4m6jxf-jljgsrhAvi3S--jCSXKmo2yqbJj3NDz2KMmvtrIRvsz-yWYG0SnmSXonZcOF1XjEU_L9cvzRtkIQUuX3AHNynfi1Q-mQLAF7n3IV2CPEe3_ANtPuPTjXgeX-75MOPtst1GfyBonV3czy095MuqMuJtrMqU9fOYoxPwee217cXYvuzeXgFHGSHMhEdjg0mIAvRBPFIk5_b8CkEK3ag", 
    "Canadian Nuclear Safety Commission": "https://yiopjq.ph.files.1drv.com/y4mZmKaRALS7TRQVTmpCgrpG_mQk3QdUDptn7vJRhRKP8P3A8HD1U6FRivYwZnmRHngChgGMmk-_Y48DumFjfTC4oTmHhqmWNJ4SDJuqHVKAGrEIhyHUOBSBWjbjbrYmegcyiFICOHJ-2hN2O0IkAbJm6JtFNZUXzt1G4pCTDMJ2JTL_qQVIhm-6vhUIRHRyIGk3qzg46R1cPO3TC4ZWK7wPA", 
    "Canadian Radio-television and Telecommunications Commission": "https://yiopjq.ph.files.1drv.com/y4mzZk2vbtjD8zkoB6MT_M4NeK4cOSUgMeKpe2rd22HtR3P0Ws7R0_SJitwcXP9bK14CetT-6GhR1tFNUwHwSbKQKuupaPazqJS9_UdJgCMtNxOZsjmryCvU617oL2ym_tBua9DaQZKupqHhu5pSEQ7tba_701ihMNSPwqaYoRprvprf98NC6c3-yPEzKJk0N_tAifAPo7pDUkWghbo3CvnRg", 
    "Canadian Security Intelligence Service": "https://yiopjq.ph.files.1drv.com/y4mlXfEbUwMIV3clayGr27ZHNsPzcuvMRncGE1xFRWSJcsH_FpJUXvdhl5L6XgDVw5lZt_YZ9h-vB-6HJ4dVlYl00QL7TsvRV92mCI3xHBNhmfGPZ_qeJccRZaUS8GCfDQRjrNvuLoooxv6poR_QOnicm-W6S8mQLhWqCwll7YyCLw8DPUHheNCJ4gXcHxwa_OyPMmWM7jI-_0lIfP6GRrR7w", 
    "Canadian Space Agency": "https://yiopjq.ph.files.1drv.com/y4m1uZrRQvg3twXOu79EEQ7pukZyPuqciiAIIc0Ki3dm11afqhMClD8Sw4Ih0CEa8CnMxS_uY_4NiwLloSn07L22fl8E3qj0Otben6EFNXBqvXw7SRkLbk4C0BX1ojqnPTVrPNOdBJ3luWYL1Vy93EnSU54rVooB2DAgBbb4XAA861_ocz2nMNLCZW78heHT-B3OIfn3owr6SacYdHECUBSNw", 
    "Canadian Tourism Commission": "https://yiopjq.ph.files.1drv.com/y4mES4_vz6ljZ9e58UsZy04TXt_cMx0_iD3_WR4UetVm54IGZXuvSHl4wMPzgLzVlE0eBaEzhd4YhfSfPMJhAhuEdWBbe4JF6gVTB86GDn0VtBrvnEyeUhDa_2TwEo7G_meGeIm0Q_IHMxjRgpwzz30yQzkxVNfqz1faiCdDJdf1CFIgkoVm5CLkzXyBLaXDIkYASId93z913IhF7-Rpv2b4A", 
    "Canadian Transportation Agency": "https://yiopjq.ph.files.1drv.com/y4m6xgf_zQ29U3SvKNs37ZVb8U1W-0ZrkuNwGBGFUKBFtULfhp6xRXxg9b4r8scaQtK69l0ANQifbNEFNXHTcLTsFp5yvsu_1EYAgCvF5dFCMYFlxsJ7hLDeA6ImdJE6GG7Zhz0hp0MhcSzatBgtOXD22eT7Vmi-RsFUjhyULrbzeCzSJi2iETyD9VuhpgVkKQnoULfqaCUEi8syvzanN0rJg", 
    "Civilian Review and Complaints Commission for the RCMP": "https://yiopjq.ph.files.1drv.com/y4m1u9VaVWoTw9_h7Vkueamb7E29zhpomxMXBZshFgrpiRWdAtFpPzqwJjyx4VK0TWlAFyeXMxrVUqnh3URMdBuwi4yydj3iQOqM-nk7j8E5oMGOw4gDKbOdbiHcG5bqvHTABBnS86m7HGHkfvkJegxzpJDWPF7aUplOne8iLg2U_C7iuXW3CJ15yWSfortgN6w3XrG3UGGM6OIroFIad2rrQ", 
    "Communications Security Establishment Canada": "https://yiopjq.ph.files.1drv.com/y4mA78bswa58qRRfPI67b7fIbOXjTy9jYJjhxYik6IdpG5L_W1wkiYsEJSHAyYUJxHLZXHERxMjValCaoN8ZUDhMtR_xh4lHs60bgLrHnn2qQmHXXidw2qPhGPimgBnndP9udVmZm6lKEFIn-laCu55xFBYDbrNYpsO28UcGecgL9sY2OFJZbeVxUeTEm9qMgZxKSW-A4iZc8ROqT7nRJVCZA", 
    "Copyright Board Canada": "https://yiopjq.ph.files.1drv.com/y4mLVTVk-GH3ZYFtX9mZVA1tMh4BkiYa8sRKoZK6-MpkkAxjWPNHEv63TtU5oRgG3rfCTUT5jk87itx4hnpC8B1irwCyZnYYeuQfbt8VZjEa0tvLyal2gpzkbBze6F0gaMoN-PYXKMaPKyrL_tImh3z74RkTM0EN1pkK9ejRhbU1WGJNphv-D1BRzzfM8iv1wd4bU3hL20qOObuzSc5avQcIw", 
    "Correctional Service Canada": "https://yiopjq.ph.files.1drv.com/y4mz7o-BBoCxBLDVdaVq563CFqN3ydifC0iY_Jaw30udkMsdbopWJOobGSaJEkW-L9EiP1cL_3TzZSY9GLa-7-V_7I-PabF8m5Ik0TGKnNbFYIIqaZfms6neQ5cf2Os8l7zs2NuifO7Mke7isBqg6xG_ZlLMYlpjwOlWOaCqNbNPtCuEwc6Gef1CL_oCw2FXb5w_yQU4LzgHqMCWyhxOyZGPg", 
    "Court Martial Appeal Court of Canada": "https://yiopjq.ph.files.1drv.com/y4mCQlluRtjAuIAm8_JBVb8Hp_Yyserjqzyc_zKf_5m3qXqOf0W61sEcSEkPmVjb2STmQLfgYJbxqJ3iDv7iLGg9xJrZi_7E_WY0ah8odEXnMJ4PfUhfBE2yt7DXMb12zs-83evadnm949kVUUzY4M_tLmWurfUKhGfkJNUiiRCyz-1gZjOIIRSbSHtXlKSvXu6qo24Sf2qy6GSCoHktVorgg", 
    "Courts Administration Service": "https://yiopjq.ph.files.1drv.com/y4m3fq4leSGRd07FB1gulp1J0UMgWbS7_BLprN-HH6eM3U1skhXVx-KePjjUCmwb1o_MKTVyjS4xL61akvJevUccF3R9JjY1z7HG25ZLEePJ1Legra6IEOQFDcjOH9LLrQ7bzMPZfwFw4OqedYFTOKOqcuBIIqlzigNO8q_xAwsbkbojidrxO2wYfZTvak9qK8xdU5_avXADgTgHF9i6Y1UNA", 
    "Crown-Indigenous Relations and Northern Affairs Canada": "https://yiopjq.ph.files.1drv.com/y4mCT3xLLdTwS-nrBqyikQbz92o2C176Tw8j9hFdXqZiaCMe3iVLS70z48w9Vj5H5NpQPoyQO2iJY2fMnH91EuYcwOXSSquIdSNjcaO1pAAQKmZw1uUX0RdjSWih65JxqAHM5erD0xL-oVEe3xqkZIgLsbZF2VHJBTdMj5BV96vyJLOs6pnf5e_jAs5DDSrw5gvueMpeyLRV62PcJ6XYK_cOw", 
    "Defence Construction Canada": "https://yiopjq.ph.files.1drv.com/y4mdwXdAfl0fp-aEHnero3Y3qBJMyJeR1YG-GiSCxuawjyESU3VwRpE-3SQZrQYOAH1qCGOM6LL_GGvj5CkuFz0OXRJF6CvYExqn8Z-t6374dRJcTgVQwMCm4JLpOHu_6zIEVCvcn0cjXfDm1ec2EzUiZjmhDOKEP5BG6ONjnJdXGTyWZzfrSkE1319Gz6e-sI4kbZN9N_aINx1ddX-lmrttg", 
    "Deputy Prime Minister and Minister of Finance": "https://yiopjq.ph.files.1drv.com/y4mgGeKw8Hw3wGCSKdflt0fc3e0aa2ri4f_Yfd8uRuMIFqSQ2Z7yIepYpc3lA6HINFsiEyhH_JiVr5ZYmaoJYIfFuLf5QKNrlnIoySuBIGaTasCVTguCnXzGMg0c-g1pzJfHMtniPLSMmyE-0s6ia2QUOuF5FG6WtmwQfR72WhpF_oBGy6s16nn7pPIxxGFrIbT86ghjDqpLO1PO6VfPvbkrg", 
    "Employment and Social Development Canada": "https://yiopjq.ph.files.1drv.com/y4mHfuqqwZI9yyyYBBws8KArsLTm5NuuNwkUrLH0fxfEtKgbHHwZxk6CbjVu_fkxYSiBzsuQ_ZRUR0k9H9Ocl6cKN2kqmVW5_Lkz9r2Gin6FdFy1IZ73UQzcr4xO-Gdn5e-Dw7xh_riSKxsKcRRnhQTlF9C6Kf-yS3Pa3gNN0qz_cKLU6JDfGYBShgbjUOLYiAeuE60o80ljhW3L4qLtyh-6g", 
    "Environment and Climate Change Canada": "https://yiopjq.ph.files.1drv.com/y4mPhUpAJoDGS6KQ2dcBg2AdGS26VVPgDsSY8BDeuAPA8MTU7dEdnzUXJa9dEs1uFxYxNEfSAcTk-2cvkfPXT-l3_W8nx7rHIodSNhcn7sCTy35hebZj0rrQTvdap0uLdlp8bUWJhatLHa0GD6VEIpD2VLlu7V6J9HZessyfsmQ1fYdEnBl2Ehfay2AQr3SqtClWAPfdp_HvtB3mheXuUKwBQ", 
    "Farm Products Council of Canada": "https://yiopjq.ph.files.1drv.com/y4mmT2K4jmnVuS00CTGct0WPdYMKG95J97qMbrKSaPCrGYNeSbziSV81rGg0I-h-fc8J45Jxa7owEYJlZqYqDoRkPCBb6GNkRXzk51YUTE3jPXcBG1VnW71bEWQj_Ur0neEUJHY7nZ9wiP8D3aSG0UCnPWWgDAXi4S-7xbMyCjthIIWay2NYS6gB4Lqf9xwC_qmE3cn5lwB-fEuXiEL3V2VBg", 
    "Federal Court of Appeal": "https://yiopjq.ph.files.1drv.com/y4mLhoNVYRDMwsNvnjCK295UlyMDTJLbKu_fOgFFmQYb9mGwSAM5eTQQoQhRHLFR-o-NAj8THDcJR_BEFlbdPHds3qv8VkOHG6MmHfatKStyXCedQSxaUF4T6PqgHsbZ6eL4-cxPx9meAkCxbUaYVyCnUbPNUW9UmonwdEgFhM8IqAkYM2LMYS67KTrFt13HLyu9e_l_badOvG2YjKhGXw0KQ", 
    "Federal Court": "https://yiopjq.ph.files.1drv.com/y4m-1oGUoCu_qrWDss1EkVGo7Cc4IUneqXCkxLiM9J1PWKMwphyR1gmHJQCBzemLi7KVTyG7Rl51wudymvO4TaWur02v5xpzXcgr63e3-v_8CGeEvL2Ym7SpM6j7N-I8y2j0e-ezcO3US3PS2MnfuXOg4FesyMGtEMomlH-oyYhNLNasbpg8U8d399AYI22Dxtsh-HCGCpbxDoZ2eD5LZMURw", 
    "Federal Economic Development Agency for Northern Ontario": "https://yiopjq.ph.files.1drv.com/y4mBHV_abULkBL7FQrJKL-LJHKhUpMAz0w-MGzd0NsVqw7VdOuAqxePgVAW8PUQCPjKpVkzZMaSS-kBzLoQkFhc3ef2yPaMNDOE_69sNLrdSAe2mF3hvKRt7nG8BLROFDnoUl3ex7DLxaRD4gWNWzKkJiSaPddhSN48FFu3ClyV1sDUz_fR9FobeI8YISadAIiVut8CpI_RiPbidNBQL9zmYA", 
    "Federal Economic Development Agency for Southern Ontario": "https://yiopjq.ph.files.1drv.com/y4me9NeAT9kLUZWuvXGb2Wex2Qo0bBLHf_D7AFm4R0WuLkbPf2EpdmZ6cmklV2PWNjuTHJn26J_aby7Tq3gaPTUcojhqyhyowGqS8wbAv2ReEokGMY_fSJzD5zPSrWZ4xpkippjO6EquVR_lXxtepe_mKyv3VQ0f8yZ3lxYekLo8O42M-PPZMgh6Kf3tlmaMe_q8v9x5ZbavqM-m9bgyiCxuA", 
    "Federal Public Sector Labour Relations and Employment Board": "https://yiopjq.ph.files.1drv.com/y4mWFhsOiZuV5C7zzL_-69NJRKDuxZ4bqrlJ8nxDrtUF990bojAtUYjl8-wSTx-1c510xyGXe9NoXnkR0povuXlMsWdg5EwzfRf2u03lANfpU2PSiVdoInjTljGorQ2fMayCwVLszQtfzWhn-BRTvt1eMhJ-x-dtVezX0o79hI3XLPLtCddzdroTaQHXZ6ypK935oBPtl64m6d6R40YmNnPtQ", 
    "Finance Canada": "https://yiopjq.ph.files.1drv.com/y4mqxnyQmJ1mQgtrzupw912X5muAb-MvcWDLm6r-FCOZ5-9_ZgWE_tejCd83b_YdmiovPd3RQAMySQtPorh8igN0ZwBq_Bcjx_usWEbLWrUODBsemR6zHEC84ylEveSXdT6SVhzPLQIVGkR00mfdhm9zGy4G4iYDv5p_epz3vC39pFKYv-1dup-wI0sxJOd7EdzuLkahwahtwbAOlkdDD565A", 
    "Financial Consumer Agency of Canada": "https://yiopjq.ph.files.1drv.com/y4mRoDdyDr5mDVKLw8pzVBHrqDwYiKnGPQvSsfA79qVHEPP_-2MzqF1spRW05pvXOPRRBswCjxY_Dyds137UHhQRXIWMcNt7qCMfrL30ApcXPEo74o-U2hqirKEqO98YGEDcLDzBapRONLOHq5FEiufd1G9vFoRYsaROR92QUvODx83VsrciI5_TmpceSeMwA0ttvxLpYaNtnBaale8wVG5gA", 
    "Financial Transactions and Reports Analysis Centre of Canada": "https://yiopjq.ph.files.1drv.com/y4m2I8A3yWQdST1z-JjpJ5jooxb-2OtmOxY9HoYANREWgwH6gdof_HsEbtZ3lx34ZWKnd286o_LLXcOL6fi323pbzTJsqvHbWjKeNDEFU6GQ_v5Hh9DIohqCIDmjNgHxsEE2zulwLvGyU9Jy-g4eIoV6VhyQGAgKOu3dhFhKc05yGha1jhEltWA9sNPHPm3JqBd9bDEnIcwxzO84HsU0cBcJQ", 
    "Fisheries and Oceans Canada": "https://yiopjq.ph.files.1drv.com/y4m1ez0HxGyKzGhxeIhH7ZCTzx_uUJ_FEkpr8PWWrf5sW74r4KIt_WaGgOJoHboGgE06jsZN9SLP5ElEU-Xrm4Sv8aBxPynuKPHWFpa0BYpYl3iUWIHVK6MlA459vmDwGcQsmzqWHoUVZVxGS36hp1oeGT1X88UNPwCMrkxXIn85ydby4ZXwwx3qq4b9kYkxsHvMM2p3M7FuFT8qLER_LQXdQ", 
    "Global Affairs Canada": "https://yiopjq.ph.files.1drv.com/y4mCqCvUpW2IG9np8AWV6vrMI9hv_mRO7llEuvKvTMzMeyOqevVvzVK7G5uU5AxBEWLE0duHWXgu9uuc-5UzgLzCGSWo6nootJWYImsGmY22kdhS_nm1G3kvQIgCYy0KdP4lF1X_KmAQr5IMyQ9qzyrsLYGprp5aaSBPiFngULMmYUUiZHpIgQfKwkzxc54uk_-7LF3TpFfejq0b62DPwd86A", 
    "Governor General": "https://yiopjq.ph.files.1drv.com/y4m2rYfGJmIt9mt_v3A_Y1l4h0dJiNXiYvH1sKCq5F6nqQjMZeGn1Snuv2YxE5qemPE2CwL_IEL4c6VOxaPN2Xp4a0NOboOxglfA6xqvAZOlhfx2jiR72HkshAue_8AELvyUqngb9azuHAkjyB4u1WxGEds2oraLbvlre_YUTVaM5LikjWpLXNh5cLEHQR2aAIVG1mOKvwQGjUHOnR2ocKuYg", 
    "Health Canada": "https://yiopjq.ph.files.1drv.com/y4m6XLeBGARX_70EIJzR6QtClgXu8yXg-5_-YHdGa8BSHThtBkTWvNjd5i7NhmbS2tHA2eHjoNqeQRYR1BLR_HJLYN7MmBLRwky9lRm_f6BhZ84UbUz2pTCUh2hR2Mh3w3c3GKj2c4p2qYlMjBv0GdZ9M3dmbvWBQRxGi_-zxz-Y1OM1wB_sylDXZojxjldPZeq8h23kuGYELO-K_y_9u0JwA", 
    "House of Commons": "https://yiopjq.ph.files.1drv.com/y4mvpQDtZAFR8GGT-jK5lMQO3vHVrtlRS-YZEeyku_Ovrs47hzIYR1c3xPiwOjrNpze13EepUqXrtIW3Ha1pe9am8Z_a-qX0EgCovHj3qhuHwb0G_yzUPvRD_5f1yjbwI9N8LQTotnrzG2S0zCbY-AfSx0EDntBJu4z0aTe9KPexDLhtqyk6EZzAmSLBygCKLJJVN6kbuS3sYrKuhsA5hrGFQ", 
    "Immigration and Refugee Board of Canada": "https://yiopjq.ph.files.1drv.com/y4mR3du7jElP_t6V2qW21rm8V0gdPL6tMD1fLY--qSW6QnkkjZBLua6BVEBm4igGxz9rJoSeFR7D7_-Zh4qynPI_TGsL2SZdLVQbtptUqL6ndiKYfmkaJOkIurFLcJUEkSxzrsxSwPSYFohoFoS-su4OhVVI8suIgYKmEbV7k_Vtyb2yYsK3vmskcxz38QOxObzM-G__z0OPhxzauYq-wSiqg", 
    "Immigration, Refugees and Citizenship Canada": "https://yiopjq.ph.files.1drv.com/y4mNrHOfGdqfF5W5UUclO-9pb2USdTE9LPuRn-Dl8OaHEo_CsIaQ8-ajU2XrS_LYJ-JJzbHkEhZPm6r7I_VXXSKyvzjiiIz0hFDL2EAHjmt8YahX-TOhvrCHfVf6At1BM1yaDPFerfGlNL0P0HND3uTU0Epd6vam5lr8Jkgtvc3U7Q3FY9G9-r9dH8dTfQvjIXVYWDi0CoCky5Bp4SVxZAlyA", 
    "Impact Assessment Agency of Canada": "https://yiopjq.ph.files.1drv.com/y4mTVOr2ZcVTNRXkCZh9354MRRa-NPnwMNrl5ohu8mqnv0ghvgGdW0dAhdARqZRseKKfxcCWatY6AcnSzo5XvMI3qUT-wgxL6RRYONY8zz5ehdxOPiCH3VXHD6pKQmFmvyshetu0jOsHiCXaYYixi1wkPEhULoKpWWZRUGg5sTovytBo5HcaeX_RPBf2R-QXvPSvW8ZZ3wcuvDGcjzYvAOK9g", 
    "Indigenous Services Canada": "https://yiopjq.ph.files.1drv.com/y4mnA9OEqG3S112KX5fln9jUV0m3xOP9fvloZQupUh9odWTPjCTZ9sX2E70MVfsTRfdtPsKBQd7wLY23_Dssf21IOqNRefqP0LGVXmvw1QSrNgN7liuhU0470JFw8IYiQJESokryHJJb8W1IvnHZMQk5ouIp6u0xVjZzudHWKHsQc8TS4tzpUSpGuE9WXrCf8Lj6lKtI28QPO-JK9oGj0mrLg", 
    "Infrastructure Canada": "https://yiopjq.ph.files.1drv.com/y4mZrZlqX80eHazWY60t_PDvNo6xuJy70V3pks2URtpxbihCO4fOr9GYkkx6d5VC7uVeLRDA6XxNIuJ40fcJhy5smEYLtQtv3NZvbrSIyrurgY1OXdDmwGHiY9eNV2ePf93Wf8jW2WBK6fff1k1iLbtBDq4sPdJz8T_e7G99iyyskNNG1dQie6MY78aX1grC34VIskE1sfkXsqdEJiqlXK4ng", 
    "Ingenium": "https://yiopjq.ph.files.1drv.com/y4mAew8rEeZ8yna3TN0tAVDuYKXKSbinN0Uo-oS9dNxLc_2u7Qwjp5ryRZsxfbdvQbkyNrLF1NUA82_UJVyhg9zbt7weooOOWL45mM7iWj205f4t5NyOytD6flKv50WnM1p1NoLttv_PzkGgQbLjuGm-zcIUbHG2MbveSHODCMDoxaa73qxgz5aAqIItoiw0TBCfzj24grF2I9cLRLyWhVE2A", 
    "Innovation, Science and Economic Development Canada": "https://yiopjq.ph.files.1drv.com/y4m2D-Lv8LjZEv_Ufi0yageQxJG2SHlk_2nvk-ezojw3yLTkfiyBMjFpzLVnW-Vd0lIf7MSNLKxX_eATK1ENAD4kKf532va9f8NiAcYxzxq_00zPrLc-3kGD2NbVlacaXHjkddqAyUfXQiBelZSqIqoXOiGIm8zbpDwFz5zh37rwcEOH0LjvdQ9cj2b0PRg0tH_XWr7ls5jvFYtFCAagMy9Kw", 
    "International Development Research Centre": "https://yiopjq.ph.files.1drv.com/y4mj-tTjWcy8fsE2oeF4mT6pjuVZW33w1dNuFAPDEmiFSGkphF7FJIag9R1kldqZq0k6hd_ihD0VpUSgckXQS_13iW_54-5etYevr9HhB4p5P2WAIzHnvfjHodDKY0eSh4Zrj5EYBja9r_JWYC9GmdhnmRFjXbknJdF1RE7YD7yDaK6yK-34kaMfzQ7LICWWLeZ0ug82sl3VAwP_WouJUf12Q", 
    "International Joint Commission": "https://yiopjq.ph.files.1drv.com/y4mIQgRHZIOIMOYhNYfYlQKOKHjIpXIbRah9rLrwcki9uAjP8ODpBxLbNU668Ykx1kWDAlHWZv5NlmwBjuawlUBbj1z-T3cpedc9DmH1pYcqjjCJuU4nnTL5XuB0N6HVinuGcmYqUmJEkhrnvKiVpgqPwLkepY6GJh80oyqBQupmv2HS09wzmFHjDV7NeugsOsrSRpHOh1POopthU1L9UJB6g", 
    "Justice Canada": "https://yiopjq.ph.files.1drv.com/y4mVrDHaYQU-vWgU4lBnIBXlXTSI6FZBNf8T2KJ_q4PWuXnzmNszPtxNkZl5WKj960ImovQeSUQRmOsNpqsf7W3Tmvbps6UaVMUfTvwWvzweCqtZ4mdMFTXgkjcagcsx1q9UVWXpjBkOAK5TRyoWSGXGDv_WP2kj8LYveTuMvi0a6bRW5PnK4ju4dxjRaNwnR_Fv2subPnDjO6kOSX88x8s2Q", 
    "King's Privy Council for Canada and Emergency Preparedness": "https://yiopjq.ph.files.1drv.com/y4mpjCQ7td6IF1-K1QThweHfdpGRQX26mplbRJw9LFFsNV2YSEBHZWOOycpzw4IXNFDKyIiS1b3yQkdRwbdU64qQbpUPrltUfbYMhuHUk7-4cb2GZkkWl9HBFUaSYN6W2oOCp-tNiaQod8Vray9kmq_r6RBsSR1hMINPFmizKjBX_LFWhM6BZG0VVSRwGxeouBq_N50TvhxGHMO1p_EwJy6hA", 
    "Laurentian Pilotage Authority Canada": "https://yiopjq.ph.files.1drv.com/y4mqy2Vcs7XuGpsBJbgy_peb_dFBVOdUN-KqBj6-xhxVYXbk9cOx0bhbHbM05bgBr-6YdS7Dy1bCyonDzqhJphBic941yEaHixgJ_I29koS0ueVM7MlImiq1CCCAUgJBAuEiFNK_RMwDaaKZpcyDbyK4YjUfViMVPTWkcpHEfKFrsH9LxfkL-0NVKV07WjHjoCJUkZBSixSTbggkVzLykkeKA", 
    "Library and Archives Canada": "https://yiopjq.ph.files.1drv.com/y4mBun0Hip8jPH5-37_3yn-l_T6I1zyLuuj2fjuMhlAdsT6rBGqjn9iXpX3hZuR6DgMoiNBw3kes5F9B4N-dnM-5LZ42DJ0gixq26Y_zCt1uYnJeVoEFTAmN1D9bnLQs0swRLhflXWJ3D1VLi8V9sV3q2C8xbWvP9_4uG2fO0ONh49KyBFPsZ7YSCgMl_1JEEl8_HEd8bqx2PhlOmrMiQcmcw", 
    "Library of Parliament": "https://yiopjq.ph.files.1drv.com/y4miQlxehSUf8JIyKKUJd6-JnWeBO82hh-0oKGdVd7g8dJKZtlYqnjKev5wD35fFb4XWjJiGLO50pdR9YprGilOj_DMbvBnuUTlQ31M5wXvWZpxHzQGC2oYvrGqTcamvmb_sKRx-WJAR14ZPbLXmv9Nii7PGx0iM9PBoay81S0XqGwXf-OBdQNAu6Mi5EMGEd6CSETDj3KgJUxqjhGggw4aDw", 
    "Military Grievances External Review Committee": "https://yiopjq.ph.files.1drv.com/y4mEF_vHVqD1G3b-FdukEGDMGyoxBgmap0d8DOZOvKFqrsTB46-YUpJndqDfs8TigETN0BBevRLZv7g_BvRilzEsExstq0u3dcQVvJTYmK74Bm8uZzGXx1QxzSSI73b3LEyHOhQd8Yc5OXQRJ3_nk7TABLXpPLNCCWcRcWjazq38o-OPncuSgd78bOnYYL_Yp5PNrbBYO1XjKR4lB9b9AB3Ag", 
    "Military Police Complaints Commission of Canada": "https://yiopjq.ph.files.1drv.com/y4mhheA3gKHKvc4hXbs7hzt3YXot0pCxQyTxoRDaNdcTxf7uUjZcSR9kxQNu6edFNrtxXlfs3e5nXr2iprG-bQkG6F8T0ZTyvJggvvkWNir-nRY4fTvTlbgQpAwtu4NfHVD-EqWEOp34CY0LI4NT606abyt60fADGjpsjK5JikZKhN0iSeulad2DzKwuJMBLC2VLVayrfxZjPyDBJXCIm86Sg", 
    "National Arts Centre": "https://yiopjq.ph.files.1drv.com/y4mjoDqHBOZ4jfiC69Lh4oBYbt7a6JZtPoSRzxJEBns7wuXlaor6joSIW5VLUF-YmNx-USYSXz8lMxko2OWgmagq4gmmsL47WAj2zfXyqVLCqWl0VqezXlFxK4ERYSxbsLIEx6Nz3rgUUi9taYwJt0PkQcxN5Tx_jAomah5422dK2kmTLXTPVvXbk_8Hd4tC_PTwLW7qYYQmJP5OMwT2Oww1Q", 
    "National Capital Commission": "https://yiopjq.ph.files.1drv.com/y4m0Kv_FGaY4qlEvNW_352pL-GxD2rU9NzwWs8w6e7dUPg7F5Z9hBvbZOirZgX3daipixHUJVBGB8dJIiJl-qsjAv2kL3yq34E6fwx-0ENKHrUEhz0UVrH7J7FdSLoJnLdkrx2n914pWLuwMtRQI5cuNWbmnLjbHjMdTLzRmZLiwLF0NHr2r_d9IXUXmLCz5KU7qYPhaR3SjnCWOSSfPX5RWg", 
    "National Defence": "https://yiopjq.ph.files.1drv.com/y4m5GgV7oF2pm4y02r61UCLWJni6dccBSFqE3gaUZNs8cyaTR5HqrECknRSQU7QLm5vJGryyqWoiFsgBKaulV6n5WvRcC96OHGiVLmsxS1F65SwUIHs38L6p6kZw_uDv3lnKKkUkccnZyEvJH4WSzAYvllt53ONMeAAiAo434OVzpCDeIWlN1Jmy8iZrUQcVv9fVi-7CQBZSxjrePotoeXgOw", 
    "National Film Board of Canada": "https://yiopjq.ph.files.1drv.com/y4m-GdzZIaAsvGOCb_sZYbYgF5fYZggcY5CZ_7OIlsqAdRKBKC8qbNU5tu4GqFFGZ0cvPte-XO-u6M-dKbU6PUGsc4ZGFKqWXs5dhI4srfAAR6A-l3otZg-fvk0EXvSgLkugkYx7vbTLOzO5YOWZ8sRgn1aJ7pYvdmcGfS-KLDWOx_IJLL_09xic1mvmUM2Op0NIFQ6N8t_g0laXhRMVksyUw", 
    "National Research Council Canada": "https://yiopjq.ph.files.1drv.com/y4mJIe8-CUSlDsrCTyr_fmhBPAIuV8eTnERBgUWvQTww6mWme7wTw8K5oAcjJUeR9dsUMDf_funQnwnvIMcNav5e8s7PRdtN7azQWs_w9lS7nxz5Wl0SowtRZvvdF4EfHB3cuTfbUXFPqdbypKtGo92K_mr0373MXJxoOZxvzpp2S8PByBAoiUvpu0XKGSz4OAf9dlcR69ZRPGBsusV4pfRrA", 
    "Natural Resources Canada": "https://yiopjq.ph.files.1drv.com/y4m2KLOFrRkfSGPhFOKp4-nHHJhX2MMJibG7QHvwFyYD7jEbguJwrQvvw8co3opEajY33R6vD2-p89t8pm_imo3qiHAHwkSGpodWuNKlwe8JVyiRg2IzIZQWtLlpzpo-O1BedbeXQj2K5EdwXHh7BNyveOg5GdZedxuQrAJz-hXORDZ91c0PMUAa6p9bYfEcm5gdEcTt7MrO4tmeEIzrIR-Eg", 
    "Natural Sciences and Engineering Research Council of Canada": "https://yiopjq.ph.files.1drv.com/y4m99NJwWIEaSChn4q0Scd7qAg0gpbjiEqlOD9r7Or1gQpcqPnS2pkAArK08DL2XGgoWcpeFDRdfCBaSVHBCljRH0KxRVD9FSrNh2tBhUpotXft_3flDqIEV4jP3GyaXMM1wx42iz_VCk071t2Z4z8mLRw5Y7SJLipSVLYwx1JiGQuLtDKH1pmC4ZkI2pMEFg6iDwcpLYGh2v6mbLTRZaQBWQ", 
    "Northern Pipeline Agency": "https://yiopjq.ph.files.1drv.com/y4mYmkhRneoA1-iPHJvNMSgaOiS9XYNuGL5LKN8yHOQF0w0Z8LCtFcPwq5HaYLACWRGWBgU-spkxxU4xyQtEHwU2G4NH3ZX9ydftjYcX0x98C8QRF9yqf76uhConTRDkxblv_yvX30geB5n1qeVF_2J9eFnbKqYh-5j9Z42E05qdcxNMmgikY7NE72Zqh-adxz6FY-SSeYpiRQXD8-YzQWx_w", 
    "Office of the Auditor General of Canada": "https://yiopjq.ph.files.1drv.com/y4mRdO6oaqYMjysIqMECdvys7OZToBXv054-teui_XcevPymdXx_NPfijPY8FU5SLDq2TFjO7ENDm1XNejChCI4XEYWT9NT33O0c3weBb82fmoZ77JPDJxYgsDRGtad0XtrXguZWvFg43LPc7Bw7DhfH3YCdxNSMw7_hBQwHsdU2Q9Y0aXzaC8eVEoqqSAvVEPLSQNsDaWlpJk4M574mFnNgw", 
    "Office of the Chief Electoral Officer": "https://yiopjq.ph.files.1drv.com/y4mdchwmAdq7zCodXAV_LosWQPWKAFj7QisDLj30YXXATIORc0fj0s6qQw_rvHI6pE8HWkretjfC4dmRmPIVpbdqkms5Cu4ZtdxF-WCmk2zofPrjY2g9OnQK5NnMH-BWxOT4Mo9IFoAFLqUZXZSw-OTEtABuisKSzKURKjd380nBKbwXfhcaoB0LRHGfVVYTyc8zDLPJBKyjQLtOX37i5ikbA", 
    "Office of the Commissioner for Federal Judicial Affairs Canada": "https://yiopjq.ph.files.1drv.com/y4msjUh9gxw8qbwm0AcMHvk7Ea9gKL8tSRQMuOFoDyIyvoZOGR-7K2sDDX25SEi5kz6aJo_Hou4er7LDyxMMn-EmkwYY0zs2AzyrFEtLsVWl5EtsAW1-zqo60ARZ-4nY5kIjXH3in7_BIvHHVOWE1xdv5pSg4tWrG_eOkQ0BJkBTUgk1YFaJOe60DzlyZIYNcITuDDpNPJChaxt4F-d_icsEQ", 
    "Office of the Commissioner of Lobbying of Canada": "https://yiopjq.ph.files.1drv.com/y4mG36_J2lrdqLpXUoUxXB8O7MpYAAZCGvfBaYj_DZHsHE67Iof93mykTzwIQ7TfQMEZxVtwHHjJzJ5VyqQtNPHvL23SYJh_H3H8aJjGbtPP0EaoWD4GZ-rLT1Rw0icRx6fp0wb5F7ePiJ13k4LZAn8l8Ig9-oL9qbQPLyQn0YOOq2oTKj11Fwe6UKbF_qruUtix84cDjnpoB3WBVdDjrGCHw", 
    "Office of the Commissioner of Official Languages": "https://yiopjq.ph.files.1drv.com/y4mSRGmL-nHdORSq5AcG84jS1YxET-rju5d_l-gFXQ2dSqMVgpli6Zh835SsUtx_N5OmpKGQTav4hg1hCwYdiIhdJvL7HxXFamY2w_7d36ZJZPTR320sUCHjCX4dl9C2JD4BniPeWpe_Cw8-vYKJC-y3MZCKgwy9D_S3B-dDW8r1_dLwVNPBqeE1loYDS7qBh8yOWBusftOphXKuyhan8rU_Q", 
    "Office of the Conflict of Interest and Ethics Commissioner": "https://yiopjq.ph.files.1drv.com/y4mhL5SnZYsI9m9U69yMbYR7gGd8MD--HEWXLmpXdc69ifL-u0buJMJ9Rr10ru8RB87uC7o2gHviSskuVOAJSWYRaaJvtfMhX3mWVOSFzvRj8N31fxIB9IM7wfgbvzbQG0_hewJ83GzTs21NTWQsK5DL0JnBTCmujTkRI5y8kTyS4ubJKESRIqgnvftc7ryIMjwEd0iYRqqBFCFB56Ov6eeww", 
    "Office of the Correctional Investigator Canada": "https://yiopjq.ph.files.1drv.com/y4m0iGm3pjUnPR8g8IekOhanTWpkKLVigPlMjiECv6Mx0TRY28NkASgAXNGhNuuMHq80HPohOCuTCFWmTWLoSFiAFxB5NzwMGWt1gE9NpgOsnEv_Cd3JYqqcFtAPd8O6tTgi6eX18nr63vYtHGaUtnhSkneukzw4BO5YbkqbSIm7BDHftT7LpPcr3LO0EGFTTfQepQhE3ZB1IJtk-J6xTUd2Q", 
    "Office of the Information Commissioner of Canada": "https://yiopjq.ph.files.1drv.com/y4mp-s5IWCPLp5NBTPZHOiVdCyUMcz43xqUnLJM0otTBnHSVEKuM0fgjsyWbAwwQO01ubPxm-zPboo3IPmoCuV5kl8SqfI56ElsbWiAWKNMUbDWdFIQOfoQhiFNOmTx_5MKAgnT8bTFO6KUEsttYy1_U1UsGBoIRpW8uJa8xbKVIxUac26TgO-2l7GhT0-T-PbzbaWFsYhhVZcrKroMRZ6OWw", 
    "Office of the Intelligence Commissioner": "https://yiopjq.ph.files.1drv.com/y4mAm2SJLHozIYjlcTDT4c4EaDI257E3ojNBDpLQLwRpnbyp-leLvqOFuuUCbxhpiZG48arwIVNnGg2SBhhcj-5VsGTBl-q7aPepLdTXSkJL34LCPK1aBAqIx9idzrn0eXbhunfW7X5tVYBj86jjJ5ufRdiELbAebHJDZsXWEby1VSNcEvpObrWBryfv2an7uRoG0POXgGxL5dbblBscEu2hQ", 
    "Office of the Leader of the Government in the House of Commons": "https://yiopjq.ph.files.1drv.com/y4mp4BhG5Ksg_5YtCthlPhJ6QfDK4H6pouMmPjiK6F2Lti74iXoNo9QFKGyaTgCIVW7rsV8w_-CkeokgTghZeJ23r-jODgjdL2lZcrZrYz7JyqyUvFPS7O50dUHB0dyG7LlJ2Em81Z9oZSAQvC6wHKHS23PXjcBvPvcAUApPu8fLHlVwms3nnlVSfIsSdoZFx0LZ4qTqJohtW_cO5TKEIIp8A", 
    "Office of the Minister of Intergovernmental Affairs": "https://yiopjq.ph.files.1drv.com/y4m6rMrmcNZvTHklYzhhw8r5wr9HOTfvSy6P4t7udJN0t1r1QPXOyN_3ZknvkJZVPAbSqkBjQ8buVxDpAZBNe3PGAQZEgFkS6xDWVm3kfw2gzlT79iF83GX4N4JI96J4Gvperc7j6pbUczFgR4NoJRWtzgDAkgFiuKDX8cz0aT9nJSQgHhrx9s3vFxrdHm42fCjKj1AfAxEqAiFv4M1X1Wz0A", 
    "Office of the Privacy Commissioner of Canada": "https://yiopjq.ph.files.1drv.com/y4mF7df8c9IYn6hutIl6LIdgV5U9Mrmc_4xPAhHBDgoGbrfvttbqQNFy7H1OTLLep8smIWAJpJFw8ofWAKdCXCQQitW3au9HW9_n2aKacHImVDq6dSJzZV4cgY80SAZDkwXACLmvRKWyL7b0SYv7eybBrueTxwWUdjQw9uy9YdsFEgmD6wMhEi1QuKvXniV7eX6yzeMB4q1hJ2skHGqWJkbbg", 
    "Office of the Procurement Ombudsman": "https://yiopjq.ph.files.1drv.com/y4mhmYYm3jQFmb9hTlJCFd4dlhiSBTYknp1CfOxHMmFbtDYNsy3kIdBv0xim_JsV6sfQ0JWhXAJ6f2GZptEGQpLX_QzlGdd0d2U72p98Z_WKp8gFsrA_iPtXydYzFKeiYhuPDcw20tvHVUGaLZK9-Y1ISYXYwSKp5wqMPav31hNCaXzWpYGSQUTibsA6a09TtgA9MtbUNRiAzcJ8EVauhpcaQ", 
    "Office of the Public Sector Integrity Commissioner of Canada": "https://yiopjq.ph.files.1drv.com/y4ma9WlmB6g10cKx-xTveom2B-bYnJimWXmNnWLa4EjzyHPGPMdykR1NwVnR-aOkLRiE7E_8xM16A2rVRq7UQ0BWwjwiMjkTSYJffwIpF3C-yBaZxK0ivUVCR-aC-GaaBYJfsgNojbEDLLjROi2AWB9hctsVQ-KUG7wVu36ZiRpVNvjhNg0__g_iTc23BLXvD25NUORskeB9hvgzK8SO9rw7w", 
    "Office of the Qu\u00e9bec Lieutenant": "https://yiopjq.ph.files.1drv.com/y4myFRhWLJ7TOam9Q7m0A4Iz7NPK1fiNeMUXRn_kVzbomBiWFGF28Fu9uO7-_LulswGLxiZxK3A037nErhEagwscZjQf1zZXEpewjk8_M7NFSbu2g-NjCp-2ncXz-jdD2z-qamOCDSK8-ZuNA-b3E546SG0rOGLGKASCi33G8kGEBcEtVX1YvMzNuE6p6MMDSO0e8iIT_QHixrN0P1Iz5dHXw", 
    "Office of the Secretary to the Governor General": "https://yiopjq.ph.files.1drv.com/y4mppGCtO3qxGCG6T9APWwAdi9HGRHXuIeXbx84tt-hW-_Sb_JjUjfxIEm7evLdINwrHmyL_SKbBrf-z-acDGH33SUER6sEjfOLFALw4qMkarxotWL3ub9vWmBsJVWPHRDYIQiBFmJNNcR3reztF8QH7OULqIF3YYXFh97i1G_OYFVLBxhl-rbzGrRzDMZyg_7LQSB8WQVx8olKaxJ66D4oPg", 
    "Office of the Senate Ethics Officer": "https://yiopjq.ph.files.1drv.com/y4mj4PjpPDFo7-57Meb0rnEgscXm4yBbmIJxPAqJsnRGkdg-9fdQ8eMmX_rBgMWYN5RSb5G3QaGiYUxYQ6A_uLwZCG0iwmVP9UJu8YKsbhoLxrP-7sl8BTzs_cffxDGm-mHyTuqxYk0D36Oc69sBUspPX-QBGFMRt6aqvlq7gf0nbQHletKgWtnT7ot6MDhKQaj32cciLTGMAs5Vn0DGuKoyA", 
    "Office of the Superintendent of Financial Institutions Canada": "https://yiopjq.ph.files.1drv.com/y4m1ksVSwG76SJg8kGkIf8PMt6AOX6rAGQTMt_s2HyXboWHCyXIyTS51-caDUotMOvEkCOzukUtURhVyeOJAO4bIxLtt0ByRjJGD6H6VTLUetVCVpD81Tv0LLaJ-QqUOJCn4FL-3zE-tyRsvqB7JPVQRjyaHtgRUcv4cCLyeJC3TUb2rDSx1HB--im3ddY91b1lL7z627c5tURnneV_Kxr6Aw", 
    "OFFICE OF THE TAXPAYERS' OMBUDSPERSON": "https://yiopjq.ph.files.1drv.com/y4mQuYGevuelLRxs7B_2xfcPx2dfrzVpWMTFtNL0Xu2-PgGhiWUqA4LI7kIKQhX6KdutmBnsrOenhevTV0ILXYOKrBMvgodDIDpatRYu5VOSUT1THvLDcU0ALXeb3fDFBekvsCfMIU2vxQv8HbZZz98aXCgDh3D5Agyr1hsPhHJrE1xcqZYc2sa_Jvsh-hFOrGvpg0ytPXrc6BT0yN56qLGfw", 
    "Pacific Economic Development Canada": "https://yiopjq.ph.files.1drv.com/y4mhvBHe6PCZHLs0qJZ-PA9VYyoxrxzTnBNfr-F_vnwiF_Iu-34XdSpEpnpThODhOwXqaGLxPda09ZMGjlFvnFKHMJ3MRa0HlD3b0cDQrIXkguJDIMNZqGJfRP0GzFU0qXNhiqtm5I2WtDZaVmZBdCmhUpm-np8Cj3jl0qX8OF6rNdd473D0VgpvQIVDdI767n4DQYruwcCm0HemxWVx6kQ4Q", 
    "Pacific Pilotage Authority Canada": "https://yiopjq.ph.files.1drv.com/y4m_8klMoC-L-vRDQ-288ZwcSFckQrUIwyynr7rV7psqxxLBL0tZhwH2BFfDqAnuR9GqIwi2pBNyVRoxfHcXP_oElt2BZgStV68dJpzuc8V2HiLih12_oBB1SjAvabsU5uhtiWFeu3Wfp0qQ-jU52UXVs0hs2bdCrukCSC7jP-JyhfLLrCklk6Iu745o_REGbp0sY8lA3X9ru4PV1UpxtThvg", 
    "Parks Canada": "https://yiopjq.ph.files.1drv.com/y4mXJYILGnrZ8QZtrfb_MF5QD1Kgi5lZkBhoh_r7dNSsbPWAH95K0p_Ma1r5lcPzNyVLm_LgypEoQA0I5JHL0H7M3Si2ponoXDGnrH0L5Hziv9hItfJyKl7a5LhVHePqsdkGbBmWDGhvVHpaKgGjAuev2mSHgOHl-nZ-sWEMM5u0M90rEaEYAlYsp1qTpLmX-E8F-7cb2LyE7GHLgAp8WtW1w", 
    "Parliamentary Budget Officer": "https://yiopjq.ph.files.1drv.com/y4mn2x8Ew-g7KcGY5rXnC1mY4oyrIR_pQcQjNwP-9o0f2y4AEiHjOQW3xEOF7j05fG1ZEF9XOoTMubqE6H7yew48_SHPVNxQHKdcjdNyME3idlh_iwl57Qbqr0nx0KrXKH9sQROxlf5rSaGTZ75EGbQXQ_7OdaSamWz_DjgoiWwdU18bNyQedzRp0Ue8dOivL70PH2XbvL8uIzJYRGW1va47A", 
    "Parole Board of Canada": "https://yiopjq.ph.files.1drv.com/y4m5lvBcJ2AE1TCxNzYsqfe4eYYqBw1-I2zpQypfclhl6vNuwyYshNpG8fvhmGMjFWcrMyCYfUSaaT7x5QjtNDaUfp1ut3Yq8etHXd1e0DbPyf7A7z82hyr-eDZavhV154r3ZdAFQj1OdYfGt1yW644pnzulzrxa1OTzmfLmu-QolVCHIvm6AkkZDU90nRWzNbzGC8ARantpMXrxkUlztLnNw", 
    "Patented Medicine Prices Review Board": "https://yiopjq.ph.files.1drv.com/y4maQR0vKpQ6K0ry_2CwCHyU9VwkfAY75GqpfosfTjzR7a8Pgrcew6KYNWG46KyKsGwNm8ljocNdGTm7Vyd53565xOaml6tg2w4pDb0ej6uBOScFp2Sld3LF9Pd50a3w-OY4m5ibmqyee8ymlRA8fR0w9kWUWt2SWh9RBTajepuzDP2L_ZZ-0o-BsFIW5VuIrPjENuIaPbRxpFyyLdB3ZEqNQ", 
    "Polar Knowledge Canada": "https://yiopjq.ph.files.1drv.com/y4m4MbDrLNh7b3CmKl08t3oCrjBYbdBVXPak-mCZcVew_SM1-eHDSA_tTCO_fvcaUxNl4HNxxBd2u4iqNf-fsYz5c9FNRfibaWiwskLXxU4pTC4ehatHc4_Klg6woISqjAV_HDPY52t860B5b3S87Fbo3hUXM5fVt3GX8kf40I9PC86aLSTavCAKqNhZbpezAERUSDeza9AZx_KNugYRfbmeA", 
    "Policy Horizons Canada": "https://yiopjq.ph.files.1drv.com/y4myMhzIHQcSQPZTEbf-pVyrzarZsgSP1xUL8fzA3Ys_6FDDTqcMQipUXVOmZSJSKgkd0gH-o0ZCL_a9SSRt9P8MvZ_O1kfgboz81bqXsGMwMYoU7PYDJPMHD1VS5DkbuU5aC1GdLEiilPLdJms-m7jInfCZ0xeoBKr3jJaqBqCsridbdHNoj-LyHFFLnoU4Y6rsiQP9vB3AlSfQHhasoi_uw", 
    "PPP Canada": "https://yiopjq.ph.files.1drv.com/y4mRpnpyEGSUYmEW2zsIf4QD_7PqoTLVcCPz7D2u9uOaQCzJBXL3DF9WOCPyqheXNEcB0Q7boAh6scHGpfloWU-YLu7lOjup2t5OwcS6OuXDBGrthdKa4Hv3JZoxv4RIB6WNfx96H1bOFfX5disWu5pAQdbLMyWPtFXNJwmbSsips2mhvUcD6JVg4_-spV0i2a28Ebwp_1WRMYE9L2TClIO-w", 
    "Prairies Economic Development Canada": "https://yiopjq.ph.files.1drv.com/y4m_HLQnwrxT9UBWXfqDAu75nwPp5rk4XiKan-cXCCAuZkKQ1K0Si7-7MS_N0YGgMKA4twvopA7yb3Orfng-fqfwUHk86N9Le3AuJDMSKk9vLHE7dQ1KCCh7uhGiugO1lVeDC7gz3CwLK7irzckGjHJ2Hp_UJyTvIg2P-u3TOG9lqVGpKpivm71NyPO8DHhijDbhOwnidCGRyUy135Et3Qz8Q", 
    "Prime Minister's Office": "https://yiopjq.ph.files.1drv.com/y4mCbnpQIJV6nPkG1OmEmUpnxhoGglGttU63SC8WcpFzwx8skc9Bf27hM1aQn0bAKHWSntrtgvaiOGGySyprnXrOn4do14GMgRzr6FzaWinR_rEq48lzTNnAROfocvHPqrRvzOvqrT5POMRA6aGLMYHAFHkoqT86gmbOjiPb64BW5-Y8OJ8Nh6n5HFfrI7p9VmwIxiSQeD15uG3FbvElCcJQA", 
    "Privy Council Office": "https://yiopjq.ph.files.1drv.com/y4myB9q3D6A9P1WxcD_3okremKL6177sTjAReYVFUjtD8eYYIdvZ0gjmpUuX8vPel6E7MufFS2OjN9xWs8bkgPT-m1Zks0QdVnURITDhAV8HIZp3rQeGtfQILxT9wOA4gYnc9OtKUPQn15WDzBrv0MnjhuCC9pkmiO-EhLVSG9inggfk9DtKBJTLFt7f4BSWJ8ht1eVVld6wCcxOFy_hvzDaA", 
    "Public Health Agency of Canada": "https://yiopjq.ph.files.1drv.com/y4mBD-ugNupraTf2Izn6ipMSi_pJDakAko8r6zDk36BZpOAu5WndYzUfmgcbGqtzh3PwsAvSr3UCNQ8vawMXzusikp3udGiS6S6sWmlwEYaXq3d0iakpHuBIFHzw-slhVZFJWNsYiGcuRYkE_GHiFPyclKoKlqC4d5z-DYG1wNTCs-_lLnmcFoewYAINzFf7iakZqZfoxAJcgV4ICMS0SqN4Q", 
    "Public Prosecution Service of Canada": "https://yiopjq.ph.files.1drv.com/y4mxisFmW3D2LVSgRq0Yk5kQlNcf1y711eSp3TaHpu1HUse8_9zYygtbdd_k3jWwt0vJKz8z4BDktEEV7JcZ0ZsQ_7sHA5LpsGHO4r8l6e1cy1PQv9C5RONpH7Jx0ACPOZ-EvwKl3LVFAqVsfZ93vISEpj5wKubSo5dkX_3uJBgT_j2Q8WUsvt_yngnRL0fRIJ1HxgoVyrTWvjI6ibZ4CBwMA", 
    "Public Safety Canada": "https://yiopjq.ph.files.1drv.com/y4mod9HomgJoW0CQYKDGH90vGNX7Wcg4rrHalPFJ4-G_f4_afDUtn_cC49ydcQ2nC1ZRYz2MpEBBVspoVpyYTjDfkAPz77LSCSzNjOMSaiPk1d-wyN2EEBUMIZuxie8NFNhcmkTSbxWRuVp2x1P-hHu1tVNCVxPEsxaE8W-bCrVFGKyRuzakEqSv-uSoUhOb8b2z3rK13hjy8MlPXVyv7T21g", 
    "Public Servants Disclosure Protection Tribunal Canada": "https://yiopjq.ph.files.1drv.com/y4mKjSzZQeR0iP-FMFBv3AV6w5gNANmkWHvMsFQH0bb3ztCUptqMjwQlQ68DSrhv0-9yS4bNtG_tgGAYFZ3IKpS1p32I9mYeBWhg_G26fbYC0hUkOvHbDTQlv08H5gUQhLiqNy-fNgAZt3aLcYnuWwgjCnvT2ux4AuzzXcECIixSi9Yrqoz-YWFp-ygXZjXC8v1l6t6-meVRgJjaMa3Gbkn8g", 
    "Public Service Commission": "https://yiopjq.ph.files.1drv.com/y4mQR-vlrNZjMNW9U3cjSqBGyjXUAZK-MafKWolijrRjW6um55qTFPORi0X0BbhH_BbfLdOLDngcKM90IaybEhjekLT9gw009U-VI0H9e70QsVvIrRl18XZLX5fBmjnR4efkvOg3K4j_oIervpTEtfUqf7Ce0IObDdRXS8PTI9oBti8KmDjieBlve3e9olFJDx0Jq71R6J3x8kBvMgy22W5FA", 
    "Public Services and Procurement Canada": "https://yiopjq.ph.files.1drv.com/y4mrgGvJb2XxSeZD38I-t_QY0Z-aqjuNq-vmKDvAxT99Z-lErn30os4ExmGivr5YfSgqbW6TZ-5t9iw1Z2awhdAT-HE1Q2v5Gjlx7ct8u7I-T51LrdMW8IV8YsSGTUmzd-cBfpDIz9gYgO9yzrRlZPcQyOXgmc0h0F8wl9t6MXqIoJ-RaETJ77I5h-K5D7mVZIubYKwzHAVZBgFxqU7xGVAFg", 
    "Royal Canadian Mint": "https://yiopjq.ph.files.1drv.com/y4msU3E0GHEzF2sPDqzJSFIWQZ5zPUBuBNqjWBMzWKPbCMq8Piu7UMqmMsUq6L7T1qqdnAcBBfZ5muArq-StotteiqSImRV9m0OHkzWFGZWdGsOoEX6Fdfu8F5W0CvyelMCIYGwGFrQk__au-opD1kq_cJuD-jbg5gOIiFj_VJaQWUr6l2MxlOkCN3T6emrJCI-ToIQ3s7BYnWZlrItxA3ANA", 
    "Royal Canadian Mounted Police External Review Committee": "https://yiopjq.ph.files.1drv.com/y4m9E_0P8buYw7gPFntNFO8eR2-1nSViECGweqKngnOtbpq2cxQd5MwVSUbC-v5pt6hf2VD5RXiyHnFygH5huGP71ohqQLZruE4VZzwFOTFfaCuAHuzylpduaBi7RoPZkt9cNPeuKgDqN32lkjmfIohnVFSO7JbV7rYsSIl7Dul_4P3zfmf6CHAt7FZ5HtzvSg6sqCmTarjClOJrpppt9QOvA", 
    "Royal Canadian Mounted Police": "https://yiopjq.ph.files.1drv.com/y4mis4DglZ4sZ30oLvPqmIRldM9KSg8fNVQFVKkBjTXLn9vCQ3qzp2tCSvimMBd-fdJ5wyfKEJNQG-WaVGAEtWjtV7vatMt-iZUOj645c8SIYV9vYC8RRfvqh7XqH2IkfDSkf00kepTejwGg_jmAi1BX3qbkwlel1hBzlK-JiqRKHLuDQwgg_Sc5pobqQP5SRrz0iYypyvg-zsNV0ixwKjXHA", 
    "Royal Society of Canada, The": "https://yiopjq.ph.files.1drv.com/y4mj5TDtcMdeMkjADdbFke-t4C-z3K8lLAx7mCFucjrTu3_OUF4XuMFj53JPxolZxU7hvT2oDIktjk_oBRQWVuJq_YWhJe9rQkbDdkUUIp0XjlB4RnPcN3lgD04H45ZCiH6k5aorUqxe-P9iea1120PlU7o5o5vfKNyTNA4UZ3ILLGBpPFefrF6RXY6heN3kg9kHqO1Hwre6Db0PU0uTZnY-w", 
    "Secretariat of the National Security and Intelligence Committee of Parliamentarians": "https://yiopjq.ph.files.1drv.com/y4mrBGMWpH3iLp6XH-AdImFvCefYg5mX5IObp0EHAFpXT5taOXUL4nbCCu0rzO475B24lVXbIe5g91HY449CNK-iJ-neIzcJpX3G5pHcHKpE-IS-PbOhsaLUfGx6_sgjID2wd26DgMSERgdIdiGoF6zJ1eoMxJ0LB9W_9yFaEIXmMrCosn3pmU0XAzNzaYheY_QtnMviPz-a2Mr0g6ML_Ucbw", 
    "Senate of Canada": "https://yiopjq.ph.files.1drv.com/y4mh8i_btx2wivmrRQiD1NLj2zVoh4y12DGknkQlZ6cmaXfXO-hR6a8TL6X-w4m_SODnOHusK2jw7wYK8PU2c1V5gw7enGZfv_vWNKx7VbVJfJFHVV-oFllHe37C1irXZ7IZFbdFwlVlgILXwI3FtGdpqh-p4y-SfolzhrRt8N-s_CHHf_ldU1zjNR14e7mkdM_bRZZrHpaP1m8Xq5TFwUDlA", 
    "Shared Services Canada": "https://yiopjq.ph.files.1drv.com/y4mFA4JilT_aDBcqX7E8x5OhhiHl0_eJ7jEr7pBq5pok095ArTX7wTd2vjl5LFad_l0LjPeNMyZpJIS4D9TuS5dvwcftwDvwBNBgomMWZZ7oJwtHVNQQeED6kM6E4k-vHsXetWEpcRkcBpUsaVd4iRgrVJHjBHGCzuZ44UUNuF5BwKdIDhGj1-fOqfAwHzE8TlM9zJxbJKZLqUDxfDNN3xqmQ", 
    "Social Sciences and Humanities Research Council of Canada": "https://yiopjq.ph.files.1drv.com/y4muVenS0hECw-mqCrUjj_itXoo9RLQeYwq_7EhUdN1WW7OclIRYYMNKcMQLbe7j96OrpA1iakuRWDagZY6v4EoV63jbCjSE-Y5EfTWcxRG5qu2siYBwb7U0EY65fA9ts0H5msRPnAPyEqrVVNvlntgOuQyaUOBV4TYWaWAiVv21589opOfWjh_l3OsOiO-eJESHDjA7ZxsZAbX4U5ej1K4vA", 
    "Social Security Tribunal of Canada": "https://yiopjq.ph.files.1drv.com/y4mmF--RyUNjQ5yfzEQtyE1xLvbqSszuroTA7CcOWrLlk49iyjHu9vuh1Uro5htaNiuPpr3jziw50igZqJo8CJbDM0JaZhHHaTVq5i2FpnsoS4cQtsxeJhnMNS5ymMikpdLXt0a8kjI3RNJrAwBOwsEZeoYbJbpObaTAw48fnPhxkhwDqwSYtKVDfioENDz1zZ9vvXSsfPSRHEdapfaMYRe3g", 
    "Standards Council of Canada": "https://yiopjq.ph.files.1drv.com/y4mjdU9d_6Dba9U7bi7jsm_X_xyQ2Q9rmzQA6Gx_2YQEA_j0N27KfiStNjM8GwfCpNVl-oe4QvsfdUtcxb3r6kbS3eesYXQH-LC7Xce_PwsYGp_Q5eJT7S1pvgCOjyDaktgEIN35b-hJuitHPOkY7rPWc2XV1xbfio2AGBmvXBUsRmgtm0vDrEu0qWjFqqIaKrxZSo92lty8aDEXOqEt_HpeQ", 
    "Statistics Canada": "https://yiopjq.ph.files.1drv.com/y4mchfqG3DvL8_TWlznQxx-UUZOcqYxevorXSDzBCQ8LVreMvxDM_nMYxadV3i2UEj8fbJcx-ya0ZEyeHKbLF4IGxLUDfwOrcCaK28ncj_V8FTq4zWwnnsrPoFcNs6kGtN-wHBjvVhPBp7A1KAA1K-jWoKwy3Y_Jjo14S8KqZuPJibZlFgpjgd-nYLVc2R7DLX8KrH6PaNv9fPZVU36KwA7ig", 
    "Supreme Court of Canada": "https://yiopjq.ph.files.1drv.com/y4mK6vfpSL6SGj2MJAeejFGId89B6vBv7rnDlzu9ouaL3In3W7tTvhN3vut0Grjqz6yEszAnF2WKV2RCMhUd_XMKfzGgL6tq4D-Z2Qtfa4wNviQIAz2vW9lz-dH3cVsH6aVQyGfDHzz4EwH_XKDNHRJHr1AZ-OrfYaro6PWLmaXklcYv7BUnWQn4ykmom_BvdDdoibtgoRIJ2r6BnBN-kZodQ", 
    "Tax Court of Canada": "https://yiopjq.ph.files.1drv.com/y4mZW35IoswK5i-iSjVuCn7vRFIvxIPKr5uZIH80kelfwcff_A02vm0ozTalg8USnUpmFiB21mbQog2gWp2D-F0DwqP4Cx09FWHTT_C2sgyJH-j9F0ey_KsUhGhUk-WfDFtSAuugFfkjiMi8ts6ZEeMa2IF9X09M-NETE2UygxlAUWsT-2aL2WQhWqXE-LQxZiHt4bUp4zSIdKYimAeAZdqxQ", 
    "Telefilm Canada": "https://yiopjq.ph.files.1drv.com/y4mxIwwDBXzbEzhDfTDUXFz4ZE_vPiyWaRwd9ddi3lsgapikVJ5F9rb59RjFiO1ervpxEZ2aG3gITRh97uKeqViQ6wf0avNZUW_H4oVX_-QH4tG3tMXVXmlFSyGL-QO5rIPFQij4OZCqt6eRyOqc45xSE2guYAmOAYNCaGDtWXDii8HihZGo_7__yaW_6edp7svmAMy8cPFV-lZjaIvvHQlNw", 
    "The Federal Bridge Corporation Limited": "https://yiopjq.ph.files.1drv.com/y4maM-JaLbG-Juvw-fObF--7-kqFV7OxsgnwsDn1BzVR8peNufIePQbX3ffacNEN0j6Bt4BogyHDFFXS9rFN6PxaBfF8SOAe7ZiAjOzKyYvRKqo4XYF6vCQZURxeUhO1_V2IA25aBVB82jmaaPKelArIUs1UgXTXqlGUbpvSW000oNMOOfO7irqDSqQUrsDwe5ivqMSkLYibo-rvb3oXXhZaA", 
    "The Jacques Cartier and Champlain Bridges Incorporated": "https://yiopjq.ph.files.1drv.com/y4mPnBl9MqEFVEPKeDQiZKLHICkcp0UMFbysG2K5RrHOUVZegcSJldKReIGnRuZTTrbjlKEBFFkqs8ipEFx-N0C4QOYyaIlpq0xCGRkBrktJpzyHoGXYMfd8Ggi93tzM549lDFhAgG2T_N6-ae72UFC6PuYwfdsiwCdMAH9IAHfN1JuI9zjYcrQWCOPG5Ggc4HetPTGuRorjogUyQPzRrc2Fg", 
    "The National Battlefields Commission": "https://yiopjq.ph.files.1drv.com/y4mIZBa2PpU896VMQ5la7NjsKqZKMSWlTolBf_65kEngV1q-YJ5qGnjoMdXOmoTXPg4c7ugHhavH-4gLBEAQC-ayH76TvkXzHgi0Kq_6bgUbZhMA1FQBBNQP6yesm4Q5zgruuoHp7GCR5yjUMfMj4wpJW0WgjldQilSFxo-og0mb7_60aR7jjUcCBHaxM7CXpBY_RWgkGqpyJFAAQRFqX2iVQ",
    "Transport Canada": "https://yiopjq.ph.files.1drv.com/y4miESxrWjalL7xSgoRLbZ2mtr1bhrkAYqozsXL3iqD_aUNO8kvGcoUtAnPqDkxBJ7P365Dr4U64VU72HYg7sH1nVd9Vt8b1rcvZppxI6ynsDNUyEyMOtgV60XlUgjT-tcGm3u8TQTO9PJwC2vcadMUyrr8wT5m0kAxKzyO6RmjkGCoCUA6ImyYxC5Ef8a65jkRCecbDnBWnlHP8rFa0g7i9A", 
    "Transportation Appeal Tribunal of Canada": "https://yiopjq.ph.files.1drv.com/y4mTrJBNkAUyWCMQn37KjqVXTka6C9avDLee6L1uu6I35gaEt-FGRHWidPeE_lGVGHq-B_u7tfLqeI9IVAoTbKxRdAR3x-GhFfbTeB9i-QHvMcbLDbIdDSeafaSg9XEO9dz9ehE2ovn-peIu1Ts-xRjsIoniyvNOWKXKZu_1OTGiLTWxn-ZZqg23sce4Jzswe08ncstVOlvaoefuMuUbIsN9A", 
    "Transportation Safety Board of Canada": "https://yiopjq.ph.files.1drv.com/y4m0sWiGRrwVvUy112_wTPGpoT454sCJiq2Eah7M7DZoP-vEPM7MzYfi_a4IDXO9R-I8Kwc_A4Ixbfymv0S9MPwd_FTlmVvqIOtVGuTL3N_8rw6BPmbyTAobuluJ--lSC9yB0t7OKL5ToSrTkX-nXjdK2i9S_CQ3OXCH47oWBHO5hIPGIQkoyijHqiOT1XrPfO0GCFAMyvvqclqgC0UwQNi9Q", 
    "Treasury Board of Canada Secretariat": "https://yiopjq.ph.files.1drv.com/y4mZRqdrjrhrayypsOzFXjQlz0LUegZp3Nc9u0K5KLFBieCT-A-siwMgabVn0lMMA0xzcwkJ7usaaZG40SLnKZWOXVLpvTiz1UfjukggesT6GUYeqMg_Ug8TCOZJoitHIGbukYwvIzcyLbEhjGsy5cCIOVTmnyG9H5XjwD9_98VhP5FaWiFdZa7263iwzLwxeY04CJUplSygyCaRmgs6blVfA", 
    "Veterans Affairs Canada": "https://yiopjq.ph.files.1drv.com/y4mlrAKLT1YOo6epUQLhGomNRsvDH7G1rmbB87JWmazoGidKzP_HmEC-jabD4ijP4f3dt29UhQY9g-YOJexv_68aH4ZBHmBWu_yDZlhOHIm9MlWjtVX9nO89BtaQoMsleLkA2xL1QZriUFTwWoOiN5qP-WueCNUChvJQYaT5aJbU67xhr2qIxJjFAIFBSQL2ZGLdeK_mngFQECDM35ngDWpIg", 
    "Veterans Review and Appeal Board": "https://yiopjq.ph.files.1drv.com/y4m3G4TCYmyr4HoQdaSOsaDiBK8dgmCTDXE_5jwAaTo9BDo2hIzh2Sq03KZTKybQgmW8ZxyIqUNP2V2Iai3nefqtPczd-xtep0hRAr1M3TcGwIsISdPwalrjF7vqnSqbd_fDf-aMeF593jcK27nt2YBb5z0wxDsmA81vRtBgtJZB8z8rHtsQyD_WIuiNzF2XoQqeiCfoyQ3QgJV18UUmKK8sw", 
    "Women and Gender Equality Canada": "https://yiopjq.ph.files.1drv.com/y4mAw45bw8pRqAC8tuQVBdmXbjiXbxn2nVGrvoTD5n4sXCpXcy60RYuaADp68cbSmdJolrgKgQhXdsFFd2d_BKbYmXwGRLFlmM8LHDNtL_Hw_vJSN1igPamtw_tnGV3yPkmivs7ww8zqsgYnjTztuzaFJ5S-7gvmWUnbd6gCp8y_sWJuCOvIG2sEKg_wKpCxjXmVgOjgjiuxKutuCZQD4tXJw"
}

let govData = {}
let total_offset = 0;
let total_vertical_offset = 0;
let total_horizontal_offset = 0;
const board = miro.board;

function makeSticky(stickyData) {
    let tempSticky = board.createStickyNote(stickyData)
    return tempSticky
}

function makeTag(tagData) {
    let tempTag = board.createTag(tagData)
    return tempTag
}

function createShape(shapeData) {
    let tempShape = board.createShape(shapeData);
    return tempShape
}

//this one will draw the department horizontally
async function drawHorizontal(departmentName, horizontalOffset, verticalOffset, isFrench) {
  let baseWidth = 87;
  let baseHeight = 212;
  let baseBuffer = 12;

  let stickyHeight = 27;
  let stickyBuffer = 5;
  let count = 0;

  let departmentFontSize = 36;
  let secondaryFontSize = 13;

  total_offset = parseInt(horizontalOffset)
  let shapes = [];
  for (const department in govData['childOrgs']) {
      let element = govData['childOrgs'][department] 
      let departmentChildLength = Object.keys(element['childOrgs']).length; 
      let secondary_depth_child_orgs = 0
      for (let each_branch in element['childOrgs']) {
          secondary_depth_child_orgs = secondary_depth_child_orgs + Object.keys(element['childOrgs'][each_branch]['childOrgs']).length
      } 
      let deptShapeWidth = (baseWidth * departmentChildLength) + (secondary_depth_child_orgs * (baseWidth + baseBuffer)) + (baseBuffer * secondary_depth_child_orgs) + (baseBuffer * departmentChildLength);
      if (departmentChildLength == 0) {
          deptShapeWidth = 1500
      }
      let departmentShape = await createShape({
        content: (isFrench ? element.name_fr : element.name_en) + " (" + element.population + (isFrench ? ' personnes)' : ' people)'),
        shape: 'round_rectangle',
        style: {
            borderOpacity: 0.8,
            color: '#1a1a1a',
            fillColor: '#8fd14f',
            fillOpacity: 0.4,
            fontFamily: 'open_sans',
            fontSize: departmentFontSize,
            textAlign: 'center',
            textAlignVertical: 'middle'
        },
        x: total_offset + baseBuffer + (deptShapeWidth / 2),
        y: verticalOffset,
        width: deptShapeWidth,
        height: baseHeight,
      })
      shapes.push(departmentShape)

      let subCount = 0;
      let branch_offset = 0
      for (let branch_node in govData['childOrgs'][department]['childOrgs']) {
          const branch = govData['childOrgs'][department]['childOrgs'][branch_node];
          let branchChildLength = Object.keys(branch['childOrgs']).length;  
          let secondary_branch_length = 0;
          for (let each_secondary_branch in branch['childOrgs']) {
              if (secondary_branch_length < Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length) {
                  secondary_branch_length = Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length;
              }
          } 
          let shapeWidth = baseWidth + (branchChildLength * (baseWidth + baseBuffer)) + (baseBuffer * branchChildLength);
          let shapeHeight = (baseHeight * 3) + (baseHeight * secondary_branch_length) + (baseBuffer * secondary_branch_length) + baseHeight / 2;
          let branchShape = await createShape({
            shape: 'round_rectangle',
            content: (isFrench ? branch.name_fr : branch.name_en) + " (" + branch.population + (isFrench ? ' personnes)' : ' people)'),
            x: total_offset + branch_offset + baseBuffer + (shapeWidth / 2), 
            y: verticalOffset + baseHeight + (baseBuffer * 4),
            height: baseHeight + baseBuffer, 
            width: shapeWidth,
            style: {
                borderOpacity: 0.8,
                color: '#1a1a1a',
                fillColor: '#8fd14f',
                fillOpacity: 0.4,
                fontFamily: 'open_sans',
                fontSize: secondaryFontSize,
                textAlign: 'center',
                textAlignVertical: 'middle'
            }
          })
          subCount++
          let divisionCount = 1;
          let division_offset = 0;
          for (let division_node in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs']) {
              const division = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]
              let final_depth_child_orgs = Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // final_depth_child_orgs = 1
              // for (each_team in govData['childOrgs']['Employment and Social Development Canada']['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
              //     final_depth_child_orgs = final_depth_child_orgs + Object.keys(govData['childOrgs']['Employment and Social Development Canada']['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // } 
              // console.log()
              let division_shape_height = (stickyHeight * final_depth_child_orgs) + (baseBuffer * final_depth_child_orgs) + baseHeight / 2;;
              let divisionTicket = await createShape({
                shape: 'round_rectangle',
                content: (isFrench ? division.name_fr : division.name_en) + " (" + division.population + (isFrench ? ' personnes)' : ' people)'),
                x: (baseWidth * divisionCount) + total_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                y: verticalOffset + (division_shape_height / 2) + (baseHeight * 2) - (baseBuffer * 1),
                height: division_shape_height, width: baseWidth,
                style: {
                    borderOpacity: 0.8,
                    color: '#1a1a1a',
                    fillColor: '#8fd14f',
                    fillOpacity: 0.4,
                    fontFamily: 'open_sans',
                    fontSize: secondaryFontSize,
                    textAlign: 'center',
                    textAlignVertical: 'top'
                }
              })
              let teamCount = 1;
              for (let each_unit in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
                  let team_details = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs'][each_unit]
                  
                  let teamLabel = makeSticky({
                      content: (isFrench ? team_details.name_fr : team_details.name_en) + " (" + team_details.population + (isFrench ? ' personnes)' : ' people)'),
                      style: {
                          fillColor: 'light_yellow',
                          textAlign: 'left',
                          textAlignVertical: 'middle'
                      },
                      origin: 'center', 
                      x: (baseWidth * divisionCount) + total_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                      y: verticalOffset + (baseHeight * 2 + stickyHeight * 3) + (stickyHeight * teamCount) + (stickyBuffer * teamCount), 
                      height: stickyHeight
                  })
                  teamCount++
              }

              divisionCount++
          }
          division_offset = division_offset + baseWidth + baseBuffer
          branch_offset = branch_offset + shapeWidth + baseBuffer

          count++
      }
      total_offset = total_offset + deptShapeWidth + baseBuffer;
      miro.board.viewport.zoomTo(shapes);
  }

  const department_title = await board.createText({
      content: (isFrench ? govData.name_fr : govData.name_en),
      style: {
          color: '#1a1a1a',
          fontFamily: 'open_sans',
          fontSize: 288,
          textAlign: 'left'
      },
      x: 4000, 
      y: verticalOffset - baseHeight - baseBuffer * 4,
      rotation: 0, 
      width: 8000
  })
}

//This one will draw the department vertically
async function drawVertical(departmentName, horizontalOffset, verticalOffset, isFrench) {
  let baseHeight = 87;
  let baseWidth = 212;
  let baseBuffer = 12;

  let stickyHeight = 27;
  let stickyBuffer = 5;
  let count = 0;

  let departmentFontSize = 36;
  let secondaryFontSize = 13;

  total_vertical_offset = parseInt(verticalOffset)
  total_horizontal_offset = parseInt(horizontalOffset)
  let shapes = [];
  for (const department in govData['childOrgs']) {
      let element = govData['childOrgs'][department] 
      let departmentChildLength = Object.keys(element['childOrgs']).length; 
      let secondary_depth_child_orgs = 0
      for (let each_branch in element['childOrgs']) {
          secondary_depth_child_orgs = secondary_depth_child_orgs + Object.keys(element['childOrgs'][each_branch]['childOrgs']).length
      } 
      let deptShapeHeight = (baseHeight * departmentChildLength) + (secondary_depth_child_orgs * (baseHeight + baseBuffer)) + (baseBuffer * secondary_depth_child_orgs) + (baseBuffer * departmentChildLength);
      if (departmentChildLength == 0) {
          deptShapeHeight = 1500
      }
      let departmentShape = await createShape({
        shape: 'round_rectangle',
        content: (isFrench ? element.name_fr : element.name_en) + " (" + element.population + (isFrench ? ' personnes)' : ' people)'),
        origin: 'center', 
        y: total_vertical_offset + baseBuffer + (deptShapeHeight / 2), 
        x: total_horizontal_offset,
        width: baseWidth, 
        height: deptShapeHeight,
        style: {
            borderOpacity: 0.8,
            color: '#1a1a1a',
            fillColor: '#8fd14f',
            fillOpacity: 0.4,
            fontFamily: 'open_sans',
            fontSize: departmentFontSize,
            textAlign: 'center',
            textAlignVertical: 'middle'
        }
    })
      shapes.push(departmentShape)

      let subCount = 0;
      let branch_offset = 0
      for (let branch_node in govData['childOrgs'][department]['childOrgs']) {
          const branch = govData['childOrgs'][department]['childOrgs'][branch_node];
          let branchChildLength = Object.keys(branch['childOrgs']).length;  
          let secondary_branch_length = 0;
          for (let each_secondary_branch in branch['childOrgs']) {
              if (secondary_branch_length < Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length) {
                  secondary_branch_length = Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length;
              }
          } 
          let shapeHeight = baseHeight + (branchChildLength * (baseHeight + baseBuffer)) + (baseBuffer * branchChildLength);
          let branchShape = await createShape({
            shape: 'round_rectangle',
            content: (isFrench ? branch.name_fr : branch.name_en) + " (" + branch.population + (isFrench ? ' personnes)' : ' people)'),
            origin: 'center', 
            y: total_vertical_offset + branch_offset + baseBuffer + (shapeHeight / 2), 
            x: total_horizontal_offset + (baseWidth + (baseBuffer * 4)),
            width: baseWidth + baseBuffer, 
            height: shapeHeight,
            style: {
                borderOpacity: 0.8,
                color: '#1a1a1a',
                fillColor: '#8fd14f',
                fillOpacity: 0.4,
                fontFamily: 'open_sans',
                fontSize: secondaryFontSize,
                textAlign: 'center',
                textAlignVertical: 'middle'
            }
          })
          subCount++
          let divisionCount = 1;
          let division_offset = 0;
          for (let division_node in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs']) {
              const division = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]
              let final_depth_child_orgs = Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // final_depth_child_orgs = 1
              // for (each_team in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
              //     final_depth_child_orgs = final_depth_child_orgs + Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // } 
              // console.log()
              let division_shape_width = (stickyHeight * final_depth_child_orgs) + (baseBuffer * final_depth_child_orgs) + baseWidth / 2;;
              let divisionTicket = await createShape({
                shape: 'round_rectangle',
                content: (isFrench ? division.name_fr : division.name_en) + " (" + division.population + (isFrench ? ' personnes)' : ' people)'),
                origin: 'center', 
                y: (baseHeight * divisionCount) + total_vertical_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                x: total_horizontal_offset + ((division_shape_width / 2) + (baseWidth * 2) - (baseBuffer * 1)),
                width: division_shape_width, 
                height: baseHeight,
                style: {
                    borderOpacity: 0.8,
                    color: '#1a1a1a',
                    fillColor: '#8fd14f',
                    fillOpacity: 0.4,
                    fontFamily: 'open_sans',
                    fontSize: secondaryFontSize,
                    textAlign: 'center',
                    textAlignVertical: 'top'
                }
              })

              let teamCount = 1;
              for (let each_unit in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
                  let team_details = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs'][each_unit]
                  
                  let teamLabel = makeSticky({
                    shape: 'square', 
                    content: (isFrench ? team_details.name_fr : team_details.name_en) + " (" + team_details.population + (isFrench ? ' personnes)' : ' people)'),
                    style: {
                        fillColor: 'light_yellow',
                        textAlign: 'left',
                        textAlignVertical: 'middle'
                    },
                    origin: 'center', 
                    y: (baseHeight * divisionCount) + total_vertical_offset + baseBuffer + division_offset + branch_offset + (baseBuffer * divisionCount), 
                    x: total_horizontal_offset + ((baseWidth * 2) + (stickyHeight * teamCount) + (stickyBuffer * teamCount)),
                    height: stickyHeight
                  })
                  teamCount++
              }

              divisionCount++

          }
          division_offset = division_offset + baseHeight + baseBuffer
          branch_offset = branch_offset + shapeHeight + baseBuffer

          count++
      }
      total_vertical_offset = total_vertical_offset + deptShapeHeight + baseBuffer;
      miro.board.viewport.zoomTo(shapes);
    }
  const department_title = await board.createText({
    content: (isFrench ? govData.name_fr : govData.name_en),
    style: {
        color: '#1a1a1a',
        fillColor: '#ffffff',
        fillOpacity: 0,
        fontFamily: 'open_sans',
        fontSize: 288,
        textAlign: 'right'
    },
    origin: 'center', 
    x: horizontalOffset - baseWidth - baseBuffer * 4, 
    y: 4000,
    rotation: -90, 
    width: 8000
  })
}

//This is the same as the drawVertical but flipped along the Y axis so it draws to the left instead of the right.
async function drawInvertedVertical(departmentName, horizontalOffset, verticalOffset, isFrench) {
  let baseHeight = 87;
  let baseWidth = 212;
  let baseBuffer = 12;

  let stickyHeight = 27;
  let stickyBuffer = 5;
  let count = 0;

  let departmentFontSize = 36;
  let secondaryFontSize = 13;

  total_vertical_offset = parseInt(verticalOffset)
  total_horizontal_offset = parseInt(horizontalOffset)
  let shapes = [];
  for (const department in govData['childOrgs']) {
      let element = govData['childOrgs'][department] 
      let departmentChildLength = Object.keys(element['childOrgs']).length; 
      let secondary_depth_child_orgs = 0
      for (let each_branch in element['childOrgs']) {
          secondary_depth_child_orgs = secondary_depth_child_orgs + Object.keys(element['childOrgs'][each_branch]['childOrgs']).length
      } 
      let deptShapeHeight = (baseHeight * departmentChildLength) + (secondary_depth_child_orgs * (baseHeight + baseBuffer)) + (baseBuffer * secondary_depth_child_orgs) + (baseBuffer * departmentChildLength);
      if (departmentChildLength == 0) {
          deptShapeHeight = 1500
      }
      let departmentShape = await createShape({
        shape: 'round_rectangle',
        content: (isFrench ? element.name_fr : element.name_en) + " (" + element.population + (isFrench ? ' personnes)' : ' people)'),
        origin: 'center', 
        y: total_vertical_offset + baseBuffer + (deptShapeHeight / 2), 
        x: total_horizontal_offset,
        width: baseWidth, 
        height: deptShapeHeight,
        style: {
            borderOpacity: 0.8,
            color: '#1a1a1a',
            fillColor: '#8fd14f',
            fillOpacity: 0.4,
            fontFamily: 'open_sans',
            fontSize: departmentFontSize,
            textAlign: 'center',
            textAlignVertical: 'middle'
        }
          })

      shapes.push(departmentShape)

      let subCount = 0;
      let branch_offset = 0
      for (let branch_node in govData['childOrgs'][department]['childOrgs']) {
          const branch = govData['childOrgs'][department]['childOrgs'][branch_node];
          let branchChildLength = Object.keys(branch['childOrgs']).length;  
          let secondary_branch_length = 0;
          for (let each_secondary_branch in branch['childOrgs']) {
              if (secondary_branch_length < Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length) {
                  secondary_branch_length = Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length;
              }
          } 
          let shapeHeight = baseHeight + (branchChildLength * (baseHeight + baseBuffer)) + (baseBuffer * branchChildLength);
          let branchShape = await createShape({
            shape: 'round_rectangle',
            content: (isFrench ? branch.name_fr : branch.name_en) + " (" + branch.population + (isFrench ? ' personnes)' : ' people)'),
            origin: 'center', 
            y: total_vertical_offset + branch_offset + baseBuffer + (shapeHeight / 2), 
            x: total_horizontal_offset - (baseWidth + (baseBuffer * 4)),
            width: baseWidth + baseBuffer, 
            height: shapeHeight,
            style: {
                borderOpacity: 0.8,
                color: '#1a1a1a',
                fillColor: '#8fd14f',
                fillOpacity: 0.4,
                fontFamily: 'open_sans',
                fontSize: secondaryFontSize,
                textAlign: 'center',
                textAlignVertical: 'middle'
            }
          })
          subCount++
          let divisionCount = 1;
          let division_offset = 0;
          for (let division_node in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs']) {
              const division = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]
              let final_depth_child_orgs = Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // final_depth_child_orgs = 1
              // for (each_team in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
              //     final_depth_child_orgs = final_depth_child_orgs + Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // } 
              // console.log()
              let division_shape_width = (stickyHeight * final_depth_child_orgs) + (baseBuffer * final_depth_child_orgs) + baseWidth / 2;;
              let divisionTicket = await createShape({
                shape: 'round_rectangle',
                content: (isFrench ? division.name_fr : division.name_en) + " (" + division.population + (isFrench ? ' personnes)' : ' people)'),
                origin: 'center', 
                y: (baseHeight * divisionCount) + total_vertical_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                x: total_horizontal_offset - ((division_shape_width / 2) + (baseWidth * 2) - (baseBuffer * 1)),
                width: division_shape_width, 
                height: baseHeight,
                style: {
                    borderOpacity: 0.8,
                    color: '#1a1a1a',
                    fillColor: '#8fd14f',
                    fillOpacity: 0.4,
                    fontFamily: 'open_sans',
                    fontSize: secondaryFontSize,
                    textAlign: 'center',
                    textAlignVertical: 'top'
                }
              })

              let teamCount = 1;
              for (let each_unit in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
                  let team_details = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs'][each_unit]
                  
                  let teamLabel = makeSticky({
                      shape: 'square', 
                      content: (isFrench ? team_details.name_fr : team_details.name_en) + " (" + team_details.population + (isFrench ? ' personnes)' : ' people)'),
                      style: {
                          fillColor: 'light_yellow',
                          textAlign: 'left',
                          textAlignVertical: 'middle'
                      },
                      y: (baseHeight * divisionCount) + total_vertical_offset + baseBuffer + division_offset + branch_offset + (baseBuffer * divisionCount), 
                      x: total_horizontal_offset - ((baseWidth * 2) + (stickyHeight * teamCount) + (stickyBuffer * teamCount)),
                      height: stickyHeight
                  })
                  teamCount++
              }

              divisionCount++

          }
          division_offset = division_offset + baseHeight + baseBuffer
          branch_offset = branch_offset + shapeHeight + baseBuffer

          count++
      }
      total_vertical_offset = total_vertical_offset + deptShapeHeight + baseBuffer;
      miro.board.viewport.zoomTo(shapes);
  }
  const department_title = await board.createText({
      content: (isFrench ? govData.name_fr : govData.name_en),
      style: {
          color: '#1a1a1a',
          fontFamily: 'open_sans',
          fontSize: 288,
          textAlign: 'left'
      },
      origin: 'center', 
      x: horizontalOffset + baseWidth + baseBuffer * 4, 
      y: 4000,
      rotation: 90, 
      width: 8000
  })
}

let activeLanguage = "lang_en";
let frenchValue = false;
//Setting up the listeners for the user-facing menus and buttons
document.getElementById('languageToggle').addEventListener('click', function() {
    if(document.getElementById('languageToggle').value == "EN") {
        document.getElementById('languageToggle').value = "FR";
        document.getElementById('languageToggle').innerHTML = "EN";
        activeLanguage = "lang_fr"
        frenchValue = true;
    } else {
        document.getElementById('languageToggle').innerHTML = "FR";
        document.getElementById('languageToggle').value = "EN";
        activeLanguage = "lang_en"
        frenchValue = false;
    }

    document.querySelector('.form-group.lang_fr').classList.toggle('invisible')
    document.querySelector('.form-group.lang_en').classList.toggle('invisible')
    document.querySelector('.layout_form.lang_fr').classList.toggle('invisible')
    document.querySelector('.layout_form.lang_en').classList.toggle('invisible')
    document.querySelector('.intro_graph.lang_fr').classList.toggle('invisible')
    document.querySelector('.intro_graph.lang_en').classList.toggle('invisible')
    document.querySelector('.contact_graph.lang_fr').classList.toggle('invisible')
    document.querySelector('.contact_graph.lang_en').classList.toggle('invisible')
    if (frenchValue) {
        document.querySelector('#drawStart').innerHTML = "DESSINER!"
    } else {
        document.querySelector('#drawStart').innerHTML = "DRAW!"
    }
})


document.getElementById('drawStart').addEventListener('click', function() {
  let departmentToDraw = document.querySelector('#selectDept.' + activeLanguage).value;
  let layoutChoice = document.querySelector('#selectLayout.' + activeLanguage).value;
//   let horizontalOffset = parseInt(document.getElementById('horOffset').value);
//   if (horizontalOffset == NaN) {
    let horizontalOffset = 0;
//   }
//   let verticalOffset = parseInt(document.getElementById('vertOffset').value);
//   if (verticalOffset == NaN) {
    let verticalOffset = 0;
//   }
  let datalink = linkResources[departmentToDraw]
//   logEvent(analytics, 'select_content', {
//     content_type: "department",
//     content_id: departmentToDraw
//     });
//   logEvent(analytics, 'select_content', {
//     content_type: "format",
//     content_id: layoutChoice
//     });

  fetch(datalink)
  .then((response) => response.json())
  .then(function(data) { 
    govData = data;
    let headlineName = data['name']
    if (layoutChoice == "horizontal") {
      drawHorizontal(departmentToDraw, horizontalOffset, verticalOffset, frenchValue)
    }
    if (layoutChoice == "vertical") {
      drawVertical(departmentToDraw, horizontalOffset, verticalOffset, frenchValue)
    }
    if (layoutChoice == "invertedVertical") {
      drawInvertedVertical(departmentToDraw, horizontalOffset, verticalOffset, frenchValue)
    }
  });
})