const linkResources = {
    "Accessibility Standards Canada": "https://aa153w.ph.files.1drv.com/y4maUKNN15T0v-cn0QXTuDVPdr8yc-63AwkNTjL73cogUxr_38IP0zVUSNfyNKBil939OXDNoUssVyvnjtSLRfrJBAbSEI8FCK-sncDc9CeSHP3hZyw4dFVBSI41CW88Zv0hjehuSm64Dum1Q17teouzxcxkaR71S1qEvhb48juuQprumi4wumsOFs4dGkoOWCl8Hh6AbsdKgI8oGO9GOjNvw",
    "Administrative Tribunals Support Service of Canada": "https://8n6jpq.ph.files.1drv.com/y4myn-WwNTkZuvyV9_dPxaTc7A7dnM3hycSJHSAIAas5b4oRwvUKZJ6uRIc6LvJARp1Gqh_SO1kS7DM0_gDbWRQ_kjZj_lWfbVsv5h_X9jESxG0NDJqgN6NmtoRU5xBqu0cMr-XK59U_ROFczFfL74Jc99lsoi5t2PuPXa1QBQ5fobG7a6-QWxvLBiKX_cI7emlew17AcpUe-OALIkzS06pAQ",
    "Agriculture and Agri-Food Canada": "https://m4gfdq.ph.files.1drv.com/y4mUN7EVl0O-pTtIbiCUMr-TkkNQ4g3He2d8TdDop2jaMqp5PFFK2hoWRbMP8OebSj8H1r6EgMkI24sJ_TIeQMhSF1ORHKGVP6iYecSXg_eBwWNNTYsMRYOjrqxfydwN4xKtafOVOobWZlSiDhTW4ND9lRsiXJipemsdrat9u1hThGjv2Rez3JycwiSj8nvxA37TCCTig_U_jy3WCz8AQzTww",
    "Association of Professional Executives of the Public Service of Canada": "https://bn8wag.ph.files.1drv.com/y4m1pk_qSgwC5D33Jf2c719EGr5Woq_gi-qJO51ShDqzi3T63JKPciJ3FTHapoZoyf8KhU6QFUcgnG25K4GX5X7x1JFn8sUR5xdzqnZfa8-Eo_UzoEfX4IF3-RKbnWWjJcBIlawl9Odwh6VmOu8JB2nFE-nmPg8MTalTHlQ-dKdUk1fkMXYg-NvKDVZI6x1pY_C0oUU_onaR36BuCH-uTX4UA",
    "Atlantic Canada Opportunities Agency": "https://yimpmg.ph.files.1drv.com/y4mG6pOinTum4WjgKHrPqt_tZPRUj0s-rty6o1F-TIpzQbWtkmjwi5uNq9UprDhnMD4mdLj9k6JRjhiO3WdSM-zBSf25lIPpIkySX7WnLQDLX3oGjKFBj_EsVSpArBqbp4ZjXYw5kLDNkIkc15xDS-5VCDT_01VTC1VAfAJbksYhblEGeeory_oxMnmcYKFQNGnB5cSgru6aG6ck_nGYelayA",
    "Atlantic Pilotage Authority": "https://vwpokq.ph.files.1drv.com/y4mNzPaH90sSJ-eT_k0BTTleN0U_w8o4jRCIDmCLEETmrOSaP_fZEdHoAsLgU1xMz02PQiqwQ9Pmhm75fut-lg_jEzHga40nrhOFz7NVY_8JNSKv9PctnDf8kpFDesU5iyH0JePCGhZD_kz1rvPlEB2_OLxT5r-TwHOlDzwQqeLXyeXqfTEngfHvwOMcXS08aStS9hAroXrt31gdegkapP64A",
    "Atomic Energy of Canada Limited": "https://bn9muw.ph.files.1drv.com/y4mvFi2XlPONOSMFZZ6bnEtyEh1ri8OxK8VJsF1QDkg7mJ9sP7hAGZVotGmBcp6AIWSUNdv24bYOETE1bPrJoGqqKQz4OuMla6makuZEW3APS-wQnTbIeQGNmBlAAGDZXP8DJP3YyabuSs1lwO9H-GQDBdGt3RELAzoEfaOxLTNnrkdD08ZPisi_Us7I71wzGuEbTHJo8-RS21HTq-KbqlqDg",
    "Canada Agricultural Review Tribunal": "https://yinteq.ph.files.1drv.com/y4m86MBj37ZM6MHV7eQSFHnKOG9IbxB6zWmF0E_Qu4RWlxggUeNZ9KnIkG4EalTNyyzRATsbLGvvkcSZhkAR8LNcidZa54binfEcrn8seMR8QhUFKl3feGpTMaStvGr45K8xrJgMpgi9wEerqLK3HkF_lk4oYBSxgkUndMRkzM2t69QNa7B0sGW4rf0BcULdAhDKEH_VyOXwmBq_mu1DwSENg",
    "Canada Border Services Agency": "https://zzihmg.ph.files.1drv.com/y4mW_Cn6J0qohXKewOhSd4KTGjJkLQA8Nl3Bwj9nbXBUYhSIuDu2O5-7DXuYvITCeR_IpS0HVZEaLanVCjp3hp_pFPnGKdCvX9IIeQ5ngu7tbWhr5hC5c8dvFfdqtAWPJsHBznEcRu9DXWTiN5NNytGHEzqvW-qRlYtw5gJwzT8F9diRVX1JgBU2xOeQpoShgWhvdXDlCpSXPl9EINNg68s1Q",
    "Canada Council for the Arts": "https://m4hpma.ph.files.1drv.com/y4mpug7sKCqx3bgxD_LOYNupIwAdp-rnEDYFOwRLvBcgQdXjeK-zzNSg3WSPqmMwgIK1pc_KQuxhpHoiCeyCqE135Whj_TgDYWKICGSG0LZuPa-o9Yztgb8dMxkDR-Igdzze3WOnNGO9R6GN7b2H17HZjACTXxclodWmHt2HqW-LxjTczOGh8DpPgeLZutA--Atb4JH2G9ZR75kQxLr7fMovA",
    "Canada Economic Development for Quebec Regions": "https://m4hqbq.ph.files.1drv.com/y4mPkQgK3Iedf59ux9zGQ4mJ467f9ztTlJFu-ZfDWhwOyhpNh9_n2LHmdpABu8y9AgjlJSCaQQzKVDRvurHtpYh9hZ7oaGhgF7gqiUK9Z_wSvgmxz57mv5V9W_NU5nIz3eKeYTXyqa672AG4CE6I-eGoV6SgGZsVTcMnsT0lJtmA-YG2NHQiW7Sj7AoLuX9arHQB6Mt6w5y-Mahv6Flre7f4A",
    "Canada Energy Regulator": "https://aa0tva.ph.files.1drv.com/y4mdHyoYJmVSSkrZv-NgWB3XyR3jIFGERS4RctDDngd5NZr8lP56k9Vw71Fwl5QqSV9RjnpPDNQSRmbEDDn5wVa3PBqu03Qykcdym8m9MkIvN_ZBCSVzJhb1TwYbNmNLxnGfdAyrjsICszBK7rByj97rqTcdS9nL41vj-HYfcK3Sl4BID28vMfwK-ZkxrqBsV9Q9rp_NzdGC4eY7Ni6BiRbCA",
    "Canada Industrial Relations Board": "https://vwqzta.ph.files.1drv.com/y4mSEmbiIahPB7RbFMAU08gxYQBnjk960Ce1MfhzWjfNNAZAtbo9Ag4E4Whl2fj-uQ8tKboWwVFyU5ua55ZqjMZWISOri6rKgpws9Fb6xRoG8HZIRozgzMT-_72EfvK_AjfDKBMCXH4ZZVePQda5RD0vMZwLjfNubGwoZr2SU7Fzl_wjn8kZcud1_V_BKpVnadFwqdFNIxP8XNoGkrNs-4ACA",
    "Canada Mortgage and Housing Corporation": "https://bnqgga.ph.files.1drv.com/y4ms3BCEvfwU9IhsRqMujJ4MMrvMdQ2VZ-_xMXZXo4LvoAtsBpNHwc495nM53lH9GD1y_ZIWnwAwQjxjxnMIRrktstmCtEYQH7KVtTkP8AIxgV_UWJu8DieZgKQ89hejtveZNsG87K6kK0fHFA0rJVHb5zixaiTHTM4WAr7p3FZ4RLOv5g6CMvTXtM-aihS1YwW3Rtd_ByjdA-sl58mtMN6Zg",
    "Canada Revenue Agency": "https://aa1c9g.ph.files.1drv.com/y4mesUbABQnGLbWpOifiLou8JuFIjuWfCH9NPodwMAAETD-jp9gZ-VaVYGUSH74HguttQGw9gwUCUXgWndYGTTiEuknpMERjLIL5Mkk7RO9ry-A2cx5vrflnJHmCSTxwIOS8Gyyh0lPuvEFzboN7_3KMWfwmtKmNAF4Uk4fbKmHpdARKq2O2Ql1DLub1ZG1EjDHpxSxCIEbKTQ7TCjb3U0hng",
    "Canada School of Public Service": "https://l6qtyq.ph.files.1drv.com/y4mhPp9CWup68pwS8NeHXlYTe8WzKCpA585vI_Ud1vFFAvorMc5ZsATemYfYGipsGUIt8Cu77x8EW0-jLXDyr8gPzzYniv7KQ2ci11Y9XhovD-t0nFlXpagvJClATX_sk-peG8-NO_X8Y-jW76Rk-61WWEgCEHqTOuUeC14-NvLWhBxs9JUKZGPY8GoI4BhepjYf52JiCbVTzMlE04mPYeSwg",
    "Canadian Air Transport Security Authority": "https://0wp2dg.ph.files.1drv.com/y4mY-rfnbe8vEnT7gqUMxv9GM4RdSCfYu0KrUWpPcswglVcbKMwoitkAhuX3NlJaHKQZxq_hJYD-zFxiWsJUI0WWyAEaT_Hmx3e2knAYIKdm8vxpIxK5QDbk8Zoay_vgQpIYlLXWgQul2GzmywLPUqqBMDzDixj95Y7GO2xVcKZBPpHWmyL6hB9IVRCNKTzO8DCb7vurdCK9GbmZNHLoVtivg",
    "Canadian Centre for Occupational Health and Safety": "https://8n7nca.ph.files.1drv.com/y4mh6yWpebf2xmVTiyhk7WbOXQ3UNEHQH9cT_cesarWIjRjeDhAMGGW9ja36wbet3sg9xTc89ycSwBl5-iOJ5hXm0SryG5E4hvHqQWSSprHeeDTC66ebHWSToRLNHXrB2NgQhQjAB2WNT6RDJCmDcU1yxrnKDcFrApk0gZFdx3VBTQN2v64EMmJExdfgh5CLphpqDh57_vLEcBrBScpnODcrQ",
    "Canadian Centre on Substance Abuse": "https://vwqlwq.ph.files.1drv.com/y4mOEcihaHlHr0Y6bdavzM83lqumdcY75wiKiHETTA_AwbdLA1Xi6YK6p5WqB-o9taHhjq8z2bPysJpeyMNh2KYShit-5FVoBUqzbzEFJ3axkugIqdCVccr94WaPddwK4njdTYlJUuX8mno-A7ciWDI9JEYEckaMcaZcKihn5t2JQBs1xkI_XFCXOigb4bGWcN-vAH2SIueX6dUpcCCL946hg",
    "Canadian Commercial Corporation": "https://aa1d9g.ph.files.1drv.com/y4m1cLGe0c6Vcbwt5l0C-WzhOXPlOo-gXNLSBfCMqqZg2xE4A1ttPxHTkl4Kf0MWrD8H4wL_qUZJS2NtExghLUsPZdImfQOqSDdews0k3X1BEyhG2upV9WG1FPHAq7xCS4SVjJ86HqFwHYgC-DBfMaKHRKH81N4GsvkBe1Z7n4J1Xw0GAM-xI4kY6SWMUJoMYJX9FHzHObUL6XvN05MsTSq6g",
    "Canadian Dairy Commission": "https://vwomzg.ph.files.1drv.com/y4mTb0PPV_2FB0bEDraxitOSNgPOo0RfPVsBYUAKtD72mJ2rHB0UJS3O2bw2SAAyM5WpQdW_AHWRX55Hlan58WCnKp-VU_BNLOsHOPhcc7f_SERsWQXc_jFbnf3MEvni-m_uQWM4L5TXUa592rQ9jCZ4nOSDexyVl8Vot3XyYGvQOdDa0UWxubmDO42CRvWariJLrf4Ilk-XV1YCMK0tkraKw",
    "Canadian Food Inspection Agency": "https://aa1xyw.ph.files.1drv.com/y4m-iuFaeLpuSQE_TD9poGyExNDgPa4FBPVRMoAYOexyJHiCwm47yTscoXNcqfDF_4VeCd30ckU0SOn8MCozIfY5eXvJQr_Q6Y2wpBSRd6eycnNxMNGrpY0Xqz-IiXtxD6yaSG8RCYfsWivOBoYw9B-QjY5juiiekKyfSN6dsY89H7WVdtOrujPB6GOsTYHu6pTmNs2KCvctb6wdp_4ImZ9SA",
    "Canadian Grain Commission": "https://aa2vya.ph.files.1drv.com/y4m13ENRbcAh514vIMaRIAeThfzP5p679hccW8bRFGVyG-keEytOjxAjRxKrSxafrbTfLbXqA9hDD1PUxSsaE_UelAPurZbCiya3e2t3-x1X50S2CE7p_e7UVzUCQYwAWF6Vc-zX3gcCuBfd48e9XumTODRC0LQLGvlcm25i0Dcn8D4xU0ycYfphXt5NLzF8OHPPSGV8ic9lxuaQ7xy8wvv0w",
    "Canadian Heritage": "https://l6quyq.ph.files.1drv.com/y4m8ETYOmmvC2LwIhcILSO4mU7yxL_EbuNgAfe636kIhL5kOUDT58sJC-N3o2ALbHO48Z9oNFtd-TnJw9CGANv19z-NWoiDRyy5uJoQmOdhBnOncC1FzNvfbUkj9xTICrKc3iEFVEr--PzMXZ7lHzKgmrGwuKSiR_eibYoh00ULvYMEKrjz7FOWaFB7vgrIhM9pCGGWjl_hqkrdb9VR-McpUQ",
    "Canadian Human Rights Commission": "https://yiovba.ph.files.1drv.com/y4m75jEogM2Hc6lvgCfvHg-lgPO2PlKQiHhPD_aCzboqWlmSeIY-QNSj9UTWDwxNwvTpLLalijapsgrdqGDiH7wHOme-hHihFZrLXF46Uo6WjT2mBtycbSDTHX4iP_oU5Roii9UCAN2aPcJvDHoZOEKwE4KZwivEcOf0jVr8dGenlDq5UtGREhxyYFb2ec9tIAtdhhkGLET5r70pEnGD-QNDQ",
    "Canadian Human Rights Tribunal": "https://zzjqpa.ph.files.1drv.com/y4mZbM3kPEUALyivzZlERHT_o6Cp08qkKY-lM_2uoV6-x0WL9mZossa2yDiDiQ7uWEQAd5Mhga5MFxXE8SRZB4mafn4zTqB6ylgO7WW_bzHAkV8zUiuo_5m_xk6n0KkNkWhTCfVZwj4YbiZYxN_0KSn65oKb1bU5aCI9lg_bWxjUNOo2tVvgNuMJkRaUUapVWCdLWa2pfuhdoE1mmJ5ljtUlQ",
    "Canadian Institutes of Health Research": "https://bnqnxw.ph.files.1drv.com/y4mOpluHPkGP4FgHSquzQqVqMBRV-iLs4VBOP_JHTNFR2PDzbYHD_9Yo1BKdgmrZp201tEggqkCcefHazWRfZfEsJc1V5IUqa51F6pWPVuD0iDamWPtJyJBBLrg1My1e4kcdT5QB4MITjg22r5uObXIEwaKukFHj4gwmW00fkBZeZsPsOppRsJXo7whXXjXh3Prqg7TletoZ2IHQ3XJiAHQ2A",
    "Canadian Intergovernmental Conference Secretariat": "https://m4gmva.ph.files.1drv.com/y4mB41bu_0cFC7fDRBRer30ub50zq2f3aFqHM0mFGLfdBYeMLQ182ki3eh-88S40h4KWKW0n0u1SQ5eGdOsg3-1tNb9BzE-pvi-lTywAA-6da9GsPH-yUISxNeBSgh6Qn6sgrN2V6ywyvTno3ycVENeNvsm4GqTHZ-lASPBIT1y4NiZcM-bI-uwWa4e8B8V9c5PX83re6pwsnTQ-YEipkribA",
    "Canadian International Trade Tribunal": "https://nvyrsa.ph.files.1drv.com/y4mRibhPRYWlChA7ARHeFvHt-zIG_lNjPEpVkH1QWkEt14RcwEkArLiJhpd9lpeIU714JGZuHt5R51hM_9lX8097kVl_qDzJkxcOx_-0bH5cRtakjvkx9munhXmfOYaKYH3HyLVdgamlvy4ZSyTauIAlqQ1LCXgcXPOzFQ5ueUY3_xo0pFxI3wcw9DdTWSsgrDKcilRK1onyKa4k2rKFnpWew",
    "Canadian Judicial Council": "https://m4fkpq.ph.files.1drv.com/y4m9RTPPE8u_9BtChbE52KAo-HIrqoCYNjtnLpmzAV-160Nzd_MHgWaB1T5_kA7eZW-jwZuCPxtDmzcFUMJRIKijlS4SzDp8UP7zneAi8kbKcCdOZCLXJ5vFxPaD25mDSwDJ7bCUqpQVeRDfeZZ-AyNsLZii19vVmRN0quxoL4mj-X9kkCi5Y-p8bOXqZWdJNGOK0_9tT6ufVDHwl3liQGSOA",
    "Canadian Museum for Human Rights": "https://m4fvaw.ph.files.1drv.com/y4mxjKW2ecExX-vwBd-s0djat-W0TWQJzHrTz0WpjFA3m1BsJ3o5pkcbelaCCp_iDTIb2YiVsj02qKeKM0Cba_5ctYFuqKAVJ5M2akRrvrCVqvh1lwJbOtEBgUpHJx3Fd2ODpmmhELIPCV-13tCxtCrgMlD7Rg_CA6rguWOLEQTLW_Bcranke13dhg7KOablq2ehqAc_LhJGqsoyoSbEXJwew",
    "Canadian Museum of History": "https://aa1jpq.ph.files.1drv.com/y4m4EyVVyic0rh2eHHJDb-YlSyzWiG8KGQwKH3ruguup9IlBkZuX-lKhHbFqacoGRoRD93QXHJig878xM454zjl01ZPGUUwItdZzINylQlyYyhMWQrfdWBOCBQ-qjps-PLA2kGz3W-TBep1ETHwjQTnzwy4qL4kHwmucdNRkFHEfu1zuUo-osCTHqs6F9GA7D7avHjFcJL_T6ExHzpyqoChqg",
    "Canadian Museum of Nature": "https://aa143w.ph.files.1drv.com/y4mjulEUBHbBbuavm6yOPJUAmAkdPJXEkDRkZPy12cJsd-Km_OcrxsrnevDptXQrulaE1A9nokzZIKUKoT1Mw7jW5Jcuyvg2T6QHHZV17mleqilLxtZ10GcghheIH3pqEvK4nxZi5vEHIc99CDVp3W8gKUnpXr32SP8mfF8os0f0_FmwtGk3xKVt1SaIN5JlxbZCfxMr90wWVFrFYiTkw0DkA",
    "Canadian Northern Economic Development Agency": "https://yinfgw.ph.files.1drv.com/y4mth1v32hXOlgsytMI93HuRYx1CfBjMd7MP2-VhdF4kCZ_C-uhCtqe8QUY8wrAF-s2m9z2EzUdjFmbmEVSVBE6rSQM1QS1VUHitFWInd-HNqOdS42xR-nYAT97xhhFXKqqL3E_sUeDjDmLK3zfQIUsYSr3746hkchLaP5wszGMvDmdfJSfQ6Wo_48mCh0ZGkEYHT2rAlrPZoK2dX7bt2pnSg",
    "Canadian Nuclear Safety Commission": "https://nvaxgg.ph.files.1drv.com/y4mXFQkLtwuKpkPgCBtIKeVTAk0af5_sAm9mkK2qxvUNlt-2icK8AmDxzioxuYKpE0S0DpSYhXtSYdiTGIAsBnF5QHTvqCCrLQRbHrKBod7fS6QW7Jol01LxNt0atY3NaQ_g0E78CKbiVHkS1o-ojG19x9lRIY25bs_yKZGlzJrJt9VHBpjC36p_k2PQOUq1ZLcBOsOZRLjshv7POB5Ah4v9w",
    "Canadian Radio-television and Telecommunications Commission": "https://l6pc9w.ph.files.1drv.com/y4mLP-FAtB9D1faJxp5lPxrvKnFkgqyeEtwWwsE-pOsQ0BvkCe4iaH4AkKyQblSjItoNW13-fp4LUYKl_teL2fR3F6vsThQXTuwMtG6nt5C_7bZC4P0iKfOXqkJE0CqowxI-kDVApfjCZODIIDIpedtK7qPEJ0ckW7f9XOp4L24OPD9gkv-oBIiB6NcSiLJ4eOvcYpzqwBwCbMEG_gttl3kxQ",
    "Canadian Security Intelligence Service": "https://vwrivg.ph.files.1drv.com/y4mbGlteoeIledaomVZaGp7eTs25miVt72brvq1_nN4ORwIEebmgL5pgyvLG2CBfvsODlseeOhpp6jgxNtQJGHD4cZCIrFWU4S8x189KNtit1HMG97nLJQm4_c2MjaWE0tIsLM2oNn_l1AFTpWb-rmBh6HROkgw54kD07rW7LCLYTl5qhwnCfbHNGXKx7NEyGperyfhw-6uujhBOJ6NFduMKA",
    "Canadian Space Agency": "https://zzggjg.ph.files.1drv.com/y4mA_NSumY4x_IpNYUSTiefC0PdEnGI-qghX4eDnnwovboSxRtDxqwQriM-LFZOXSC6xf7_WyrDXN0bCzAqPVdlOH17n2KLJIvreUuYLtBdU-UKGvM5kAxAU72fUjXBrJ7o7lZkLytTnsWyoVIZiwtHXaeqrbE-QawVVckRf60F8LLuYBZ4FcRvX3hGcg1V2qgIHwbbdMCQ1oUC94wXcAJVBQ",
    "Canadian Tourism Commission": "https://8n4kbg.ph.files.1drv.com/y4mmhuU5tlfJz1dWWcOQWYzyMhMKMV0nnzx_p3o2GCpf27rwi-Feyby9OeN-sBFMFkW0SzX8eZqZNMyXVwrsS-OU1iAZVmFAinslVJDXGprSu7i55qwAGblTvl11uxmz44iL2VBoOtbQeKFrVfoorfLuN4AkWJMWVuA1DYnl_dei9KVGRKc2uTGycwYFT6XASk2MTUh6sTnxSHhzWA6QCF6SA",
    "Canadian Transportation Agency": "https://vwph4g.ph.files.1drv.com/y4mumy2BMOKLis5UFY1WeRMAhaP7J-RIOKmb5kNPhSW2IxAem24SecM_IK85ISmcLoLd49Eoqo3D0hVJr-ej0k4_Ao_HAZa-iakeRkuj_Lr70SglCX-JP6lheBFbMZ6Ko5yXhUIFQeusqG6-hZkkQCzAWrrvn7RY_SoGs85Zz5uRi_QJzsblt5-ma5J-PfGXVjqhI1JvXd0krAxRVO1cck5lw",
    "Civilian Review and Complaints Commission for the RCMP": "https://zzhssq.ph.files.1drv.com/y4mW3jzTFxDjfCjkY-j8SkKakk3jthPwYsfgT7jkvp5QCLCJrylpN5I9y5hkceXQDs8SbuYTip2XHOU3toYVaJXXmGTMnpbzPO9dxwVQlrCf9guV5GIdmrKGSzsKO1nVl8w7TdY2n53cJa68o29RhOKYcq4AGDqHa__F39XPuZ9Rnq8wU8VAQt24F-j487yJdUbyNPe5Dy-kc24ps6ieg9bCA",
    "Communications Security Establishment Canada": "https://l68dba.ph.files.1drv.com/y4mudqFH7Jcvdvt0J9c1UXD4YmSXGmFslWOUX3AYs7yQ5rshN7bmlha6iU3luHs2zNdE5Zcj2jGsftJmytPfsrR6kdB9vPB4At2Zq7vxjTBmkdW6PvCzhBa08ciC_sQnhPZQ31edwsrGNK6WCavtHoFDyNXm1vwq9qe8-0tUTjcpmkBa5TwrhiiVLkd9M4yComjShFaAB-cVbpyvnNPxOFQkQ",
    "Copyright Board Canada": "https://aa3lsq.ph.files.1drv.com/y4m6JuKe6-_KLw9jNOv762NH88ImL5rB2lIB_QInHewQYz_noBnLG2y7owdJZ_MiAgKe4d9fjNkG163kMIPsSv48x-sd3lLVC8mdB-c8Kk2nofdFq9zcshekKTV_M_RPSbAnf2ZftMQJjWz1VIPWcQUCji1dTI1NcNaarvEJ4qHyPPGmAkX4gIqwpTIl2L6x9fooTGwHZsmkyHWQB04mwbZcQ",
    "Correctional Service Canada": "https://0wqlsa.ph.files.1drv.com/y4mrcNUVqGJCWTdcD9xOGpdzPUVq_Jkye_WyQqeCHgo_kFB2fQ3UnzU_JGZpOKkG2FG4VweSOq3mYmmG20Q3KwWfutsMRiMf1hYBAtjyc6nXeRghDsjx6OUTj25JWNwN_chVLijFXoaPMIZGx5Ug5qcG6lEyzUR1jgjGc76ToMQYCJpLNIYHY7PrPiTkYVW9r10jlzw2PMeqvnqm9UjAPCT0A",
    "Court Martial Appeal Court of Canada": "https://l6qngg.ph.files.1drv.com/y4maEyiBBgcedc6b050o6afeSnv-CIIkMrJDxdUn9FHp95B-qm1d_fi4Y18Fyi9iLl3PLAWGgk8vOg3Leu_0TDweJXecUjE80l_xJtzLwFIsFGkE2rUj4MVe_MbL-6eDaH3xX58X0ao9dV2TxlAbXUltc7_kEtlZyqdkcUH47lz4p33s7K30WpGJKplaLeKyS43azOGN8ggfE0uylYTVpU4AQ",
    "Courts Administration Service": "https://nvzhmq.ph.files.1drv.com/y4mtzBUVZL8F7jyXSeR5k1IxqjCWYE8JeQfWS7Bo0YFTH5DqDkpORsAvlDq14dbMaNWk9bBGcav2RZSTlpxyLFgg01v62JRiIDd6QA1JfG9kEAiZAJzLjzYvV_5lsOWHNsGzdnmDS5ggkCkTxc40pcT6lVFJZBKl3TfcWLxxg8-0VNcnEkivjNvE8TNCQh5JK0m8soXSB8ayfYbZ3-O2NyQ4g",
    "Crown-Indigenous Relations and Northern Affairs Canada": "https://zzg9dw.ph.files.1drv.com/y4mH_Qot0EwsW4n8nKDBepaEjib7nB9qBmGVn94S1JW1yr-oiPALa0drXWhxk4PKM40kUob2Xve6aZl4Iyy-XMuNJe_F3Xy5p17zAZ0eb2Mn5Zm8dvnkXDIoYjrkuB-s_jozpBDKKRs8Px1gDbJVfy2G33jFcp0eoKwZ1qWZFyaoWHiDNbl3B6z_N9RWi2TZR4cPl908tqA2Ar80Z1GptgUzg",
    "Defence Construction Canada": "https://l6pipg.ph.files.1drv.com/y4mrUn75cfCEBk6-d7vsOVmvbUS_LW34wOvmzFsd1iL29rPR6NxaRVyeVlQKGlri5veTLCnrQNJxddy_s17uEWVWhuD7QJ5SAhcFKcClmY22XP12IuLgNb5FIrMXEOTvkFuXgCGK0L87snoZZ3rAcFU8D0Pf3uZlPBiX1wlHQ3l1C-ioV8-osDZr10mGlJVjv2QuvDw-urbd0UGs8mUPXgflA",
    "Deputy Prime Minister and Minister of Finance": "https://bn8dsq.ph.files.1drv.com/y4mt_GhCj0G7q_Q6rQPlKKG9KyOtezvjVCT7Xe2jfwu7wMefwIQHqmxPF-e9KVk5PGoH-esLYmXoVjCdDb8q9rE8PvuYiXnY5XqUCGeDvIDMYlRnjoMxADMhlpKVheBVloerit9IzmzrY93Zyr_hok-D4qvcDJKQywzMYMuLOgT8ks_WoqjbNnePANtOChdZc6xg7lz6HrwYgqdVyb5JCSKGQ",
    "Employment and Social Development Canada": "https://nvyssa.ph.files.1drv.com/y4mxBfCXV1XlmIR_Mjr4Qpey-2DYJsAE4i4wtSIVYARnUmY_FandUVrkLcTCrzlJfMif0cwqJqBsWFesnaFYBdr5MmwZEsi_Pfrb0WWec8xKlKue72I5K4X1Y9QcfTYa7bGjLX4Ut4BAVqMQOb2bdAvyJP1ljQ3Q8_8ln-sXVoyRnigU-w7cRUuz97CAacu3MlDPmqXUowRddruJYrfHfxEEA",
    "Environment and Climate Change Canada": "https://yipedg.ph.files.1drv.com/y4mv4GYdgaqTLUspEuZgJKyEVl4ERX27PWgQ44ozahTEJRc4Rsrhp5HiETgOiO3uo-tiZNchVO7TDyvVz_1IWxqEQLKUTPqHE7xJS_8PVyiwRLyhBcAQpJT9e0tNUj1P0xII9MownfOeP6T2IEtK96DVyUYq7oDm95gwbczG7AA7thLTnUBQVvXO3zzumyo6btEqLuvkk_HW5QRTwayf2eGDg",
    "Farm Products Council of Canada": "https://yimjhg.ph.files.1drv.com/y4mWttLmE0aNEa7VxnCT1rMragCTdWmrk-GXKhQa8J9tx91XkmXAtWGyGfJq-cagSLMD0XSGu2H6pwNkwPc2G9w9nFlMzb9e0O7zhgKMQMTnkeE_OCwCicKVoApB5l1aT7S_UJWeWX-h7ulywfMUdIt_JLfGlosORQPOHoJGnziG3HDgGuSTUpO1JCM9uHkfU5sd8Evo3IyYcpe9LvfsplBBA",
    "Federal Court of Appeal": "https://m4g79g.ph.files.1drv.com/y4m4eECDpghu1CUooG875JTJ8MbJgaofuAKcxW0L-d7e-e8UUhWYz_voxkvRdmEPPh5otqJ0tGEAbaBX62r43wFzL36_G-cpSmFT_acttBxgefLZEwgRd7PTMj0863LoHMaxYuSHQXD-6wVatCQ3bvhb5EOr2MKtePiNVuVfeur7V2u7-eFGlDvoD1XIM5W6ntgGeMTRkUlfz9sbjSVx66WKQ",
    "Federal Court": "https://zzjxgw.ph.files.1drv.com/y4mT-2FaUccmiz0I-x9Mdl52fQDVL5JhrunCexSSusW-ukxb3qtrVNcQLVU6NNv1DIve3SbYruk8OE0EN9T5QncJ1eDYEcXu4kvDI61-uvEYF8kRUIgphZxCSqnsiYJVY7mA5RdlnFyHFVE2QDim5xOzP-1FP75GUQBIMr41-NISnvy5bckJ7J_ZuIYt-kj10dLJDcGb0106oLZroQP8nwaOw",
    "Federal Economic Development Agency for Northern Ontario": "https://aa2uya.ph.files.1drv.com/y4mb09xYJFktbmEsHJiJ_4VQ-AGpA2CTJJBKy1T8Dmfj7RsT89gHG6JwUW_xldJgatHLgsjMYaztpbUqMtDlMbMJEnH9hepdiCmkG0X-CwmPf3vbmqic-n-5eEte4li3OeMOXL2KqZVSdf4l4CkrUW4smcInipVgT3TBFlKqBD0JsgTWW3XppnfcZ9080ppxctFeBChapX3EKvSeOGxp1nHeA",
    "Federal Economic Development Agency for Southern Ontario": "https://zzivka.ph.files.1drv.com/y4msrZ25uSYq4YlAxma-31rgBhEGExAsG15Ihmbyc5sxJZlg9RJluDxjMD9H4Gn9ZJyWlG7GCjPXlJHvPdida2oNwsbMuQYgc3ogz6yuyOhP02Hfz2GuoirGEFjAXjLCgcDul_G1mwN6w6zSYVfjErE7g-ZcYFyulQexPNcxlOwcG8Yp4Zwd8_ZQ9-92TYM_ajXkX_Ijjxoadt6CcxvzRSQ2g",
    "Federal Public Sector Labour Relations and Employment Board": "https://8n71yw.ph.files.1drv.com/y4mmeDwrYl6sV_f3BqAzbRCpLy34GQvBXiW7d4yd2lxWXdkVdnqRktTNIs-FfJ3f1L5p72QTjiVSvngyk3O6Z_v4qtZIGBGFDMr-XUbUAmMBLRUkiPSs3RxgVqujEZoCEhS7oI3auaYpvMQnJ18RsFJFMHHNVaww6pPzGKreS_4vOH896Nat9tV5KxfjUkaZS2n-nD1BIg_x6-FgESMROTE_Q",
    "Finance Canada": "https://m4hw3w.ph.files.1drv.com/y4mOxHtAg_YHObWC4tBvB1zWXCGRBYBP6qeWFyhgpE4uoaHDY0XX85S1YgUn7GVOkebcEO1QjB3YEOhiFoZ4Fiy51fG8awjx9JEGtNrPeH56xgGfyYOPNcZ7qESNx-V0UIakWpOYgsFn4mW-mOg5R-9lXrvKt1FvHNP7yIHIATPax_Zn4epvW4_PunlANFphjgCrVOIBmt8X7Zx-zMbOuPaLg",
    "Financial Consumer Agency of Canada": "https://nvb9dq.ph.files.1drv.com/y4myHoL0XbiEteCwB5Gr-w_mwrSSke3yg2T9LS08kpxnGKieNLVj13BrxlF4a5kZjH2_S1dFrsjuHlKA6Pc5O7ooa3yRicRKjF6YDzYwGaEQB2ZF1R0QYH-0WrsEuc65SUx4pZ0kDARQBZKWnWxeC92wCC3AhxTLkzgV3lvCNohUSQu15w_yQkQ3NUnihfYNbn0vGrWD2MsuZZl50qD4gnwdg",
    "Financial Transactions and Reports Analysis Centre of Canada": "https://l6qgbg.ph.files.1drv.com/y4m1TwqzMJ5G5v1qDgWHKE0qm1-4EwHfjMtMv8187Pze0mAbfoYV1UVBCj69hjTQY284Dces5g3FRUtY1EAhM2uLrHK-91-H9y8J-DAgEfnR80YwTiuPs1vmMKoezDOQRkQ5oAKlUqPDxvfZtAGYYRUiRoCyPnQWs9bUVbT2cRHfDARsEdknfiFC49cgIxaWlX1Gm5Tap-JS5jSatlt6kAyDg",
    "Fisheries and Oceans Canada": "https://zzghjg.ph.files.1drv.com/y4mAiOvNQmWIMRWxvvcOMU_UOxkJCf3KPTaauBfFD4_EbkSu8ZcyQsTBHZDqirAO38CivwpHMITpi1LyW5dJjpf3skAG46H5kD_cIDVXM9XKeri6GIJS6gevZPxZmBsOl4tJhm5wYyKSUloly_uBOOJQP61A1QbepwQ5DYPyALBrUppFrHQkCXVpjYn6ptSvdV45hq_75kENIYhIyV84iwzWw",
    "Global Affairs Canada": "https://nvzimq.ph.files.1drv.com/y4mkzrvjr3JeMmpX_ljt_t6U6KYy4E-RyU3-fFdzTyoPQb_xFboeAvmA0dJtEVKZUixYw0tavhVGXI_GIA4HmEUxiBIgDKzHctfXgqWfRJiNihtRbNf7PEluWI8G_J5NJkJGRq85OFmTWCTgOr3TQxoylw19SPsCefbAafhrZwVk_5j1DtUwz5L4epCnBe8lcdgPPySt8H7kDnza71jFqizNQ",
    "Governor General": "https://0wruug.ph.files.1drv.com/y4mteQMUFXHXYLHo2MhBt4gzzrK1PB1RWy_eQyKWDqrBUq-dA57V-OW90zysiOJbvw7b2BTzSLHRNQIcolTGXNQ6Jc5mduJG3zScTXCIWq7R5ES1yw2QWbLdVJ6lq5srl8qZG-4S4c5vQS0nacCvyuqCVi8QinjQ6e2K4FVLFqnx6KIT-ELMz8x18QEcdLjtCiB13QlbjkyAUA7L6vxBGFXyQ",
    "govTree": "https://0wokpa.ph.files.1drv.com/y4mysBxy5J-u4r7LJjD8E2z2pqb5EY4vhInTwnROqXXInKIpGOlgSQIkyfUSU07vQtOe0xst-acrG31qEMlmtWp6FTnlpcmCYcNqFvag9y7RM7a3dYn9DNJNNYrxqOVEiCN2QQ_EQf5uEdirS7ft2vhGedR7k3G3n5_IajwqZplPwlbWCcXgnnt7xoVnIGMRYKotkAL1KtY3MpBYBitwkcJDw",
    "Health Canada": "https://nvbhja.ph.files.1drv.com/y4mg3T8x9x4TBvTk_OQudiWO-btQ9o-_olhOYwLr0PVr0NZihiPuZe9P-wbwkip-UmdPdolci-HCKbcJ2UHkbgW-YW6mSd7BwjWT5O8btUmPe55VBf9_Gaol8qJmS5nOyj0FDT35_xvimN9dwBPYT38ikZpIVbJXC8ItFhYTPLy_PKTiiIp31d2KTTqqBcnIhmV-s3mgn5R4_Pm_Wad_BfUaQ",
    "House of Commons": "https://aa28vg.ph.files.1drv.com/y4mBF1FWtMYi45il-j4yOiWEihgaFwcDIIn8EoVYzUc8OS3yIen9QFAPLHOm3YD9ZccYnSd7yRFatWXhL_attVXQsL1huh3vC4Gu6kNGRlGqw1j5amWhmlWV5iyecaGWbz02oS3t7nYJyp_ircqzodhBh-VumNmJxGn_y99OcNgxzSCUG5QcolQE0L4FbxFn4Ohk4XwO47KGBvtN1YDo7CoZg",
    "Immigration and Refugee Board of Canada": "https://8n4yqa.ph.files.1drv.com/y4m7TS0zcGEZOWRfEuioH7wYyAxOqq3J1mjLAlnVTKL_UrGTHtZfZh90VHNr9PUwLuYI7aYmfCviTRfxS5wEj4zWuDx4qgcmi48pbH0shm_EYlwH1T1NZR_JxyWKVrihQ5gvqHV0dNRFlZGRDoqfYr1zYm0OhTT5LWB1b4Z6pO2CsS28PMVaPO9INQlVzlTN7Bxyit9KwiHErpsCGAcXoiMIg",
    "Immigration, Refugees and Citizenship Canada": "https://m4hx3w.ph.files.1drv.com/y4mkZ-4V1fORATHhCUWhjSTyeXJhOg-T67LquFgV1uPZJtkXGbc-gFDqHnpfhtOWp0FrJyVtqz4u80wM2Ku6WHOqgDaKsVHydCjqkPx3KEbWPzPdlm3UA13Ts6tm29FrjiklDZXQkmy5GtGykMgAhjfEXu4uX8w3V2_TVEY9TQFoNYu57wvLEsoj1ryy3htQWpf-TCPNr1msGCyGuYcbx72Mg",
    "Impact Assessment Agency of Canada": "https://zzhrsq.ph.files.1drv.com/y4maMASnFc8RJUCmEj649I0wh0UfCCoSwrK5wkMlP9o37otGG-ZY54HaXCo3Q0m3gTBDVirE7Ar0pR45nEInbrZSFfgq9Gy65TWgNRLbm2eoiNMgqExcDMcQbfLxhGal0nkfJ4q_mPZzlqS0CS6TQgmC2MLVDxGapg7XsiCBd9lZDWHis7dwVvimi2MzVfV3LOF24m4tak85um2-NqTn4hWzg",
    "Indigenous Services Canada": "https://zzg2ya.ph.files.1drv.com/y4mFNrS42qdUCaBsl96_1_gaxVnLMi8oMTOAEc5-FyqeMIhk8xEPoLQc2_lYaBIf5nAK-591b8rHS2Pl3tdnf3puDqJMTvMFu8LTR-l-UL-jspUjNTM7CRkpltmYFoWadhczd-_zAxFW_wUoYiQbNF3FQnOFBDd4QBjchU_Vdh8VoJx_Yo0-ro4BG3pR8We9Ooe5h7bpAO--pcz6GL7xb_BzA",
    "Infrastructure Canada": "https://zzguta.ph.files.1drv.com/y4mU4sy7UirMHMGsZoz1e2EbHsg2m6s3gh07S3uOuif5zRYwsPr2VUTELveb7yCUFlFDmxRrbpP0V7Qkv-7uGfz7GdBwD3-lkAIux9-wogUakAlXJm1dt-fMjx2mCMAP8m9zLQDl5XLXL56xhRtys7HoCME0poVFslX4bk3wGrvpyhEQ7JAk36l6_5c_lQ3bkuBQgYdh-L4yVd2YggSCgovqw",
    "Ingenium": "https://l6qmgg.ph.files.1drv.com/y4mDhYoxV9Oa8lo80s_i8cJohc5AxRDUBPbMCRzO38ZOq7m5-InAU6Znyejn8GUNrcxG50S2yUpH5qaT1gTmTokeKYinuheI8QEIW2Tm_aE8VGi1DuF9Ptmav5MoM7rYAuX7hXSU1l0ICcW3li-qO7gu4p2eyVgpBXJmQn1a8i9Ib8WhrC1wAestdjqNojwp0v4phboZbGwP2sWETQ_MvU-og",
    "Innovation, Science and Economic Development Canada": "https://nvylna.ph.files.1drv.com/y4mw1chIM0iCOg6lOuiTleRx286fi4GcLVuOwEtVjx4b7MLGIRUXHLzIKQLWVRK9wsK9Gox7RnJAwcJ1_70zs_m1rwUpUaOD1nHpJJPzYPq6ey-cO0Xl3UVsvVYmc7sfvL-rch7Azdy7iOsGyt7sugrKnLEPCn1YAi7tKoQ2rPuoQjzpwVuhBAippfdr_FB3LSvUSEE_H9R76hctSrbQIQLJQ",
    "International Development Research Centre": "https://l69tvq.ph.files.1drv.com/y4mgXjDjYASCG0gq5LfUIRwLoPvTUfIULCVpG3B9LJuazvDDQFNwk_Tt4FhLSheNcQq_XN4ExEumlFLAtWwamyfIIAPH5wdwpibmexOJn958-3WYR5XvzMsZpLPJbLYMMFh8lipR3V4ycPy0Iu2AjSf6arBYmD4pT6_IdfeFSHQxBU7qiZ48FAVPtD-QGAHrszKzvU5B2SGzRvzOPaoj07UBw",
    "International Joint Commission": "https://yimw4q.ph.files.1drv.com/y4mNvO0dR0YG-kGzh76xdIDsNjom3r5gOH4ifepMzzLHfR2MoM9vmrwq-VPViefttjC-eUdk6-e45_H3xz3K8-B8R1FpsnUgH-WNOZjD3_Hjxlloih5tes_xl-FKII3i32caEJAX06qoGYkg5bmzQfMhxtmPnFpKpCCDUqmzVaKJ2arlb3dj8qkWdARnhcD-LiJJuRa98S1TjaC-65cBizQog",
    "Justice Canada": "https://yinueq.ph.files.1drv.com/y4msx3BQ17ys5f8YKD6bhDdVA-xqsXZB-dcYWj-p_Qmv3QCqes3FwPoM-1EDqVYostLhNR4VggMuYnYG7JZPf5jCmuH06yscYgPziisIHSvw8uGNkLwrqKAVjh4ics7IjgbZfal8hjgDasVddWey97UBuRk1tFVmPMsRslFjm2ioPBt_bltRkr5Xp3sC5XcpL2cGlkpEuWiVoEI8fPBfrmhMw",
    "King's Privy Council for Canada and Emergency Preparedness": "https://aa1qjg.ph.files.1drv.com/y4mCB2PLdDJpnNfpwUc7h6WtN1zqw8HoG7j_pLBR5B0P91ZAwIDNL8IB1sWcK9RQ_Oyo14bfNYEFamMQOKeakV4PbKJF8iQbWP9EI3UEin1-BbQEGzaAdlaIbRty5Eni3BqmQ-tZLkxB-l2DC8j5ZlRjK0I5AgUlGcFvXfgwaJENN0xZsWZayiF98QMrmg4CoLC4SKUifo_7UH2VuUvdow3Hg",
    "Laurentian Pilotage Authority Canada": "https://zzg1ya.ph.files.1drv.com/y4mNp_oLrpgA2Tk4QC0wwoQqS4yZEshtXX8Zc-fpLrI8eCMpHEIVlUXMqFotkWUBlP_nAYjI0fzBnZoaCv0SEj31-pYiGsZu2rGFkaOY5Xm5Zlz1RmM3QRPkKsk-rIfqBwWz-iAYqfsT1VlDrqQJ4nS4Kzu-3Yq6qwyehw-icn3CQqW9EBg-HWLnrE0IGo3FFUtDxdlZWNnrOHyMirH9Q2DQA",
    "Library and Archives Canada": "https://bnpcpa.ph.files.1drv.com/y4mpKJjjlwTp9i3fheN_mz2sgxwlfwY2FYwq5Psdux7bz56HFa46u7_OcoeRAylXq0nGxIHXVZDzaCXPlDWyt1maWF2uJg_xbFRQvIUBb9PiJ8xe6h6aNqEGV51QyKFkry8HcnmLvskXhjs1TGYiUcnoIm3N6sjESDW580xK4Et971_CgBwfRD71HcEtce-7piSy5PPUBB07M2Prk87wVo1sA",
    "Library of Parliament": "https://aa0uva.ph.files.1drv.com/y4mf9OiNY6_MILPnKCncbkJp6-foT_vAPq7mtIj93dCFzGgfm0B0veHPPZ6tRf3NcovVh5veImVTW6rOOwBv3aJYb9gTZ-WYL7iy1vQLfYhtfqoqVg9T2xVEv2oXde6FHq1PUXb1nATLHWyY1T45qMNgHvPcHK0oSIaonNfUauf3OE1J1e4q0fFPr_CqXZK9tRutKUSvbXcilJshnA7oLoRTA",
    "Military Grievances External Review Committee": "https://m4gedq.ph.files.1drv.com/y4mVbitoHxDj1RGVNv-ktu9jXaKZvHqAe7mO7CU0CmrfVFG_1epGRy2a5_HOtaJFitiZGCb3Slpli_XbAY3af5LB3N6m_LOgAsqA1SqjUw5o1BtuIljJTRNTIa5obJ4pGh1wumqq2Ht0hsvU0YbsvspwxvtdhWXfNBP-XjIcg5THYnUllhTFB192jl7FT5FtuPoesrSeF4NdWpv7UFe7CCQiQ",
    "Military Police Complaints Commission of Canada": "https://zziimg.ph.files.1drv.com/y4mA65SD2JqHCBsD3AE9vLZrvAEJwRwZEkGzOJytXOJoa7IcXWGQD-iktbsuhRAus63W3SVBLZ5qQhTyhx9hTykqA_-muc3KtoBiUagV1maja1cz6s38MTVkXfnF7ZSeyIKm1lNJgksgGhNE-ulg3xUod7xhdVnyFwjstA_nQUwTjZdN_CwF5zCSKQGQklWCV8YFZ3jw1gf3NhzdofCzhv8vg",
    "National Arts Centre": "https://8n5avw.ph.files.1drv.com/y4mvkdno4wdFl2cqVdBEnDaaIgzTeU1T4LiTUwCt5-jncj9M-t2bR0ogLA-plpzxlXMVviwMgKrcsDprLeY-wYpREAV0SR8VzKWb6cCVV-aS4HQlWUWfFInNd10MfsVSMx1q4UEUDVy7vjeTI8gxOe8DQhssy3oiwyjyB2SnfSoSLRmVZ6Q0Sf8h_ddHeQ3dEhXthOxy_3lvaCE4uEqFaUDPg",
    "National Capital Commission": "https://l69svq.ph.files.1drv.com/y4mvJIPwsJB_XtI8LSn0CffBjK4Bhp2OAeC2rJYPtSeMQzz2gc710rdYvEE0UkJskXy0LXwfaFRenLW2MaToXdfAwUEXUE4IqBQ-78GE_cECAciWz90on5DIIPPCPkkAVyiSk-DngHyxY1rX0G49oTrXpyY0QwDug8G9aKbwA22BGU7jfktn3tuuhHy3-ckg8eXyr7YqjABKaesH3eAVUtZcA",
    "National Defence": "https://l6p34a.ph.files.1drv.com/y4mfcKt39HOrn6vN_DJdqClVcwkQJsBzyKr7ddbeogKyy9uay0qdhqRzzOWjg-4dWgoX_D75GaCzGwTeetjN2g-q6Woiz4uX5xd6tkYgnq245zyFvrvkdvoM_cNj-UIJtAoX06a1rm7cte9jOcyD7ENn1NrKBpmUIKTTj3ixmX3MBNrw6KE-4mZee8LntrK43CUGX9ZBa6AGFBnXdBKw6U8EQ",
    "National Film Board of Canada": "https://zzgvta.ph.files.1drv.com/y4mUUfp2_rzZdA7UAB0VdS6-DFFnCEKLR9l-MCIVTiuHlZMDnAL0fl4oAgZmz5LUDBH4oFIsaJqS2_PmZSIDW2mMfW6T2CRzp2H3Jl_azVwVnzKCitWbA0i7adMTF2KuyVFblL9YJKcCmNmO36uU5gvTjEJy_XV8iJ0n_QPr42sv6aFRv7yXGWfdRwx9_Ep9mcGjB8l9ZaQWul7QYti3hWmRQ",
    "National Research Council Canada": "https://zzjrpa.ph.files.1drv.com/y4mL9fa288xgU4e1drHB0zAQq9UMf3YQLlGjSZHQD_soyja6gIsatobTAmFqffqqiHJk6uFRfI7qDPyVjHh_Dluadkd8HUipUmBkq4yveDPE-cv9UqficHKOpa4rgHNU_C_mvSzGTBftXODqxVKt_TNkbCGYc9uR_-IbFS95TBuZ4mAHF6XQATudpVN2bFEtXpK0T_b92ni5mjuxumbit8VVw",
    "Natural Resources Canada": "https://bn979q.ph.files.1drv.com/y4mK3sh_zqLFZ5ZmUfPJe0F_1DKrpwhUEzYm_dn0eGqDmVrJ4W4zOrzkqW885fDj9dY5nLHCaR3158SKRdMOordzpWSITzd2LfcZWrJ0DAoNq4SOEZqe0H5qvrnDGeYPFfP93ZpVNvlKHqinkmFflX8xfof5gYTVyeWp0C8eTpz13wWHJrX-IFs6xK15qMq73TuRIAIyI_q-EXcjBFj3yFXJA",
    "Natural Sciences and Engineering Research Council of Canada": "https://8n6q4g.ph.files.1drv.com/y4mygCVmXn5zR0jCMARCBQ_MsZZBZreNsYIn-u24DrUaN-JKKhSUNFFnUTXvCYzdPY_ntEGzDgZ8iP3KLsj9gHl8ccWRb8XjEDh4GwBY616TtjjZBtLma1Jyb1bsuh0wUdpNXZnlRqoFZi9xCLanAcGmpWMepK5qi6fwgrj8IA5clwucwTluHO7QrrYNMdwTViezuubxB4os5hBNwlXGDCBDQ",
    "Northern Pipeline Agency": "https://l69ldg.ph.files.1drv.com/y4m6hNfvD8W04LFN4m2oVtkivw_ieSB-lmjA4E1dtoMlQwvynvchFyTxKlfbKEGluMWzx4jIQ8tgTlFnASOJa-TjDqSn_fUV9wSv__sC4Wdx7J5hPeJEm89ert8VLKZtHyEyQrGGughYwGlIdQvbHPXk7lPYaYfqJNv2DUJqZWdUIpVpV6hDN5a9gdFGG3w1Mc1H_uNwecj_hJkEc27oCqcmw",
    "Office of the Auditor General of Canada": "https://aa1yyw.ph.files.1drv.com/y4m59WxhhJOdZJx4yUPI_d8UP62FV1_ZTfq1aIfqj52_02x1GiDuQaiYTaJpINpj4vklvbHgzHUOeX1XL_j7jXHwsqw345QIY7PeMMBIHyDcqz2vWi5PGz3aX_4IaqjaebbcJ2kK_HS1N-YD8-jh4o-73Cf4BT5fY-RM782favjQRdxWWqiJYpR9LibjvIV4sfo6YV6jIullQA8DkYOmUnf9w",
    "Office of the Chief Electoral Officer": "https://bn9a4q.ph.files.1drv.com/y4mpwLa6N597drzYsEf3X7onL-B7S6cDLo03D03RcXA7oSItm7ZljXWyYSx00TQHjxfs8v812XmuMDUwuDlJtaiv_HCory-Ix4_arIMLFUnCgwoOHQINXC9oTXhp9LC49Y9eAlv27WIF9BCKXGIjkwbPbsiLyY_IiMakME0TKGhA57VC9Jd2JNdlHxKauySLTcK_s4aRG00tBQrAKnXSZWv4A",
    "Office of the Commissioner for Federal Judicial Affairs Canada": "https://yip0sa.ph.files.1drv.com/y4mdZ2RP0ljdd2x4CiCVWNEYEMkTewVNyVZDG3RlmB_ojpzKJvr1BTzCahDXpFR1a-f4eFFXz4HwedlrNLiTDIo2Qj2lGyS3qKNWawbURfYySGIt0gKUrRRXes6z8j0O5Gkar-2t8pyUhnMwCu4XQkbzc1vQ5vYiYY_R0E4YDvWY0nrua16rxz4ZmL7JHuw8zZ4h3W08-Anoa5Q2qtVhPnUFQ",
    "Office of the Commissioner of Lobbying of Canada": "https://yioojq.ph.files.1drv.com/y4mwW_sLJJCP74FA1sjIwAoEKT-tcvzL834dcK2S_dGL99flMajr0wh2LsleXRpNKi8zq4KNrdImkHIPo_LTy7kmMTM0pmLfQnmGQ4j0IXH_QC2yPGhri1NhD5YoiOlO0uw4Z8oiAb4Ja_dbj4Vgt-R1bNYCISRzk48hUpmllUc3PYtjT58RjrQZATKnMkl5dKdFwk7HOj3vYcEZFRSygyLKg",
    "Office of the Commissioner of Official Languages": "https://nvyz9w.ph.files.1drv.com/y4me7e0Y7rTl7vGKK9OoDfukpASpKXurX0c5xhotLBVzQRQ-i-YIAMUDsRGTXrDpApwtPQA5nNuXGd7MKvAFIGhVaFKo8lC46HFZN-uyo5fMY_GV-RQrOKAjuIplNvsoJOBP0gizdTjWhJMxRDZ7CHxjNpNqds3uO587AH5cEwfWOlCJIkb5mp7hbHz0Vp5OjdT0QnziRS-FtAgtqk3teVxuw",
    "Office of the Conflict of Interest and Ethics Commissioner": "https://l69mdg.ph.files.1drv.com/y4mcnBRE7Fa08Qer19yoeziL8RBOBPRh0wjH1rdClboYy3849DF7GCaf99Jkrd2bVboux4O4q1bthVyYjx9_-dpqJTLwtLfxdDkgRlbQRIiUlQMyi_wmPMtn3ZmCB2q7BCNCTmeXKAtvE0hXN4rOF52uNtj9RnCI65BU54I9zTQWNTAzt0Gcslbxxmjs69xmVdbC_f-n2l1W2BJTXE2zn25DQ",
    "Office of the Correctional Investigator Canada": "https://0wrbmq.ph.files.1drv.com/y4mp4xsKOqUGyXcHFx7iPxwfTRRqHjX9Nwu3RE9yO1F5WILLP83Zy7sxfRHhMvj_RXJ4Z2tqWb7OetDjSbuX76i5qvGFiDCxKjjXKIosq47TiR3xHAEz-c2Gxx1IEDpL6yVXZyfpGuoYVmgZxuB_meCvPQeC4IY27wJuTJVIXyHxldbl9hiuf9zc82oWuEAVcYmkRIhVPWYBbtxW7Cd2qKlzA",
    "Office of the Information Commissioner of Canada": "https://m4enyq.ph.files.1drv.com/y4muJ95n33xu4UaPfUZe34wp0Yhw0U3syE-92cI06hgnHC1ytXn3Zmz-VSnBYSedcB8hcX8SswYrWE0s9rgApgZHhYTQPfL3dcic6tBGXURC9bpD3rId4fUrxwlfoRKlTmAtQ__pXsycu2CsNHjhti-78vUKD98wXnXj7ZsCoHBAYthtpxEFGoYQ2F5uzzI_cGq3JAuRG_fPsDiOOkMAEB0HQ",
    "Office of the Intelligence Commissioner": "https://aa3eag.ph.files.1drv.com/y4mqWZTkUYseoY30EHByLwOkFv8lnqgpVensLssxIA-NYc_125_1htPfCwCvfQkRWDMHRSSaPfjkX4534e7bCL6vkolTlONhJNWUoY6jtr4xurrW0l09cVCNqe-iDGgYuM2SypwWD-5AgQ9W6D5z7AzGdKXHWYlu5MojEo-I1p_J1GdxhscLIeQneCSO4c5qGv1PAapCktuG-uHauOx5NY4bw",
    "Office of the Leader of the Government in the House of Commons": "https://nvb8dq.ph.files.1drv.com/y4mjtzhqcvjqrYLSUQPa0APjDC92DKC0_qxcElxrd3n6Py-A6k58WEya9qNjiRy48J9XdEjk-SfYFwq-qPQmBe2HhFrKqs1R9H34a3FvSAxs2Ku-RAlAbdwfDSy8BHO-f4Do6oZJg0zAbUomGrLc1hjoIUh20S_FR6XxeQ9XLvu5qcNuBEA9R9jU-Dr4homYMiiaeD_VIcsbVlFQaB-L72aFg",
    "Office of the Minister of Intergovernmental Affairs": "https://l69h4w.ph.files.1drv.com/y4mskCWCKNgLgJNwDTvNJpFQkvIVFryeyXyfu8e-8Y14_AT0aBjdOU_HSmwWtYCu28NzkiWbfzZxZbJFihRLsrodoplx_Awqxbqf2MQq_6PHn19-K5OC4Kxx1nOHJTDpsfYUvoT_Nqi9qZPwgq_AbRvHRZLwmeuBDG74Q8_p2MjUts7IYBmmdmtiGwbxpJTDVME14VEySfNZkDCiqxR0IrN2w",
    "Office of the Privacy Commissioner of Canada": "https://m4emyq.ph.files.1drv.com/y4msZS65T0vJ4UYho4wXdy4hhRyDCwsGZDOWZFbNNTdHSbtluYr-5_Pz8ysI2-Ieusq44HgN58jFCEqsJ0iHcNawFNJoGnzkNXU8gj7Ln9qXagWbNjvT0kBBvZRPId3JHC8vAPnFu8Raw_-6V2csc94jbqFcjpx4ihqxobbe2WvMm-tyAY8wnTe4mlKUW0mNZ6fp-XAJaXmNqA6sE-A4wYBuw",
    "Office of the Procurement Ombudsman": "https://aa3dag.ph.files.1drv.com/y4mwSDufmCLiZxKlrg72wn9gP1IXvTwj5Ga3LrEwwKNo_kzLLUD-h1k6_n7xJBgNnRC75g-AP9eFueLOFVN8RiFl0t3vmyEXal9ZPSjzPSfzG4UxFymwrVFAR1bFMRvoanEBtgbnZQ16HU1BkXYXdzKc-hiwte3CuGKHX5obqtl4Z__VkEvfVyryBTUBa3yUb3Xt-wF-kG3shf5ykVpopMv0Q",
    "Office of the Public Sector Integrity Commissioner of Canada": "https://l6pjpg.ph.files.1drv.com/y4miXbeo1MJeLaqVQ9tbPRKxwbUe9CEzjmdhp7vMkPmbbvfpEV2Iqf2WMK4TvzBRDSi1tCpOCCwkJYjv5RKpDBuMh6mPESG_Oy3ML762Fw5XIhWMJu_6YnAFZ_rl3H-zeOlLxu9GLvmZFap9H0MZnFs49egPa4X3Xed_JbY_KSmHCuVIvh6ZJaytNyfGlbcilSZ3Flh0Bz3kEf19pLHVIC8fw",
    "Office of the Qu\u00e9bec Lieutenant": "https://aa29vg.ph.files.1drv.com/y4m8q8r0fs10nzAJyzipm4DfMpB2FK-JBYSEAGzyIoMwHfPF2-zbPTuXQlCrshAykeuWKwOtkPJ_ZmMeggn-8lZJmWzVbH2KADRCWUayKgmVPmAahFy6OOxBknoajpZM8tlvQBPz3CBGwE7hpXIqqzaL2hP0GPrjFWLQN7TDm0Cm_4QFPPJaTeF8OqzUV58H5XCbaf-ALPN14qRrfovHgp-yQ",
    "Office of the Secretary to the Governor General": "https://nvarow.ph.files.1drv.com/y4muqx8r96_Y1EgBF6ZII3ykWt0dWnwxsTBulOyvWEOtrD8pWin9Ed68op2QOgosiLy1UTdeGB804_6mmS7HqUNEp0LUL0ORpN7mOkMLvUc8jnO8mjDguku_9WCanxIpvyg_uWkfWU-U_J41YCyZXgkajXUWWBCQAp4xvHbn8ZsmTZiU8et3Sg62_OAJpJYO-Aa8HKrM55aX0kOm9ckRmob_g",
    "Office of the Senate Ethics Officer": "https://0wo53g.ph.files.1drv.com/y4mzOqDQFbMe8I8UGQxvf_GtX-nle08ctZAH2SwLA2Fgh12KRFXmouidakC5ZdflBHxBMtXl2GTqUsz73sEDnzkgLoZPX2ik_BXUT8kgVUj1zfiZ-zdNd04EPyrKmXNuRv8EkDNJBFzsmhUXeAzqQlR5n2jQcZuEo4cGYfYY3u8nswBlwLDtP9V_gxLYw1waC5yDgUrCA0ERqdBoxUcsCB8uA",
    "Office of the Superintendent of Financial Institutions Canada": "https://vwqsbq.ph.files.1drv.com/y4mjzNJm5bAfFm_4_Thzq00tgpBqkN2UvLf-N2B2bxn3VBf4hd7EEJlqhLVNJTYnq6AUNRHwJKEiplqbdvpXcarjV6bDY9NkPNfjJQd4shUWjOL_XrhV9-hMwjd3j9LEH6cB47Qph59rKji7ddBvgMvB-K8PilQ-rzb_v8JcBsC-3zt5a81B6jdr09RYJu0DgKm4UI84bBSdomcT3DjPxsKeg",
    "OFFICE OF THE TAXPAYERS' OMBUDSPERSON": "https://l6pb9w.ph.files.1drv.com/y4mDyIz1UT7o56UgUKhk9TKBrf25l_u57QrmVsA3EmUwpw5gDQ3WOh8pmkzek2kz9cFzeawR5CjYv0HHtC2Pp7rzA_6xvn9s2OfYdvHxGFnCfbzAbYebjKEWTq9mdKi75lMVu-eYVID0GNLU0rjbliTh5T_HoRiSnznvnrO-ini1iQ-A-Ki5cZeTSwtBp_q41nGFZbS1ACY53jSUbAagM-Nag",
    "Pacific Economic Development Canada": "https://bnq1vq.ph.files.1drv.com/y4mJEcoo_Xp8G7IzZTx-zSCC5Q_vEdcEqgRLK4uH_IerK2KPCJbnhwxomfv7us5QNTN56fKX-c5S_Rm7d3na9cEP7tYZuMCUde7TNX7M9R1ozS53kCORWsI9-s6yHtaVfC5ANCnIHTmLSPmWJZsEkLaGQF1b4VoR0CFqMld5b27cZgzH8bCNuP7ZDbm1A8-o9JMcx11694rC7vThCTvQQ-EQw",
    "Pacific Pilotage Authority Canada": "https://nvaqow.ph.files.1drv.com/y4mcD4rVbTf3E24lJqrx4ekQzxsA2AaKf8OxeiD9_tPJ2avRJV9vM-hmrXrccoNcx8MNIprcngxTcMV9aH0dniHH4LssgOKiJkXxf9jJ8kaKXyVoWV6ZHy8uekpWhCSBCmX7ZYUOzAAX0oUXqZ7gEbQ7z6vkWyhnbSrSWueisgabwz1_AXRKzszHnoTa4uEU3JeI6CPlcwh_XmkadzV24sJ-w",
    "Parks Canada": "https://bnpx3g.ph.files.1drv.com/y4mVM_zSil32y0AzCovVg1uxMievw4C1Inp1BFGx-4Df5XpHogL2znOudEhWgQyxf9dniaPZ7aXFpEs0hoosXBnb1I_LfEC5kDqRY67_RqNmUuyZnA9HAXkdmVc-JEVpkNVLJpIEaBACrZ7gajl88rg1-yjbZVGRAGZGvuKpvrIJ4uyGcT5CZYV5JbheqCAeLvm267pcRKGuqa38BDWilnlKw",
    "Parliamentary Budget Officer": "https://nvbnaw.ph.files.1drv.com/y4miI4Q6vHzGQ3GUJZf7WO6JpuKKTdkPKoam3U5vDsCKzCh1TiFO8tFG9VD7k20W4Q9dU5BOIu8syhP6cJI-WaZ3bEBijZGknobT-a2cRhtYXv-xPqgwt8_LGBm2eMt_5SMfv8VXRiRiHY5n6N61PFtRPVAGzfpUWqobb7eurOzL0baEYdPJclyUn7hj-AUAVMgHSdHcbiFFaZrjhRTMTLEuQ",
    "Parole Board of Canada": "https://m4eggg.ph.files.1drv.com/y4mvmnjzL1kbT8AeqFrYLC4t12IardbYar0sWpBaiTCnTYgUKkpxoITWyICz51oTF2PUuzABKh5VWcCyvHytSQBt3pC1rX4E6RDHgsF4LgcdTP0cUFX_e_vcI1zDosqbGyZYbMBfCCwGepF0iNJfQxAwtoZo9XfWfObp-WMyE4-PbbDvVZdqV0s_98K1rL8Ab5vy2DY6cexfRzrT4qLBCLKaw",
    "Patented Medicine Prices Review Board": "https://zziwka.ph.files.1drv.com/y4mMj479ZWwjYHkk9zBfkhGAsmnT9TaCzLsi5ikWrCUWZXr1HXm5XQ5RmYCI6-MMcDoJ2YSNtPfNpmNuFnhQ1A-OtomSbpBQZwfE29zpAcqGHR2ufFIZ1up3UAtbsu-YT2006PhbUDUpCaxFP4IwZddu7jcURADg9JkrWcSMRYRPAnJYOXsDktvR7RlvQBIOe1PCS1WsvmfRb1q_iGTGDqJKQ",
    "Polar Knowledge Canada": "https://nvykna.ph.files.1drv.com/y4mj8-CZAqYablQ2MT1pBjSR7zCqov4n_1yudft7VzQrOVXNoB43KnrCJmVNWR2pZBxZnUFsTJqxt0I11SwbdNaIjl3CASV5P9rIjaU2eOQAaAaUGgcEHycnkrBpN3QEJvZUSoyB07LSvOUzORliRu5lXk0CQAkZ2i-hXETuKk53UTdv3cjdbqjDVF4M_mWvCyoBoahvPjL8lLg0C5j_yG-PQ",
    "Policy Horizons Canada": "https://vwp9yw.ph.files.1drv.com/y4m119l_5eOrJV9TEncPUUxlXwhc8wAKe9Fd4C-XWprmTMQrcNTdTn_GUXD7MRkVDN5ygkHOEMR7cVMJSTGHHrnz1suMHlo2RlLk31i-E2qBeAhTxW4q55YsEC0uuCt-aAhzBQ6YB5CWa_cWoIcsN5Vw1PebNyS9kyEvuERUUd6STMO8ce04Nz_c99K2ayrmo5QLZhwocwI0-D7Q4oK62qJSg",
    "PPP Canada": "https://m4glva.ph.files.1drv.com/y4mr8jdSkEcwTilcb7orCfrdVDW7D_N680mA0Yq9JwKP-J9NMAZc-SpGm1M18qo0YPia_uSnEcupzz-zLrlgp1wdmr-vjcdMzJ4-lA6NlJmkKN99vD40dU-Z3G-5Yvz1bglcq8wHvHEFmKGfh4VzRlmRWJols_qVSyDMu_vjjUTVBTunzfzAvf2D9S2OWrHCcMdho5WvjEbxN8QQStQUbtUuQ",
    "Prairies Economic Development Canada": "https://m4hqma.ph.files.1drv.com/y4mmtPwy6KMHJcV3rnKrgvA-kyOkkzP3PBtngn_FQTFp0xs1CrUxtRVcEofuC-waI4pM22v7xb1jG8yD9IeVo8aZ3JGOwxwC-MAgSB0VBTthUDy0O1Fgg98opU7himWybHlIgeq5U3M7PR3cfdLYsnhzDgjbzagMHn0QRc_Aiu7EdG3eNDmJdzleFUTdBGqUSd2gf3u19giT20n307drPC_Eg",
    "Prime Minister's Office": "https://m4efgg.ph.files.1drv.com/y4mzo2ihe16YiePhjBFB7IRFwdtOAyKmINEj9lkGBVm47rhsVylwr-ER2Zwl_rZLtCnsXBE_FqJj8a16vunLiPgBTcC3FlyUbtaWWhc9sZdgbsxe0YCtIl1Vi5EptWNUCiHnYfBz4xAzcVrCMDk0i-t-dEHHpD2aPe63S19Z_lG4OkoPMleflhI2V9QqyLObCNuvxrK6awXykgZjzHjU0OQkA",
    "Privy Council Office": "https://yipzsa.ph.files.1drv.com/y4mTrHb-4Gh0m4QqrS6XOHT4cLHD7V4Yiuxk-dEbHpmKLvFKRL1Hq1yUs30LPJ5-fqsa1gCOas1KQMx_Q86meFNP-LuscoQ2-6jL7fSNaGUPShNmtaPzyWvL90kpqPZTkuoCcWhTUN1f0xTsXJN6yGbdwqCri6kvWKQKnWw9E18XsXMe1H82cwpCpLvj-6autrN8GMe_2uUDHOMn20PyU-mnA",
    "Public Health Agency of Canada": "https://l69g4w.ph.files.1drv.com/y4m6dZp_OGcs5K11ssRlLkxLG0BNPH6waJBkej-UcZItpJLJNVqqvH1_OFGCP3Y89mHvfhJhhcYuTS2hYcyBJ9GeSFer_y3xwUVZW5TAjkZTGkHoNXvjeC-mtId3HA68fXFzbENhTDqyz5tGtF8rybnvnDgu-1eUzc3-O0lE3ee62ySYNSQ5HMLQgGHO8Dw36naZtCMsw0AbHhwua1mSgWtPA",
    "Public Prosecution Service of Canada": "https://0wqzpg.ph.files.1drv.com/y4mgDAKGEj7v-eKS2bac0KeatqokLpCxYY_BQ3ka-5LovO4HUyDGmZcaqXEW0xRoZvCmbYtB-Aap2wDasfBbhPDCum7sovWuOseRaf5O5iAoTo1qEJcXh2dOc6vdsEU7ms-Wpg_aA0BWwLOelWe3evrlnHUgurvIaFkVQuGwaoUmtHBgjwrAYvu6gEUppaFcEirrsxr4hFM7M7HU2L0rMGJ3A",
    "Public Safety Canada": "https://zzjygw.ph.files.1drv.com/y4mLcrD4YE2jeH_a529rxd_c9kTY04yEsswnbNa5zSLt4CRvzCSpzjfoGRa6FP_29_-h4k15R8E83M0do5e_Z09vNKdR-oc2tsXX30_aRioap1SbsqrW2QQkepHIGz_G_nhPVpQA4uk7zbXY9PPFLJWUBI3L89V-3vHHglrYRgrXIqzI9-AO-FPxwYWzXD7EJJg36G3hjR9ma_OCO-jwzlr2g",
    "Public Servants Disclosure Protection Tribunal Canada": "https://0wposw.ph.files.1drv.com/y4mUD1xeRqqgxoT342mXKJGOtWzOafoN95EB4wTlAIvxnPXE2cOSM36vrAhpRqtoirnq-AzPqg7SWna6uR5sGtyC1EdMfdGOGyg97KH3Tx4TuXpPGdFRwDRqzMR4LHtUNzJ2bn1j_u01KfCAthECKivNKyFI_XF4q8pkPMrzRZCQkoA4xG-kyupgKM9sD0iuK-Qh9PQL5dOQ7cxluTihJIv4Q",
    "Public Service Commission": "https://vwoyqa.ph.files.1drv.com/y4mRZQE9FITw1p20mg0Fq0HA0ijl-lbWJWYYzcQPo3JmciaoxyWFPr6nIlxngTc2HJMDG84gQ0IHD03ul_azeswoXobS26SNPpYe7DUiNBEYWlTSQzr2_b_xPhGkifkORj53CqHANTB1UEyCAUQOT9dfqDpYcOMRC27YZnvdOoAyvVmml1KiAAtEGnjadJef4CVKivX998g4PnKU4ICXdLEtQ",
    "Public Services and Procurement Canada": "https://l6p44a.ph.files.1drv.com/y4myd9ySCqmoZMFe3PC6KBwukQrsZjRCpvCRQrWggMcOkQd0F4oTI6TjGVtFlxNst_rFcc0K-pZ6JnSAIhGEYUKqbaGIhb8IpueCZz-sTY6ewKOrY2QzceQzQZjHmRZRE3pzH48Ohbu1gVJevNC-CCXQZfGlQ4IL8cIx9yHoGdRMjyMGUMG_Ehh9VOzURq4G5phm43ejcUx556ixryTkI90BA",
    "Royal Canadian Mint": "https://nvyy9w.ph.files.1drv.com/y4mMHygmh8KfbmAx3cdOJgPTGdzBf1cTwNuyJ6Cy6RNFOdD3YXwhOIXeWtBwfNAVulBZwboCZ0K6UYhHGO0cnyrP0WHo-PpSqCmvkdVUohnzh8vSMcghfIOPiA-c0KnegjoHnRE2jUrYoGdOFMDmccDrhVBoyhhaX_e4l8XIvtlW80BpmjcLRCPPobXcAJC3P7LUlCFlfLoA3pahY6ADtRkQQ",
    "Royal Canadian Mounted Police External Review Committee": "https://0wpvxw.ph.files.1drv.com/y4mxZ7uJ4TIEfpJ-B5Tryh4QNq8qXHa3P1NFwUGbFNIXXJH2UttD1rzH1MADLol1zBGlCobYQcrDj1GZu_vfq6kDmSUuGZEA9ORJ8h56OMrv30-DgY52ZpcZQiMI4Zt2q3EuMAkEH_XQvdm2m6oK4NncLuQYrj1gumi3iPgK5XqwvSBvrXLE7XHerdzbwn7_hI0Jd7iEr8sWr05NYB-8vwBsA",
    "Royal Canadian Mounted Police": "https://nvamea.ph.files.1drv.com/y4mHW87y2mHsjbXPZclNtAqyox_zefVGxzB_24F4PYD48K_rf-tahWe7PEoeswNUY2n09k7nEs5nWsMP0ZXlqK0gYIKhIMq1ePT5S5wzUU7_JpVjQqxcCGG2DPI1iSKKoJSq7d2ArorTaskHV9fbh0j4T-gUuX0hKZpcoUCV6oxbxIlutHSMAUUrnU7MLPfTc4zEsOUKf9W7Z--_YH2kqmrSg",
    "Royal Society of Canada, The": "https://aa2ajg.ph.files.1drv.com/y4mubLVseqb5HO5wIzO8iJo0lYDxGGDeslySUawfx73MIOJZm0_FhVc68XJ5g6hvEeXwaANcsR0AxIcpG0ZiHWNtLqOBqAS-HZ4pV7VwvA33dY0TK2juoPcJS45FLhhKlGwyJmVKVqvQ1wbBCoTIDKRFqDwY1iDrFlF-WrR2tGayzti2se27W5Kz_Orlq4JfT7Y5MdD_UpWCP5JTLBenVu2-w",
    "Secretariat of the National Security and Intelligence Committee of Parliamentarians": "https://8n5tea.ph.files.1drv.com/y4mdQru4K1hLWh74EnnN1LhBjxk35dc8Xh0PQXYuvslocIPBGsURy-rxETxmPOQ1j3h51t2jyPGH_QqvuEaYcpchV_m8ymzY33niz18o8OtsA87lQ4PukRc1J-T-a0ISWakAyqABAJgLA-hFnYbrJNIRZbJelEilLAT61EoX_JDUsIH-N5SLkNL71wU1qLQ9fEXjNSPH1L_B0gu1RiAVEKI0A",
    "Senate of Canada": "https://8n7uha.ph.files.1drv.com/y4mUpalZa6C0WvmeMMDMoT4gi8fDOUfz0c6p5R8gW1ArRFufJoOfC5VUkyajb8ictIXXfBGEWGlQV3ReVQUD_y9_QakKRRusLf0sRrJqx6fAxgm6_ij1vp9YN3zPtRca3rS8r3o1wDIwJGi0s72pQtIDersjabdkxLAsEroMw5a8oO5_qRA2deEZQq1hsBGz0meE4rg_3WFiIR_x9ENdZz7tg",
    "Shared Services Canada": "https://l68cba.ph.files.1drv.com/y4mRXE32R7NWTUsZOnuNtJ6JiBMhRnacEFCUCvfkoAYkQYc4ltvPsjdoF-xrrLTLs3_4OxtldbKCzIa4m3fAc5mCyqYJ6m1yUNTcdb9hQLeDxM85Yf4wnqht6OrwjL3G1xX95O0wvKIdxZH5VWzcwb2sy1lChsQ3xdT3x3aAhQD4g2mm5zTnbRv46-CNAJxKS6ofwG_OAvomvuQsCAFlkWfiQ",
    "Social Sciences and Humanities Research Council of Canada": "https://nvbgja.ph.files.1drv.com/y4m1pRGKjJ3vzph3tlD3dNXcCfLe7Nf_DjenmnIDTaF6YrW-mxmnQ_hlwtE6pavt3Wq-WNHFVUKycXXXpxA30pGFyQjFb4MzFHS2mgdgDPYB-2EbJdBy6a89eMnrQiZruyLosQEWMb9F8Tz8dclH4XHcE0Fah-j9-5RGeNcPIzgmbn5xMpPpcM_D9uGrFo8-mzTi_NS5HT3m1T1HwgyCmiiVA",
    "Social Security Tribunal of Canada": "https://yip69w.ph.files.1drv.com/y4mh_2UXWIFvMlkH8hgGn0Ph-s-4PgGmE3wcVza5RjyMwMbyKK0yJyyKULXEPs4Fpk2b9xIuEX6VBga6Nkh4wNjTs_SMvgKfX0c7q_l29zfOhP9ZTyIfXZeXRPhtSJnf041PHujp7HCtxK492Vm4MNPv8K6HKxe3B_KSY4CqJfVRVX72rGXPZPQNSwZ4P3iNaQY687dADo9navMOGDLPEgpXQ",
    "Standards Council of Canada": "https://zziauw.ph.files.1drv.com/y4mcuN0Rzmn-GtniY8mO3ofKCaTT2SJQ-Xm3RJuhFlT3Yb2g32u8matpREjG0kv3kmY6URrAke5YocKsVSvWh7f0i3uaXkZ25PjZTZFjLTBAj9hgrOuqPMp-L2k6qa2rck9EAIO9eBVbn-ZnCr2csMLllPxLts9_3rg95QmMAsYLkX-IQ8UrgqvRbc4R6_1vTZeKYRAwApQQNuT9Ilc2xikNQ",
    "Statistics Canada": "https://0wpajq.ph.files.1drv.com/y4m6ENjNaEIhNIDm-9CJcO85vJBOrefhDYAc9hWngtC-RJKvJCfmm_TkybTSDP1PmLECLuizgxChV_v4HECvHDJ9oMdK61v-vXG1QERVWS7LkR47V-aaQchnlOG-wXDwxSgNSfRKIaKt0KiKQH0ZdULC09YR9NjznjFuO_Z34P1Xdt8AQfYMTZYkEH8m9E38yyg3oKZ5ZNKZx2WwIUgUA_Xxg",
    "Supreme Court of Canada": "https://m4g69g.ph.files.1drv.com/y4mUTfWw6GVR-ySLuNNkelgZBv8MCRPtGBJUu1nE0rKaxtwlZL007GA08QJeGisP8ZBC0Dk-x3w9EGdKFkPmAWb-nc74v5ZfuHfh1OZxiwROzrmRHaIxwdHG3FU6Tf-a86POyVZP90fSPf-zJhsoEopPPHAwL6mePY9fnplnCNcgZQuVIaRQhHuybaqXxT3BMbmxGVqlQJP4SEl0O-E9xJbgQ",
    "Tax Court of Canada": "https://8n64mw.ph.files.1drv.com/y4mAWKZEu0813q-dd3TOw4K7inrgAyhqWndx64xc0OIksFP4bxXCN4l1UhVREVVx1CW47xMK31XHQhUBRtqI1Fht1G388-oX2_S748jaeh8HBuj4BKKXb5pnXMgxzYh_gKUqEYT7F9Ekdyn0XVQCHojWX1JRsMW3ngHjKBrECWyhGtknwG62rNkkX52Jk1z07uC-SKH91l0dqGtcl0N9xtbCw",
    "Telefilm Canada": "https://l6qfbg.ph.files.1drv.com/y4mDuZkU1uNNrN8wHpI4ocIsc3Ef3EnYcKwZb7zdbgEMhVP9d1rC5GeYgedcX-VuOFr_WWAlAb0AnlrjUjJs8-lMJjVuMe8vZdxd8RWXJ53CKNz2ztiVcRI-jutZYtzdEzM3KTILOGKOpFmN5n8IWsF3f89EXyaHpPm-jQ2GF34HvJm9udNszm0tn5w5vEMF0auuC1VbMRY2tvk-i3sTHAqzA",
    "The Federal Bridge Corporation Limited": "https://m4fwaw.ph.files.1drv.com/y4mdAOfOn9mADiP9zLzsEG8DVAQqfZfDxmHJYibrp-bkmoYKeLwB66HfCwgYzEjPveGtCfagTmD7vuX5j7yyU6mkMMiMricrOZmDVWuQaXPVQHDu88wA3YS2pIgA0quD2U5PAWlT7WaCsHyKWPgXkPsy2OfAVItqjwGKj0YATpMqfAoSPLAipvw-sQrNfx9J_wWYSlLJTpEDwplZq6DEQzKwg",
    "The Jacques Cartier and Champlain Bridges Incorporated": "https://aa3ksq.ph.files.1drv.com/y4m5bcCbwwFgMl8z6wJW02WR2sLyMIz7PIroaaRcRc9VcCzY_R2lQzLXud40pZxrUUketsixFBXzXTL96CRLEccVCCned2ynROQFzLKMhCMv-DuBcYpOsJbi-MYHZoPl0j9CsauLV4Ar8Vq2Q2teITreQ3mTp74ayZAVGYDtMHPEcxunCLREui4qYLa1mZV_wfmxxu2ijyo5m0KHuZLanOx5Q",
    "The National Battlefields Commission": "https://yimihg.ph.files.1drv.com/y4mzRDOOotl_ssvUGymakmfhTiW0pZygKUXHzb3sKIJTAYdlf4abmzLMvCfAGQ9fHHi5wqoV6JJQf_GZrR4e8Jw-2DR__dkZ8B9dv9ZcrztkZpX6At1uyJyiZBFhBURWR7tARMJHtyGFu_zWRmfil_LmT0WyRf2yVFSWLUForwXxy7IcFTJheao6RDc8VGVuI49d_DDBlxgjPVZfsauv1BYiA",
    "Transport Canada": "https://nvboaw.ph.files.1drv.com/y4myiJLXG9OhOnv170LeLe-6kCZmFKouTs6pb6jNGHl63jR2ynGCtawi6Vq1pYLI9Hnk9mGdqJaSSotHZYueMfD8hrDaLgF1sjckPPkLAJProskJYPi7qWjXofGpjUhqVF9J6jRsSv4NLwuY9eJJMpg-Q9eNXPE6dBqWWpYkU-oL4QZIOon8exroK6D0oeB1uro10Lh9xWHf9w3x6Cb9VbEBQ",
    "Transportation Appeal Tribunal of Canada": "https://vworpq.ph.files.1drv.com/y4mSm7k0gk_uATos4hDIpHQiJCL1RsyPS6ipk0yDlNoId4YygCP0TwH-R4KKiBJ8YW_djDrQOKVNifT5Dp8S-_GjW2zn4Uixf-aOdHniXbBxp-xbVG61Jgyasqhg_XE8Ky9F9V3-uka_pwHMN8VDubFhHBLMp8p4wQmDj-Fi519M6Mldwb-5HkF2DkarKV6qCKUhGGOsgfAYwnPCHG5neeEww",
    "Transportation Safety Board of Canada": "https://zzg8dw.ph.files.1drv.com/y4m-OPNK5O1gOmEAKXCwGMWTWrVzDAmGmQ-z4R_AtIc5VLS5FvI8_dZuulQwe47IxiJ0Ay1feE8B6aF76Cu9F42ke8VnvcY_w-Dv1fP1sz2HE2Vm1-p4QEbWUqnOMDD5FJweNL6kHPFHAz5byVAjcaWO34VIUjQMQu-Oadp5xb69yumd7LKF1neugowwGV12p-vqsym3mAhQeJRvvLicwWwbA",
    "Treasury Board of Canada Secretariat": "https://nvalea.ph.files.1drv.com/y4mDxXb_ozpdVp3eGbi7W1TGnQmXa-1PfkOaqzOZ7Rtj7Ta5EamDvZttOkoo0wHMurVx7WWisZnYXHWInqA-EdwEX5GMr_nefC_RtQPZ5QEiIaXh5qWK2Y7d_ELUd2jMMmHxNeqNCGV_wsR4swvRfnfeO-01mAlCg7fhnmsIyoJtjjca9-7NssphZMsgXoISvX5uL5UYKfO3-ffo7m4FG00yg",
    "Veterans Affairs Canada": "https://nvaygg.ph.files.1drv.com/y4mWFuQPa5-37nKpZMxxO1SbaYFfB-iMwN38bKjs25H_31PoLfqIX1ZFVvt2dyNnDkCqdAH9AnnIS2n5hYITFI8DoSOlSEUX0s5MNG5I91KC5I2HBRAunqWXTbDlnfFVCXTmdl-rf5Q6bojUTvhlOuTXx5_WgHbwyxgEs5u4XpGG6Dr5j6uxfTxYkgezw693vPLqj5mcsCj92pTD_E5_zSPjA",
    "Veterans Review and Appeal Board": "https://aa1kpq.ph.files.1drv.com/y4mLTgC6Ssk1sqCDGvmj6X50xQcqHHQTTVD4iMjnwoPzW6EQbY9cLBVS_aTe7Bgp6h2-8N_ZNNKE7HwREKFfXbmRIjBLkgAUR2xzxSV-5Xu0Otv5aoZ947DCTfBV8bWTRxVn-YLPo9rogRo6QrYYEgay7fdULj8tfaKba56UG9tyafWOOITBn9ep8vC3FNwJdpFh-R2wbMj8sZsX5zmiq5aJw",
    "Women and Gender Equality Canada": "https://zzibuw.ph.files.1drv.com/y4m-Prxo8OBt88u9-hRvY9RXsMO6bcjY0qLMKoCV4zSD2ryYDeJNafLDgoHYY2r8vV2Z8Qps-4gl5txs60600_XavV4SqGeJI2dq_nzWB1wB4s5elXChf1uI5VjN9ElIN7KJuavTruCdvexRacAZQAYsoOBmI9yCPUJ6bEz2qj4glaxYaDVp11jRaPY2EYve_TVnRY3kk3E0Xil4ilqYPoS1w"
}

let govData = {}
let total_offset = 0;
let total_vertical_offset = 0;
let total_horizontal_offset = 0;
const board = miro.board;

function makeSticky(stickyData) {
    let tempSticky = board.createStickyNote(stickyData)
    return tempSticky
}

function makeTag(tagData) {
    let tempTag = board.createTag(tagData)
    return tempTag
}

function createShape(shapeData) {
    let tempShape = board.createShape(shapeData);
    return tempShape
}

//this one will draw the department horizontally
async function drawHorizontal(departmentName, horizontalOffset, verticalOffset) {
  let baseWidth = 87;
  let baseHeight = 212;
  let baseBuffer = 12;

  let stickyHeight = 27;
  let stickyBuffer = 5;
  let count = 0;

  let departmentFontSize = 36;
  let secondaryFontSize = 13;

  total_offset = parseInt(horizontalOffset)
  for (const department in govData['childOrgs']) {
      let element = govData['childOrgs'][department] 
      let departmentChildLength = Object.keys(element['childOrgs']).length; 
      let secondary_depth_child_orgs = 0
      for (let each_branch in element['childOrgs']) {
          secondary_depth_child_orgs = secondary_depth_child_orgs + Object.keys(element['childOrgs'][each_branch]['childOrgs']).length
      } 
      let deptShapeWidth = (baseWidth * departmentChildLength) + (secondary_depth_child_orgs * (baseWidth + baseBuffer)) + (baseBuffer * secondary_depth_child_orgs) + (baseBuffer * departmentChildLength);
      if (departmentChildLength == 0) {
          deptShapeWidth = 1500
      }
      let departmentShape = await createShape({
        content: department + " (" + element.population + " people)",
        shape: 'round_rectangle',
        style: {
            borderOpacity: 0.8,
            color: '#1a1a1a',
            fillColor: '#8fd14f',
            fillOpacity: 0.4,
            fontFamily: 'open_sans',
            fontSize: departmentFontSize,
            textAlign: 'center',
            textAlignVertical: 'middle'
        },
        x: total_offset + baseBuffer + (deptShapeWidth / 2),
        y: verticalOffset,
        width: deptShapeWidth,
        height: baseHeight,
      })
      let subCount = 0;
      let branch_offset = 0
      for (let branch_node in govData['childOrgs'][department]['childOrgs']) {
          const branch = govData['childOrgs'][department]['childOrgs'][branch_node];
          let branchChildLength = Object.keys(branch['childOrgs']).length;  
          let secondary_branch_length = 0;
          for (let each_secondary_branch in branch['childOrgs']) {
              if (secondary_branch_length < Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length) {
                  secondary_branch_length = Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length;
              }
          } 
          let shapeWidth = baseWidth + (branchChildLength * (baseWidth + baseBuffer)) + (baseBuffer * branchChildLength);
          let shapeHeight = (baseHeight * 3) + (baseHeight * secondary_branch_length) + (baseBuffer * secondary_branch_length) + baseHeight / 2;
          let branchShape = await createShape({
            shape: 'round_rectangle',
            content: branch.name + " (" + branch.population + " people)",
            x: total_offset + branch_offset + baseBuffer + (shapeWidth / 2), 
            y: verticalOffset + baseHeight + (baseBuffer * 4),
            height: baseHeight + baseBuffer, 
            width: shapeWidth,
            style: {
                borderOpacity: 0.8,
                color: '#1a1a1a',
                fillColor: '#8fd14f',
                fillOpacity: 0.4,
                fontFamily: 'open_sans',
                fontSize: secondaryFontSize,
                textAlign: 'center',
                textAlignVertical: 'middle'
            }
          })
          subCount++
          let divisionCount = 1;
          let division_offset = 0;
          for (let division_node in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs']) {
              const division = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]
              let final_depth_child_orgs = Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // final_depth_child_orgs = 1
              // for (each_team in govData['childOrgs']['Employment and Social Development Canada']['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
              //     final_depth_child_orgs = final_depth_child_orgs + Object.keys(govData['childOrgs']['Employment and Social Development Canada']['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // } 
              // console.log()
              let division_shape_height = (stickyHeight * final_depth_child_orgs) + (baseBuffer * final_depth_child_orgs) + baseHeight / 2;;
              let divisionTicket = await createShape({
                shape: 'round_rectangle',
                content: division.name + " (" + division.population + " people)",
                x: (baseWidth * divisionCount) + total_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                y: verticalOffset + (division_shape_height / 2) + (baseHeight * 2) - (baseBuffer * 1),
                height: division_shape_height, width: baseWidth,
                style: {
                    borderOpacity: 0.8,
                    color: '#1a1a1a',
                    fillColor: '#8fd14f',
                    fillOpacity: 0.4,
                    fontFamily: 'open_sans',
                    fontSize: secondaryFontSize,
                    textAlign: 'center',
                    textAlignVertical: 'top'
                }
              })
              let teamCount = 1;
              for (let each_unit in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
                  let team_details = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs'][each_unit]
                  
                  let teamLabel = makeSticky({
                      content: team_details.name + " (" + team_details.population + " people)",
                      style: {
                          fillColor: 'light_yellow',
                          textAlign: 'left',
                          textAlignVertical: 'middle'
                      },
                      origin: 'center', 
                      x: (baseWidth * divisionCount) + total_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                      y: verticalOffset + (baseHeight * 2 + stickyHeight * 3) + (stickyHeight * teamCount) + (stickyBuffer * teamCount), 
                      height: stickyHeight
                  })
                  teamCount++
              }

              divisionCount++

          }
          division_offset = division_offset + baseWidth + baseBuffer
          branch_offset = branch_offset + shapeWidth + baseBuffer

          count++
      }
      total_offset = total_offset + deptShapeWidth + baseBuffer;
  }

  const department_title = await board.createText({
      content: departmentName,
      style: {
          color: '#1a1a1a',
          fontFamily: 'open_sans',
          fontSize: 288,
          textAlign: 'left'
      },
      x: 4000, 
      y: verticalOffset - baseHeight - baseBuffer * 4,
      rotation: 0, 
      width: 8000
  })
}

//This one will draw the department vertically
async function drawVertical(departmentName, horizontalOffset, verticalOffset) {
  let baseHeight = 87;
  let baseWidth = 212;
  let baseBuffer = 12;

  let stickyHeight = 27;
  let stickyBuffer = 5;
  let count = 0;

  let departmentFontSize = 36;
  let secondaryFontSize = 13;

  total_vertical_offset = parseInt(verticalOffset)
  total_horizontal_offset = parseInt(horizontalOffset)
  for (const department in govData['childOrgs']) {
      let element = govData['childOrgs'][department] 
      let departmentChildLength = Object.keys(element['childOrgs']).length; 
      let secondary_depth_child_orgs = 0
      for (let each_branch in element['childOrgs']) {
          secondary_depth_child_orgs = secondary_depth_child_orgs + Object.keys(element['childOrgs'][each_branch]['childOrgs']).length
      } 
      let deptShapeHeight = (baseHeight * departmentChildLength) + (secondary_depth_child_orgs * (baseHeight + baseBuffer)) + (baseBuffer * secondary_depth_child_orgs) + (baseBuffer * departmentChildLength);
      if (departmentChildLength == 0) {
          deptShapeHeight = 1500
      }
      let departmentShape = await createShape({
        shape: 'round_rectangle',
        content: department + " (" + element.population + " people)",
        origin: 'center', 
        y: total_vertical_offset + baseBuffer + (deptShapeHeight / 2), 
        x: total_horizontal_offset,
        width: baseWidth, 
        height: deptShapeHeight,
        style: {
            borderOpacity: 0.8,
            color: '#1a1a1a',
            fillColor: '#8fd14f',
            fillOpacity: 0.4,
            fontFamily: 'open_sans',
            fontSize: departmentFontSize,
            textAlign: 'center',
            textAlignVertical: 'middle'
        }
    })

      let subCount = 0;
      let branch_offset = 0
      for (let branch_node in govData['childOrgs'][department]['childOrgs']) {
          const branch = govData['childOrgs'][department]['childOrgs'][branch_node];
          let branchChildLength = Object.keys(branch['childOrgs']).length;  
          let secondary_branch_length = 0;
          for (let each_secondary_branch in branch['childOrgs']) {
              if (secondary_branch_length < Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length) {
                  secondary_branch_length = Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length;
              }
          } 
          let shapeHeight = baseHeight + (branchChildLength * (baseHeight + baseBuffer)) + (baseBuffer * branchChildLength);
          let branchShape = await createShape({
            shape: 'round_rectangle',
            content: branch.name + " (" + branch.population + " people)",
            origin: 'center', 
            y: total_vertical_offset + branch_offset + baseBuffer + (shapeHeight / 2), 
            x: total_horizontal_offset + (baseWidth + (baseBuffer * 4)),
            width: baseWidth + baseBuffer, 
            height: shapeHeight,
            style: {
                borderOpacity: 0.8,
                color: '#1a1a1a',
                fillColor: '#8fd14f',
                fillOpacity: 0.4,
                fontFamily: 'open_sans',
                fontSize: secondaryFontSize,
                textAlign: 'center',
                textAlignVertical: 'middle'
            }
          })
          subCount++
          let divisionCount = 1;
          let division_offset = 0;
          for (let division_node in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs']) {
              const division = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]
              let final_depth_child_orgs = Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // final_depth_child_orgs = 1
              // for (each_team in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
              //     final_depth_child_orgs = final_depth_child_orgs + Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // } 
              // console.log()
              let division_shape_width = (stickyHeight * final_depth_child_orgs) + (baseBuffer * final_depth_child_orgs) + baseWidth / 2;;
              let divisionTicket = await createShape({
                shape: 'round_rectangle',
                content: division.name + " (" + division.population + " people)",
                origin: 'center', 
                y: (baseHeight * divisionCount) + total_vertical_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                x: total_horizontal_offset + ((division_shape_width / 2) + (baseWidth * 2) - (baseBuffer * 1)),
                width: division_shape_width, 
                height: baseHeight,
                style: {
                    borderOpacity: 0.8,
                    color: '#1a1a1a',
                    fillColor: '#8fd14f',
                    fillOpacity: 0.4,
                    fontFamily: 'open_sans',
                    fontSize: secondaryFontSize,
                    textAlign: 'center',
                    textAlignVertical: 'top'
                }
              })

              let teamCount = 1;
              for (let each_unit in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
                  let team_details = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs'][each_unit]
                  
                  let teamLabel = makeSticky({
                    shape: 'square', 
                    content: team_details.name + " (" + team_details.population + " people)",
                    style: {
                        fillColor: 'light_yellow',
                        textAlign: 'left',
                        textAlignVertical: 'middle'
                    },
                    origin: 'center', 
                    y: (baseHeight * divisionCount) + total_vertical_offset + baseBuffer + division_offset + branch_offset + (baseBuffer * divisionCount), 
                    x: total_horizontal_offset + ((baseWidth * 2) + (stickyHeight * teamCount) + (stickyBuffer * teamCount)),
                    height: stickyHeight
                  })
                  teamCount++
              }

              divisionCount++

          }
          division_offset = division_offset + baseHeight + baseBuffer
          branch_offset = branch_offset + shapeHeight + baseBuffer

          count++
      }
      total_vertical_offset = total_vertical_offset + deptShapeHeight + baseBuffer;
  }
  const department_title = await board.createText({
    content: departmentName,
    style: {
        color: '#1a1a1a',
        fillColor: '#ffffff',
        fillOpacity: 0,
        fontFamily: 'open_sans',
        fontSize: 288,
        textAlign: 'right'
    },
    origin: 'center', 
    x: horizontalOffset - baseWidth - baseBuffer * 4, 
    y: 4000,
    rotation: -90, 
    width: 8000
  })
}

//This is the same as the drawVertical but flipped along the Y axis so it draws to the left instead of the right.
async function drawInvertedVertical(departmentName, horizontalOffset, verticalOffset) {
  let baseHeight = 87;
  let baseWidth = 212;
  let baseBuffer = 12;

  let stickyHeight = 27;
  let stickyBuffer = 5;
  let count = 0;

  let departmentFontSize = 36;
  let secondaryFontSize = 13;

  total_vertical_offset = parseInt(verticalOffset)
  total_horizontal_offset = parseInt(horizontalOffset)
  for (const department in govData['childOrgs']) {
      let element = govData['childOrgs'][department] 
      let departmentChildLength = Object.keys(element['childOrgs']).length; 
      let secondary_depth_child_orgs = 0
      for (let each_branch in element['childOrgs']) {
          secondary_depth_child_orgs = secondary_depth_child_orgs + Object.keys(element['childOrgs'][each_branch]['childOrgs']).length
      } 
      let deptShapeHeight = (baseHeight * departmentChildLength) + (secondary_depth_child_orgs * (baseHeight + baseBuffer)) + (baseBuffer * secondary_depth_child_orgs) + (baseBuffer * departmentChildLength);
      if (departmentChildLength == 0) {
          deptShapeHeight = 1500
      }
      let departmentShape = await createShape({
        shape: 'round_rectangle',
        content: department + " (" + element.population + " people)",
        origin: 'center', 
        y: total_vertical_offset + baseBuffer + (deptShapeHeight / 2), 
        x: total_horizontal_offset,
        width: baseWidth, 
        height: deptShapeHeight,
        style: {
            borderOpacity: 0.8,
            color: '#1a1a1a',
            fillColor: '#8fd14f',
            fillOpacity: 0.4,
            fontFamily: 'open_sans',
            fontSize: departmentFontSize,
            textAlign: 'center',
            textAlignVertical: 'middle'
        }
          })

      let subCount = 0;
      let branch_offset = 0
      for (let branch_node in govData['childOrgs'][department]['childOrgs']) {
          const branch = govData['childOrgs'][department]['childOrgs'][branch_node];
          let branchChildLength = Object.keys(branch['childOrgs']).length;  
          let secondary_branch_length = 0;
          for (let each_secondary_branch in branch['childOrgs']) {
              if (secondary_branch_length < Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length) {
                  secondary_branch_length = Object.keys(branch['childOrgs'][each_secondary_branch]['childOrgs']).length;
              }
          } 
          let shapeHeight = baseHeight + (branchChildLength * (baseHeight + baseBuffer)) + (baseBuffer * branchChildLength);
          let branchShape = await createShape({
            shape: 'round_rectangle',
            content: branch.name + " (" + branch.population + " people)",
            origin: 'center', 
            y: total_vertical_offset + branch_offset + baseBuffer + (shapeHeight / 2), 
            x: total_horizontal_offset - (baseWidth + (baseBuffer * 4)),
            width: baseWidth + baseBuffer, 
            height: shapeHeight,
            style: {
                borderOpacity: 0.8,
                color: '#1a1a1a',
                fillColor: '#8fd14f',
                fillOpacity: 0.4,
                fontFamily: 'open_sans',
                fontSize: secondaryFontSize,
                textAlign: 'center',
                textAlignVertical: 'middle'
            }
          })
          subCount++
          let divisionCount = 1;
          let division_offset = 0;
          for (let division_node in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs']) {
              const division = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]
              let final_depth_child_orgs = Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // final_depth_child_orgs = 1
              // for (each_team in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
              //     final_depth_child_orgs = final_depth_child_orgs + Object.keys(govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']).length
              // } 
              // console.log()
              let division_shape_width = (stickyHeight * final_depth_child_orgs) + (baseBuffer * final_depth_child_orgs) + baseWidth / 2;;
              let divisionTicket = await createShape({
                shape: 'round_rectangle',
                content: division.name + " (" + division.population + " people)",
                origin: 'center', 
                y: (baseHeight * divisionCount) + total_vertical_offset + division_offset + branch_offset + (baseBuffer * divisionCount), 
                x: total_horizontal_offset - ((division_shape_width / 2) + (baseWidth * 2) - (baseBuffer * 1)),
                width: division_shape_width, 
                height: baseHeight,
                style: {
                    borderOpacity: 0.8,
                    color: '#1a1a1a',
                    fillColor: '#8fd14f',
                    fillOpacity: 0.4,
                    fontFamily: 'open_sans',
                    fontSize: secondaryFontSize,
                    textAlign: 'center',
                    textAlignVertical: 'top'
                }
              })

              let teamCount = 1;
              for (let each_unit in govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs']) {
                  let team_details = govData['childOrgs'][department]['childOrgs'][branch_node]['childOrgs'][division_node]['childOrgs'][each_unit]
                  
                  let teamLabel = makeSticky({
                      shape: 'square', 
                      content: team_details.name + " (" + team_details.population + " people)",
                      style: {
                          fillColor: 'light_yellow',
                          textAlign: 'left',
                          textAlignVertical: 'middle'
                      },
                      y: (baseHeight * divisionCount) + total_vertical_offset + baseBuffer + division_offset + branch_offset + (baseBuffer * divisionCount), 
                      x: total_horizontal_offset - ((baseWidth * 2) + (stickyHeight * teamCount) + (stickyBuffer * teamCount)),
                      height: stickyHeight
                  })
                  teamCount++
              }

              divisionCount++

          }
          division_offset = division_offset + baseHeight + baseBuffer
          branch_offset = branch_offset + shapeHeight + baseBuffer

          count++
      }
      total_vertical_offset = total_vertical_offset + deptShapeHeight + baseBuffer;
  }
  const department_title = await board.createText({
      content: departmentName,
      style: {
          color: '#1a1a1a',
          fontFamily: 'open_sans',
          fontSize: 288,
          textAlign: 'left'
      },
      origin: 'center', 
      x: horizontalOffset + baseWidth + baseBuffer * 4, 
      y: 4000,
      rotation: 90, 
      width: 8000
  })
}

//Setting up the listeners for the user-facing menus and buttons
document.getElementById('drawStart').addEventListener('click', function() {
  let departmentToDraw = document.getElementById('selectDept').value;
  let layoutChoice = document.getElementById('selectLayout').value;
//   let horizontalOffset = parseInt(document.getElementById('horOffset').value);
//   if (horizontalOffset == NaN) {
    let horizontalOffset = 0;
//   }
//   let verticalOffset = parseInt(document.getElementById('vertOffset').value);
//   if (verticalOffset == NaN) {
    let verticalOffset = 0;
//   }
  let datalink = linkResources[departmentToDraw]
  analytics.logEvent('select_content', {
    content_type: "department",
    item_id: departmentToDraw
});
  analytics.logEvent('select_content', {
    content_type: "format",
    item_id: layoutChoice
});
  fetch(datalink)
  .then((response) => response.json())
  .then(function(data) { 
    govData = data;
    let headlineName = data['name']
    if (layoutChoice == "horizontal") {
      drawHorizontal(departmentToDraw, horizontalOffset, verticalOffset)
    }
    if (layoutChoice == "vertical") {
      drawVertical(departmentToDraw, horizontalOffset, verticalOffset)
    }
    if (layoutChoice == "invertedVertical") {
      drawInvertedVertical(departmentToDraw, horizontalOffset, verticalOffset)
    }
  });
})